### ISSUE TITLE
Repo-map can't include file and doesn't ignore the file

### ISSUE THREAD

**Issue by GitIgnoreMaybe** [paul-gauthier/aider#1033]
### Issue

I'm getting an error for "largefolder". I exluded it in the `.aiderignore` and I tried `--subtree-only` both didn't work and give me the following output. Anyone an idea how to fix it?

```
Repo-map can't include /Users/user/dev/project-a/largefolder, it is not a normal file

Unexpected error: litellm.APIConnectionError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10080, in __next__
    self.fetch_sync_stream()
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10175, in fetch_sync_stream
    self.completion_stream = self.make_call(client=litellm.module_level_client)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/llms/anthropic.py", line 577, in make_sync_call
    raise AnthropicError(status_code=response.status_code, message=response.read())
litellm.llms.anthropic.AnthropicError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'

Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10080, in __next__
    self.fetch_sync_stream()
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10175, in fetch_sync_stream
    self.completion_stream = self.make_call(client=litellm.module_level_client)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/llms/anthropic.py", line 577, in make_sync_call
    raise AnthropicError(status_code=response.status_code, message=response.read())
litellm.llms.anthropic.AnthropicError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 900, in send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 1176, in send
    yield from self.show_send_output_stream(completion)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 1250, in show_send_output_stream
    for chunk in completion:
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10166, in __next__
    raise exception_type(
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 8139, in exception_type
    raise e
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 8103, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10080, in __next__
    self.fetch_sync_stream()
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/utils.py", line 10175, in fetch_sync_stream
    self.completion_stream = self.make_call(client=litellm.module_level_client)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/litellm/llms/anthropic.py", line 577, in make_sync_call
    raise AnthropicError(status_code=response.status_code, message=response.read())
litellm.llms.anthropic.AnthropicError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'
```

### Version and model info

Aider v0.48.1
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 170 files
Repo-map: using 1024 tokens

**Comment by Jehu** [comment]
Happens to me also since updated to 0.48.1 this morning.
Worked perfectly yesterday in the same repository.

**Comment by RhydianDowning** [comment]
Same here!!:


> Happens to me also since updated to 0.48.1 this morning. Worked perfectly yesterday in the same repository.

**Comment by Jehu** [comment]
Hah, it seems to be a problem with the Claude Sonnet Model when used via API. Wanted to use sonnet with fabric and get also the error 
```
Error: Fabric is working fine, but claude is overloaded. Please try again later.
Error: Error code: 529 - {'type': 'error', 'error': {'type': 'overloaded_error', 'message': 'Overloaded'}}
```
Seems to be unrelated to aider.chat.

**Comment by GitIgnoreMaybe** [comment]
Sorry, the logs include two issues. One is the Claude api issue, this is unrelated to aider. The other issue is the large folder issue. I did mean the folder issue.

**Comment by cueup** [comment]
experiencing the same issue since the update.

**Comment by paul-gauthier** [comment]
These errors are because Anthropic's API servers are overloaded/down. Aider is simply reporting that the server is broken. 

Anthropic has been having serious issues since yesterday. You can directly check their server status here:

https://status.anthropic.com/

The file is not being included in the repo map because it is not a normal file. Is it a broken symlink perhaps?

**Comment by GitIgnoreMaybe** [comment]
@paul-gauthier 
Thanks a lot for your reply.

**Comment by aligg73** [comment]
I get a similar error, not because of API overload, but because I use a lot of symlinks in my repo.
Is there a way (command-line argument or env variable) to suppress the:

`Repo-map can't include x
`
message?

Thanks
