### ISSUE TITLE
"OSError: [Errno 24] Too many open files" when working with big repos

### ISSUE THREAD

**Issue by davidmigloz** [paul-gauthier/aider#1064]
### Issue

Hello team,

First, thanks for your awesome work 🙌

When working with a large repository, aider hits the system limit on the number of open file descriptors and throws the following error. I'm not sure if there is anything aider can do to prevent this, but otherwise it would be nice if aider could catch this error and suggest the user to use `--subtree-only`.

**Error:**
```
Traceback (most recent call last):
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/mman.py", line 569, in _obtain_region
    r = self.MapRegionCls(a.path_or_fd(), mid.ofs, mid.size, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/util.py", line 126, in __init__
    self._mf = mmap(fd, actual_size, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/main.py", line 533, in main
    coder.show_announcements()
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/coders/base_coder.py", line 395, in show_announcements
    for line in self.get_announcements():
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/coders/base_coder.py", line 159, in get_announcements
    num_files = len(self.repo.get_tracked_files())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/repo.py", line 247, in get_tracked_files
    commit = self.repo.head.commit
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/git/refs/symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/git/refs/symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/git/objects/base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/base.py", line 210, in info
    return self._db_query(sha).info(sha)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/base.py", line 193, in _db_query
    if db.has_object(sha):
       ^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/pack.py", line 91, in has_object
    self._pack_info(sha)
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/pack.py", line 70, in _pack_info
    self._sort_entities()
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/pack.py", line 58, in _sort_entities
    self._entities.sort(key=lambda l: l[0], reverse=True)
    ^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/pack.py", line 54, in _set_cache_
    self.update_cache(force=True)
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/db/pack.py", line 157, in update_cache
    self._entities.append([entity.pack().size(), entity, entity.index().sha_to_index])
                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/pack.py", line 572, in size
    return self._size
           ^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/gitdb/pack.py", line 534, in _set_cache_
    self._cursor = mman.make_cursor(self._packpath).use_region()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/mman.py", line 133, in use_region
    self._region = man._obtain_region(self._rlist, offset, size, flags, False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/mman.py", line 581, in _obtain_region
    return self._obtain_region(a, offset, size, flags, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/mman.py", line 569, in _obtain_region
    r = self.MapRegionCls(a.path_or_fd(), mid.ofs, mid.size, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/pipx/venvs/aider-chat/lib/python3.12/site-packages/smmap/util.py", line 126, in __init__
    self._mf = mmap(fd, actual_size, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files
```

### Version and model info

aider 0.49.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
