### ISSUE TITLE
TypeError when adding a .jpg file to the chat

### ISSUE THREAD

**Issue by Sjlver** [paul-gauthier/aider#1088]
### Issue

I get the following error message after having added a .jpg image to the chat:

```
Traceback (most recent call last):
  File "[redacted]/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "[redacted]/.local/lib/python3.10/site-packages/aider/main.py", line 620, in main
    coder.run()
  File "[redacted]/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 693, in run
    self.run_one(user_message, preproc)
  File "[redacted]/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 734, in run_one
    list(self.send_message(message))
  File "[redacted]/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 956, in send_message
    messages = self.format_messages()
  File "[redacted]/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 915, in format_messages
    messages_tokens = self.main_model.token_count(messages)
  File "[redacted]/.local/lib/python3.10/site-packages/aider/models.py", line 519, in token_count
    return litellm.token_counter(model=self.name, messages=messages)
  File "[redacted]/.local/lib/python3.10/site-packages/litellm/utils.py", line 1994, in token_counter
    num_tokens += calculage_img_tokens(
  File "[redacted]/.local/lib/python3.10/site-packages/litellm/utils.py", line 1841, in calculage_img_tokens
    resized_width, resized_height = resize_image_high_res(
  File "[redacted]/.local/lib/python3.10/site-packages/litellm/utils.py", line 1758, in resize_image_high_res
    if width <= 768 and height <= 768:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

I did the following:
- Add a text file to the chat
- Add a .jpg file to the chat
- Ask Aider to transcribe the jpg and write the results to the text file.

### Version and model info

Aider v0.50.1
Models: claude-3-5-sonnet-20240620 with ♾️ diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 201 files
Repo-map: using 1024 tokens

Command line switches:  --no-auto-commit --no-auto-lint

**Comment by paul-gauthier** [comment]
There's a workaround in the main branch now, which will prevent crashing.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by Sjlver** [comment]
This seems to work now. There are hints about the problem still, but nothing blocking:
- There's an error message: `Unable to count tokens: '<=' not supported between instances of 'NoneType' and 'int'`
- It says `Tokens: 0 sent`

Here's the transcript of the new version:

```
Aider v0.50.2-dev
Models: claude-3-5-sonnet-20240620 with ♾️ diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 201 files
Repo-map: using 1024 tokens
Use /help <question> for help, run "aider --help" to see cmd line args
─────────────────────────────────────────────
> /add public/assets/blog/personal_key_rotation/simplified-asset-graph.jpg

Added [redacted]/public/assets/blog/personal_key_rotation/simplified-asset-graph.jpg to the chat
─────────────────────────────────────────────
public/assets/blog/personal_key_rotation/simplified-asset-graph.jpg
> Please transcribe the content of the simplified-asset-graph.jpg file. It contains a handdrawn sketch of a graph. Print the
 corresponding graphviz representation.

Unable to count tokens: '<=' not supported between instances of 'NoneType' and 'int'

Certainly! I'll transcribe the content of the simplified-asset-graph.jpg file into a Graphviz representation. I'll create a
new file called simplified-asset-graph.dot to store this representation.                                                    
simplified-asset-graph.dot

 <<<<<<< SEARCH
 =======
 digraph AssetGraph {
     // Node definitions
    [redacted]
 }
 >>>>>>> REPLACE

Unable to count tokens: '<=' not supported between instances of 'NoneType' and 'int'

This Graphviz representation captures the structure and relationships shown in the hand-drawn sketch. It includes all the
[redacted]

Tokens: 0 sent, 557 received. Cost: $0.0084 message, $0.0084 session.

Allow creation of new file simplified-asset-graph.dot? n
Skipping edits to simplified-asset-graph.dot
```

Thanks for the quick fix!

**Comment by paul-gauthier** [comment]
This should be fixed properly if you upgrade to the main branch. 

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by pcalatayud-prog** [comment]
I was having the same issue. You solution worked, thank you :)
