### ISSUE TITLE
Cannot add folder via command line 

### ISSUE THREAD

**Issue by quocdat-le-insacvl** [paul-gauthier/aider#1126]
### Issue

Hi,
![image](https://github.com/user-attachments/assets/a1c224e9-4baf-409b-8795-ebd927c57848)

I tried to add a folder to `aider` but it doesn't seem to be working. Instead, I need to add multiple files one by one to the command line. The wildcard * doesn't work either (e.g backend/src/*)

### Version and model info

Aider v0.50.1
Model: Claude Sonnet 3.5

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use whatever methods your shell provides for wildcarding files from the command line.

This doc may also be helpful:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by Jiayou-Chao** [comment]
> Thanks for trying aider and filing this issue.
> 
> You can use whatever methods your shell provides for wildcarding files from the command line.
> 
> This doc may also be helpful:
> 
> https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

This doesn't seem to work for me. I'm using aider on Windows. 
```
> aider my_folder/*.py
Creating empty file C:\Users\user\OneDrive\my_project\my_folder\*.py
Traceback (most recent call last):
  File "C:\Users\user\miniforge3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\miniforge3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\user\.local\bin\aider.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\user\pipx\venvs\aider-chat\lib\site-packages\aider\main.py", line 514, in main
    coder = Coder.create(
  File "C:\Users\user\pipx\venvs\aider-chat\lib\site-packages\aider\coders\base_coder.py", line 151, in create
    res = coder(main_model, io, **kwargs)
  File "C:\Users\user\pipx\venvs\aider-chat\lib\site-packages\aider\coders\base_coder.py", line 342, in __init__
    fname.touch()
  File "C:\Users\user\miniforge3\lib\pathlib.py", line 1168, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "C:\Users\user\miniforge3\lib\pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\OneDrive\\my_project\\my_folder\\*.py'

**Comment by paul-gauthier** [comment]
Are you using Command Prompt (cmd.exe)? I don't think it supports expanding wildcards unfortunately.

You can do `/add my_folder\*.py` from within aider.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
