### ISSUE TITLE
aider crashes when having error on the /run command

### ISSUE THREAD

**Issue by ameramayreh** [paul-gauthier/aider#114]
Thanks for this great project.

When I use wrong parameters with the `/run` command, I got this error and aider crashed.
I used Aider v0.8.3.

Should this be handled to avoid crash?

```sh
Error running command: [WinError 87] The parameter is incorrect
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\main.py", line 373, in main
    coder.run()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\base_coder.py", line 388, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\base_coder.py", line 457, in run_loop
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\commands.py", line 67, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\commands.py", line 45, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\commands.py", line 345, in cmd_run
    self.io.tool_output(combined_output)
                        ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'combined_output' where it is not associated with a value
```

https://github.com/paul-gauthier/aider/blob/e7692fc9d130acfbb2c4a3d9cb63a78fa5b47483/aider/commands.py#L345C33-L345C33

**Comment by paul-gauthier** [comment]
Thanks for the PR!
