### ISSUE TITLE
Request: Docker Image

### ISSUE THREAD

**Issue by dan-willett** [paul-gauthier/aider#117]
I am trying to run aider on Ubuntu, but I get the error: externally-managed-environment

Is it possible that somebody could create a docker image to run this in?

**Comment by joshuavial** [comment]
Here is a PR with a docker image that works on my system @dan-willett https://github.com/paul-gauthier/aider/pull/119/files

Unsure if @paul-gauthier will want it in the main code base in this form but it should get you started. ChatGPT is pretty good at debugging docker stuff so should be able to help if you have issues - e.g. on my system docker needs sudo to run, it might be different on yours.

**Comment by paul-gauthier** [comment]
Thanks @joshuavial !

Let me think about whether this should get merged into the main codebase, where to put it, etc.

**Comment by paul-gauthier** [comment]
FYI, I built a simple docker image and published it to docker hub. See the readme below for details:

https://github.com/paul-gauthier/aider/blob/main/docker/README.md

**Comment by robertofabrizi** [comment]
@paul-gauthier Can you help me debug this issue related to docker? 

```
roberto@nuc8i7beh:~/maas-gauges$ git config user.email "my@email"
roberto@nuc8i7beh:~/maas-gauges$ git config user.name "account"
roberto@nuc8i7beh:~/maas-gauges$ docker run -it --volume .:/app paulgauthier/aider --openai-api-key "sk-B..."
Unable to find image 'paulgauthier/aider:latest' locally
latest: Pulling from paulgauthier/aider
1f7ce2fa46ab: Pull complete
442c5d63eafd: Pull complete
0b479d7f68f8: Pull complete
2a12c810a227: Pull complete
6a07a7337a53: Pull complete
d61d4899dcae: Pull complete
9191e9a49246: Pull complete
8f0a1302ebd5: Pull complete
Digest: sha256:9e482448365e98219f012b725d92ee765a5a0859260d653e3e5f021c4be69d12
Status: Downloaded newer image for paulgauthier/aider:latest
Aider v0.18.1
Traceback (most recent call last):
  File "/usr/local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/aider/main.py", line 471, in main
    check_gitignore(git_root, io)
  File "/usr/local/lib/python3.10/site-packages/aider/main.py", line 79, in check_gitignore
    if repo.ignored(".aider"):
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 878, in ignored
    proc: str = self.git.check_ignore(*paths)
  File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 736, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 1316, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 1111, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git check-ignore .aider
  stderr: 'fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:

        git config --global --add safe.directory /app'
roberto@nuc8i7beh:~/maas-gauges$ git config --global --add safe.directory '*'
```

But the error is still present, I used * as directories since /app is a container specific path, but that didn't help (I then tried /app specifically, but nothing).
