### ISSUE TITLE
Automatic update fails on Windows if multiple sessions open

### ISSUE THREAD

**Issue by ctoth** [paul-gauthier/aider#1195]
### Issue

If you already have a session of Aider open and then launch another, perhaps the next day, and an update is available, you will get something similar to the following on Windows:

```
C:\Users\Q\src\audiom\layerloader>aider
Newer aider version v0.53.0 is available. To upgrade, run:

C:\Users\Q\scoop\apps\python311\current\python.exe -m pip install --upgrade aider-chat
Run pip install? [Y/n] y

Installing:  C:\Users\Q\scoop\apps\python311\current\python.exe -m pip install --upgrade aider-chat


Installation failed.

Requirement already satisfied: aider-chat in c:\users\q\scoop\apps\python311\current\lib\site-packages (0.52.0)
Collecting aider-chat
  Downloading aider_chat-0.53.0-py3-none-any.whl.metadata (19 kB)
[snip]
Downloading aider_chat-0.53.0-py3-none-any.whl (196 kB)
   -------------------------------------- 196.6/196.6 kB 660.9 kB/s eta 0:00:00
Installing collected packages: aider-chat
  Attempting uninstall: aider-chat
    Found existing installation: aider-chat 0.52.0
    Uninstalling aider-chat-0.52.0:
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is
being used by another process: 'c:\\users\\q\\scoop\\persist\\python311\\scripts\\aider.exe'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Q\scoop\apps\python311\current\python.exe -m pip install --upgrade pip


Aider v0.52.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 61 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /exit


C:\Users\Q\src\audiom\layerloader>aider
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Q\scoop\apps\python311\current\Scripts\aider.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'aider.main'
```

You will then need to re-install with pip once you tskill all Aider instances.
Instead, we should probably block the autoupgrade or prompt the user to shut down the other Aiders.

I propose searching for active Aider executables using one of the following methods:

Method 1 (Cleaner) PSUtil, requires an extra dependency.

Method 2 (Meh):

```
import subprocess
import sys
import os

def is_aider_already_running():
    if sys.platform != 'win32':
        return False # do we need to care about this on Non-Windows?
    
    current_pid = os.getpid()
    
    try:
        # Get all running aider.exe processes
        output = subprocess.check_output('tasklist /FI "IMAGENAME eq aider.exe" /FO CSV /NH', shell=True, text=True)
        
        # Split the output into lines and process each line
        for line in output.strip().split('\n'):
            if line:
                # Parse the CSV output
                parts = line.strip('"').split('","')
                if len(parts) >= 2:
                    process_name, pid = parts[0], parts[1]
                    
                    # Check if it's aider.exe and not our current process
                    if process_name.lower() == 'aider.exe' and int(pid) != current_pid:
                        return True
        
        return False
    except subprocess.CalledProcessError:
        return False
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

In this situation you should just fall back to running the install manually. Aider now recommends this on Window in the latest builds.

```
C:\Users\Q\scoop\apps\python311\current\python.exe -m pip install --upgrade aider-chat
```
