### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'

### ISSUE THREAD

**Issue by lsscodes** [paul-gauthier/aider#1207]
### Issue

In stalled aider-chat in a clean conda environment on windows and when I run aider after installation, it returned following error

TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'

`(aider) C:\Users\tcmkorp>aider
Traceback (most recent call last):
  File "C:\Users\tcmkorp\.conda\envs\aider\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tcmkorp\.conda\envs\aider\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\tcmkorp\.conda\envs\aider\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\tcmkorp\.conda\envs\aider\lib\site-packages\aider\main.py", line 512, in main
    git_root = setup_git(git_root, io)
  File "C:\Users\tcmkorp\.conda\envs\aider\lib\site-packages\aider\main.py", line 115, in setup_git
    git_root = setup_git_home(io)
  File "C:\Users\tcmkorp\.conda\envs\aider\lib\site-packages\aider\main.py", line 70, in setup_git_home
    new_dir = home / project_name
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'`

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This issue should be fixed in the main branch. You should be able to upgrade with `aider --install-main-branch`.

Or you could do this:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by lsscodes** [comment]
@paul-gauthier thanks for the fix. it is working now. Closing the thread/issue
