### ISSUE TITLE
Uncaught AttributeError in __main__.py line 7

### ISSUE THREAD

**Issue by vsvito420** [paul-gauthier/aider#1226]
Aider version: 0.54.7-dev

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 764, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 753, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 204, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 179, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 1079, in cmd_settings
    settings = format_settings(self.parser, self.args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "format_settings.py", line 13, in format_settings
    show = scrub_sensitive_info(args, parser.format_values())
                                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'format_values'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
