### ISSUE TITLE
Uncaught UnicodeDecodeError in codecs.py line 322

### ISSUE THREAD

**Issue by shamshudhin** [paul-gauthier/aider#1230]
Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 764, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 753, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 204, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 179, in do_run
    return cmd_method(args)
  File "commands.py", line 252, in cmd_lint
    errors = self.coder.linter.lint(fname)
  File "linter.py", line 79, in lint
    code = Path(fname).read_text(self.encoding)
  File "pathlib.py", line 1135, in read_text
    return f.read()
  File "codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
