### ISSUE TITLE
Uncaught PortAudioError in sounddevice.py line 569 when no audio device present

### ISSUE THREAD

**Issue by Nucs** [paul-gauthier/aider#1237]
Aider version: 0.54.7

I tried calling /voice when I had no audio devices (I must connect to bluetooth first).

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 764, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 753, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 204, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 179, in do_run
    return cmd_method(args)
  File "commands.py", line 968, in cmd_voice
    text = self.voice.record_and_transcribe(history, language=self.voice_language)
  File "voice.py", line 72, in record_and_transcribe
    return self.raw_record_and_transcribe(history, language)
  File "voice.py", line 82, in raw_record_and_transcribe
    sample_rate = int(self.sd.query_devices(None, "input")["default_samplerate"])
  File "sounddevice.py", line 569, in query_devices
    raise PortAudioError(f'Error querying device {device}')
sounddevice.PortAudioError: Error querying device -1

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
