### ISSUE TITLE
Uncaught AssertionError in fun.py line 210

### ISSUE THREAD

**Issue by 0xideas** [paul-gauthier/aider#1241]
Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 550, in main
    coder.show_announcements()
  File "base_coder.py", line 444, in show_announcements
    for line in self.get_announcements():
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 192, in get_announcements
    num_files = len(self.repo.get_tracked_files())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 266, in get_tracked_files
    staged_files = [path for path, _ in index.entries.keys()]
                                        ^^^^^^^^^^^^^
  File "util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "base.py", line 168, in _set_cache_
    self._deserialize(stream)
  File "base.py", line 197, in _deserialize
    self.version, self.entries, self._extension_data, _conten_sha = read_cache(stream)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "fun.py", line 252, in read_cache
    version, num_entries = read_header(stream)
                           ^^^^^^^^^^^^^^^^^^^
  File "fun.py", line 210, in read_header
    assert version in (1, 2)
           ^^^^^^^^^^^^^^^^^
AssertionError

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Looks like you are using a git repo with a version that aider doesn't support. See #211.

But aider shouldn't hard crash. The fix for that is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
