### ISSUE TITLE
Uncaught BadObject in base.py line 197

### ISSUE THREAD

**Issue by stepwise-ai-dev** [paul-gauthier/aider#1248]
Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 770, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1195, in send_message
    add_rel_files_message = self.check_for_file_mentions(content)
  File "base_coder.py", line 1321, in check_for_file_mentions
    mentioned_rel_fnames = self.get_file_mentions(content)
  File "base_coder.py", line 1296, in get_file_mentions
    addable_rel_fnames = self.get_addable_relative_files()
  File "base_coder.py", line 1630, in get_addable_relative_files
    all_files = set(self.get_all_relative_files())
  File "base_coder.py", line 1615, in get_all_relative_files
    files = self.repo.get_tracked_files()
  File "repo.py", line 249, in get_tracked_files
    commit = self.repo.head.commit
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
  File "base.py", line 197, in _db_query
    raise BadObject(sha)
gitdb.exc.BadObject: BadObject: b'1a37994421acf59ae35cd718b181dd959b976066'

```

**Comment by paul-gauthier** [comment]
Is your git repo corrupted?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
