### ISSUE TITLE
Uncaught GitCommandError in cmd.py line 1388

### ISSUE THREAD

**Issue by learhy** [paul-gauthier/aider#1253]
Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 770, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1157, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1835, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 94, in commit
    diffs = self.get_diffs(fnames)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 227, in get_diffs
    diffs += self.repo.git.diff(*index_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git diff --cached -- ../voice-memo-transcriber-ios/VoiceMemoTranscriber/NetworkManager.swift ../voice-memo-transcriber-ios/VoiceMemoTranscriber/VoiceMemoTranscriberApp.swift ../voice-memo-transcriber-ios/project.yml ../voice-memo-transcriber-ios/VoiceMemoTranscriber/Info.plist ../voice-memo-transcriber-ios/VoiceMemoTranscriber/ContentView.swift
  stderr: 'fatal: ../voice-memo-transcriber-ios/VoiceMemoTranscriber/NetworkManager.swift: '../voice-memo-transcriber-ios/VoiceMemoTranscriber/NetworkManager.swift' is outside repository at '/Users/dan.rohan/My Drive/software_projects/voice-memo-transcriber-ios''

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I'm a little confused about how you were able to generate this error. Any chance you recall how you launched aider? Like which dir were you in and how did you add files to the chat?

Because it's odd that all the filenames in that error start with `../voice-memo-transcriber-ios`.

All that said, aider shouldn't hard crash in this situation. I'll try and resolve that. But I'd like to also prevent this situation from arising at all.

**Comment by paul-gauthier** [comment]
The fix for the actual exception is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
