### ISSUE TITLE
Uncaught OSError in pathlib.py line 331

### ISSUE THREAD

**Issue by jaswindersinghdhami** [paul-gauthier/aider#1254]
Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 512, in main
    coder = Coder.create(
  File "base_coder.py", line 156, in create
    res = coder(main_model, io, **kwargs)
  File "base_coder.py", line 354, in __init__
    fname.touch()
  File "pathlib.py", line 1168, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
OSError: [Errno 30] Read-only file system: '/reset'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Looks like you tried to run aider on a read only filesystem. That won't really work, but aider shouldn't crash. I've fixed that.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
