### ISSUE TITLE
Uncaught BadObject in base.py line 197

### ISSUE THREAD

**Issue by Talonkinkade** [paul-gauthier/aider#1262]
Aider version: 0.54.8
Python version: 3.11.7
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 680, in main
    coder.run()
  File "base_coder.py", line 729, in run
    self.show_undo_hint()
  File "base_coder.py", line 1859, in show_undo_hint
    if self.commit_before_message[-1] != self.repo.get_head():
                                         ^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 377, in get_head
    return self.repo.head.commit.hexsha
           ^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
           ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 197, in _db_query
    raise BadObject(sha)
gitdb.exc.BadObject: BadObject: b'e12d661db41c09564e732ac5723c128c6afa7309'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
