### ISSUE TITLE
Uncaught OSError in pathlib.py line 1110

### ISSUE THREAD

**Issue by khalid75** [paul-gauthier/aider#1270]
Aider version: 0.54.8
Python version: 3.9.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 385, in main
    io = InputOutput(
  File "io.py", line 218, in __init__
    self.append_chat_history(f"\n# aider chat started at {current_time}\n\n")
  File "io.py", line 553, in append_chat_history
    with self.chat_history_file.open("a", encoding=self.encoding) as f:
  File "pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 30] Read-only file system: '.aider.chat.history.md'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
