### ISSUE TITLE
Uncaught TypeError in pty_spawn.py line 281

### ISSUE THREAD

**Issue by harperreed** [paul-gauthier/aider#1276]
Aider version: 0.54.10
Python version: 3.12.5
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1212, in send_message
    test_errors = self.commands.cmd_test(self.test_cmd)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 746, in cmd_test
    return self.cmd_run(args, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 757, in cmd_run
    exit_status, combined_output = run_cmd(args, verbose=self.verbose)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 14, in run_cmd
    return run_cmd_pexpect(command, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 73, in run_cmd_pexpect
    child = pexpect.spawn(shell, args=["-c", command], encoding="utf-8")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "pty_spawn.py", line 281, in _spawn
    self.name = '<' + ' '.join(self.args) + '>'
                      ^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, list found

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I can't figure out how you triggered this error. How did you set the `test-cmd`?

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
