### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by lkonga** [paul-gauthier/aider#1278]
Aider version: 0.54.10
Python version: 3.11.2
Platform: Linux-6.10.0-linuxkit-x86_64-with-glibc2.36
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.10.0-linuxkit (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1862, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 106, in commit
    commit_message = self.get_commit_message(diffs, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 186, in get_commit_message
    commit_message = simple_send_with_retries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
    ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

aider --verbose output:
```
$ aider-vertex-ai-sonnet-35 --verbose
Config files search order, if no --config:
  - /workspace/.aider.conf.yml (exists)
  - /home/vscode/.aider.conf.yml (exists)
Loaded /workspace/.env
Current version: 0.54.10
Latest version: 0.54.10
No update available
Command Line Args:   --dark-mode --model vertex_ai/claude-3-5-sonnet@20240620 --verbose

Environment Variables:
  ANTHROPIC_API_KEY: ...ngAA
Config File (/workspace/.aider.conf.yml):
  openai-api-key:    ...6b21
  openai-api-base:   https://openrouter.ai/api/v1
  weak-model:        vertex_ai/claude-3-5-sonnet@20240620
  llm-history-file:  .aider.llm.history
  lint-cmd:          pre-commit run --files
  auto-lint:         False
  vim:               True

Defaults:
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --map-refresh:     auto
  --cache-keepalive-pings:0
  --map-multiplier-no-files:2
  --env-file:        /workspace/.env
  --input-history-file:/workspace/.aider.input.history
  --chat-history-file:/workspace/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /workspace/.aiderignore
  --test-cmd:        []
  --voice-language:  en
  --encoding:        utf-8

Option settings:
  - aiderignore: /workspace/.aiderignore
  - anthropic_api_key: ...ngAA
  - apply: None
  - assistant_output_color: #00FFFF
  - attribute_author: True
  - attribute_commit_message_author: False
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: False
  - auto_test: False
  - cache_keepalive_pings: 0
  - cache_prompts: False
  - chat_history_file: /workspace/.aider.chat.history.md
  - check_update: True
  - code_theme: monokai
  - commit: False
  - commit_prompt: None
  - config: None
  - dark_mode: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - encoding: utf-8
  - env_file: /workspace/.env
  - exit: False
  - file: None
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: /workspace/.aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: ['pre-commit run --files']
  - llm_history_file: .aider.llm.history
  - map_multiplier_no_files: 2
  - map_refresh: auto
  - map_tokens: None
  - max_chat_history_tokens: None
  - message: None
  - message_file: None
  - model: vertex_ai/claude-3-5-sonnet@20240620
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - models: None
  - openai_api_base: https://openrouter.ai/api/v1
  - openai_api_deployment_id: None
  - openai_api_key: ...6b21
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_repo_map: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - tool_error_color: #FF3333
  - tool_output_color: None
  - upgrade: False
  - user_input_color: #32FF32
  - verbose: True
  - verify_ssl: True
  - vim: True
  - voice_language: en
  - weak_model: vertex_ai/claude-3-5-sonnet@20240620
  - yes: None

No model settings files loaded
Searched for model settings files:
  - /home/vscode/.aider.model.settings.yml
  - /workspace/.aider.model.settings.yml
Model info:
  max_tokens: 4096
  max_input_tokens: 200000
  max_output_tokens: 4096
  input_cost_per_token: 3e-06
  output_cost_per_token: 1.5e-05
  litellm_provider: vertex_ai-anthropic_models
  mode: chat
  supports_function_calling: True
  supports_vision: True
  supports_assistant_prefill: True
RepoMap initialized with map_mul_no_files: 2

Aider v0.54.10
Model: vertex_ai/claude-3-5-sonnet@20240620 with diff edit format, infinite output
Git repo: .git with 58 files
Repo-map: using 1024 tokens, auto refresh
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args
```

**Comment by lkonga** [comment]
error was with latest litellm from `main` (`litellm-1.44.14`), after trying with aider's litellm (`1.44.7`) there is no error.

closing issue

**Comment by thiswillbeyourgithub** [comment]
Can you please reopen?

I'm hitting this error too but simply rolling back litellm is not an appropriate workaround. Litellm is on a rapid release cycle and quickly adding features so in my case I prefer to stay up to date with it.

It's making aider unusable for me so pinging @paul-gauthier :)

**Comment by paul-gauthier** [comment]
Aider pins the versions of its dependencies. Currently aider is setup to install with litellm 1.44.7.

```
$ grep litellm== requirements.txt
litellm==1.44.7
```

Aider is not intended/expected to work with different versions of litellm.

Why have you installed a newer version? If you need it for some other reason, you may want to consider installing aider with pipx.

https://aider.chat/docs/install/pipx.html

**Comment by thiswillbeyourgithub** [comment]
I stand corrected. Sorry for tbe disturbance then !

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

**Comment by alexanderkjeldaas** [comment]
Can aider be updated to use litellm 1.44.22?  This will fix nixpkgs.

**Comment by paul-gauthier** [comment]
Main branch has been bumped to use the latest litellm (1.47.0). This will release as aider v0.57.0 later today.

**Comment by paul-gauthier** [comment]
Aider v0.57.0 is out now, using latest litellm.
