### ISSUE TITLE
Uncaught ValueError in ntpath.py line 747

### ISSUE THREAD

**Issue by js-commit** [paul-gauthier/aider#1288]
## How it happened
Entered command `/map`  - my git repo (dir) is a repo with with Ruby, some .ahk and .ts/.js, most Ruby though.

Aider version: 0.54.10
Python version: 3.10.11
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.32.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1083, in send_message
    chunks = self.format_messages()
  File "base_coder.py", line 1021, in format_messages
    chunks = self.format_chat_chunks()
  File "base_coder.py", line 971, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
  File "base_coder.py", line 627, in get_repo_messages
    repo_content = self.get_repo_map()
  File "base_coder.py", line 599, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
  File "repomap.py", line 124, in get_repo_map
    files_listing = self.get_ranked_tags_map(
  File "repomap.py", line 466, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
  File "repomap.py", line 497, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
  File "repomap.py", line 322, in get_ranked_tags
    rel_fname = self.get_rel_fname(fname)
  File "repomap.py", line 159, in get_rel_fname
    return os.path.relpath(fname, self.root)
  File "ntpath.py", line 747, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
