### ISSUE TITLE
Error on `/undo` when working on top of a past commit. Uncaught TypeError in symbolic.py line 413

### ISSUE THREAD

**Issue by kennyfrc** [paul-gauthier/aider#1291]
Steps to reproduce:
1. Checkout to an older commit
2. Allow aider to enter in some code
3. Hit `/undo` after

Aider version: 0.54.7

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 764, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 753, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 204, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 179, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 439, in cmd_undo
    current_branch = self.coder.repo.repo.active_branch.name
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 1036, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 413, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'b3911e74e65d76550a2fe38a7e8c31c1e3a4a1bc'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by kennyfrc** [comment]
Hi @paul-gauthier! Thanks for looking into this. Unfortunately, I'm still getting the same error. 

Here's a more descriptive version of what happened in case it helps:
1. Checkout to an older commit (which gets us into detached `HEAD` state)
2. Ask aider to change some code, which should create a new commit successfully
3. Enter `/undo` after. I expect this to go to the previous commit, but it throws the below error.

In a normal git workflow, checking out to the previous commit also works and does not throw an error.

----

Uncaught TypeError in symbolic.py line 413                                                     

Aider version: 0.54.13.dev14+gc8b2024f
Python version: 3.11.5
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.41.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 691, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 472, in cmd_undo
    current_branch = self.coder.repo.repo.active_branch.name
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 1036, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 413, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'd1c5f66cc0bfb74c96123d62391e9c487b2de534'

```
