### ISSUE TITLE
Uncaught ImportError in utils.py line 50

### ISSUE THREAD

**Issue by DeathGanker** [paul-gauthier/aider#1292]
Aider version: 0.54.12
Python version: 3.11.9
Platform: macOS-14.1.2-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.1.0 (64bit)
Git version: git version 2.39.3 (Apple Git-145)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 498, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 486, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 660, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 780, in <module>
    from .cost_calculator import completion_cost
  File "cost_calculator.py", line 24, in <module>
    from litellm.utils import (
  File "utils.py", line 50, in <module>
    from openai.lib import _parsing, _pydantic
ImportError: cannot import name '_parsing' from 'openai.lib' (unknown location)

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? It looks like you don't have the correct set of dependencies installed.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
