### ISSUE TITLE
Uncaught ImportError in _compat.py line 57

### ISSUE THREAD

**Issue by ariel-tar99** [paul-gauthier/aider#1296]
Aider version: 0.54.10
Python version: 3.12.1
Platform: macOS-14.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.1.0 (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1105, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1377, in send
    hash_object, completion = send_completion(
                              ^^^^^^^^^^^^^^^^
  File "sendchat.py", line 86, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "caching.py", line 22, in <module>
    from openai._models import BaseModel as OpenAIObject
  File "__init__.py", line 8, in <module>
    from . import types
  File "__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "batch.py", line 7, in <module>
    from .._models import BaseModel
  File "_models.py", line 36, in <module>
    from ._utils import (
  File "__init__.py", line 3, in <module>
    from ._utils import (
  File "_utils.py", line 24, in <module>
    from .._compat import parse_date as parse_date, parse_datetime as parse_datetime
  File "_compat.py", line 57, in <module>
    from pydantic.typing import (
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/Users/arieltarayants/genalpha/genalpha-backend/venv/lib/python3.12/site-packages/pydantic/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1107, in send_message
    except retry_exceptions() as err:
           ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 24, in retry_exceptions
    litellm.exceptions.APIConnectionError,
    ^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "caching.py", line 22, in <module>
    from openai._models import BaseModel as OpenAIObject
  File "__init__.py", line 8, in <module>
    from . import types
  File "__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "batch.py", line 7, in <module>
    from .._models import BaseModel
  File "_models.py", line 36, in <module>
    from ._utils import (
  File "__init__.py", line 3, in <module>
    from ._utils import (
  File "_utils.py", line 24, in <module>
    from .._compat import parse_date as parse_date, parse_datetime as parse_datetime
  File "_compat.py", line 57, in <module>
    from pydantic.typing import (
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/Users/arieltarayants/genalpha/genalpha-backend/venv/lib/python3.12/site-packages/pydantic/typing.py)

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? It looks like you don't have the correct set of dependencies installed.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
