### ISSUE TITLE
Uncaught AttributeError in wholefile_coder.py line 130

### ISSUE THREAD

**Issue by CD1010** [paul-gauthier/aider#1298]
I went into folder with starter vite project
asked it to create src/components folder
entered 
ls  
hit return.
Got this error

Aider version: <module 'aider.__version__' from 'C:\\Users\\cdepa\\miniconda3\\envs\\aider\\Lib\\site-packages\\aider\\__version__.py'>
Python version: 3.12.4
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.43.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1146, in send_message
    self.live_incremental_response(True)
  File "base_coder.py", line 1506, in live_incremental_response
    show_resp = self.render_incremental_response(final)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "wholefile_coder.py", line 18, in render_incremental_response
    return self.get_edits(mode="diff")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "wholefile_coder.py", line 100, in get_edits
    output += self.do_live_diff(full_path, new_lines, False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "wholefile_coder.py", line 130, in do_live_diff
    orig_lines = self.io.read_text(full_path).splitlines(keepends=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
