### ISSUE TITLE
Uncaught TypeError in pty_spawn.py line 281

### ISSUE THREAD

**Issue by fr34k8** [paul-gauthier/aider#1302]
Aider version: 0.54.12
Python version: 3.12.5
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1212, in send_message
    test_errors = self.commands.cmd_test(self.test_cmd)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 746, in cmd_test
    return self.cmd_run(args, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 757, in cmd_run
    exit_status, combined_output = run_cmd(args, verbose=self.verbose)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 14, in run_cmd
    return run_cmd_pexpect(command, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 73, in run_cmd_pexpect
    child = pexpect.spawn(shell, args=["-c", command], encoding="utf-8")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "pty_spawn.py", line 281, in _spawn
    self.name = '<' + ' '.join(self.args) + '>'
                      ^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, list found

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What did you type into aider to trigger this error?

**Comment by paul-gauthier** [comment]
BTW, the fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by fr34k8** [comment]
@paul-gauthier was fixed meanwhile and with main branch, back then.
