### ISSUE TITLE
Uncaught NoConsoleScreenBufferError in win32.py line 219

### ISSUE THREAD

**Issue by cristianmonsalve14** [paul-gauthier/aider#1304]
Aider version: 0.54.12
Python version: 3.12.3
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.33.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 466, in main
    check_gitignore(git_root, io)
  File "main.py", line 132, in check_gitignore
    if ask and not io.confirm_ask(f"Add {pat} to .gitignore (recommended)?"):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "io.py", line 453, in confirm_ask
    res = prompt(
          ^^^^^^^
  File "prompt.py", line 1423, in prompt
    session: PromptSession[str] = PromptSession(history=history)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "prompt.py", line 476, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "prompt.py", line 727, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "application.py", line 267, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "current.py", line 67, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "win32.py", line 115, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "win32.py", line 219, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: Found xterm, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How are you running aider? It looks like you don't have a working terminal?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
