### ISSUE TITLE
Uncaught ValueError in ntpath.py line 744

### ISSUE THREAD

**Issue by alberto071968** [paul-gauthier/aider#1305]
Aider version: 0.54.12
Python version: 3.10.6
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.41.0.windows.3

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
  File "base_coder.py", line 738, in get_input
    inchat_files = self.get_inchat_relative_files()
  File "base_coder.py", line 1630, in get_inchat_relative_files
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
  File "base_coder.py", line 1630, in <listcomp>
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
  File "base_coder.py", line 1627, in get_rel_fname
    return os.path.relpath(fname, self.root)
  File "ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'F:'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by alberto071968** [comment]
Hello Paul, I still get an error when passing an imagine in the clipboard.
This is what I get:


Added clipboard image to the chat:
C:\Users\Alberto\AppData\Local\Temp\tmpzy8v9gn4\clipboard_image.png

# Uncaught ValueError in ntpath.py line 744

Aider version: 0.55.1.dev10+g18bf3a9f
Python version: 3.10.6
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.41.0.windows.3

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
  File "base_coder.py", line 738, in get_input
    inchat_files = self.get_inchat_relative_files()
  File "base_coder.py", line 1630, in get_inchat_relative_files
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
  File "base_coder.py", line 1630, in <listcomp>
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
  File "base_coder.py", line 1627, in get_rel_fname
    return os.path.relpath(fname, self.root)
  File "ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'F:'

```

Please consider reporting this bug to help improve aider!
Open a GitHub Issue pre-filled with the above error in your browser? (Y/n)


Thanks for your amazing work !

Alberto

Il giorno mar 3 set 2024 alle ore 17:15 paul-gauthier <
***@***.***> ha scritto:

**Comment by paul-gauthier** [comment]
Sorry! It should really be fixed in the main branch now. Please do let me know if it works for you this time.

**Comment by alberto071968** [comment]
Great, works fine !

Thank you Paul.

Alberto

Il giorno mer 4 set 2024 alle ore 23:12 paul-gauthier <
***@***.***> ha scritto:
