### ISSUE TITLE
Uncaught AuthenticationError in utils.py line 6747 - Conflicts between models

### ISSUE THREAD

**Issue by ignacio-chiazzo** [paul-gauthier/aider#1306]
```
Aider version: 0.54.12
Python version: 3.9.6
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.46.0
```

The OpenAI key is not set but i'm using a different model 🤔 , I'm not sure why I got the following error:

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 928, in completion
    openai_client = self._get_openai_client(
  File "openai.py", line 750, in _get_openai_client
    _new_client = OpenAI(
  File "_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1345, in completion
    raise e
  File "main.py", line 1318, in completion
    response = openai_chat_completions.completion(
  File "openai.py", line 1041, in completion
    raise OpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.openai.OpenAIError: Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 928, in completion
    openai_client = self._get_openai_client(
  File "openai.py", line 750, in _get_openai_client
    _new_client = OpenAI(
  File "/Users/ignaciochiazzocardarello/Library/Python/3.9/lib/python/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    saved_message = self.auto_commit(edited)
  File "base_coder.py", line 1862, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
  File "repo.py", line 106, in commit
    commit_message = self.get_commit_message(diffs, context)
  File "repo.py", line 186, in get_commit_message
    commit_message = simple_send_with_retries(
  File "sendchat.py", line 44, in wrapper
    return decorated_func(*args, **kwargs)
  File "_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "sendchat.py", line 106, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
  File "sendchat.py", line 86, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1078, in wrapper
    raise e
  File "utils.py", line 966, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2766, in completion
    raise exception_type(
  File "utils.py", line 8438, in exception_type
    raise e
  File "utils.py", line 6747, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Traceback (most recent call last):
  File "openai.py", line 1033, in completion
    raise e
  File "openai.py", line 928, in completion
    openai_client = self._get_openai_client(
  File "openai.py", line 750, in _get_openai_client
    _new_client = OpenAI(
  File "/Users/ignaciochiazzocardarello/Library/Python/3.9/lib/python/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


```

### 

I changed models using `/model`, but it seems like it keeps checking for OpenAI 🤔 

![Image](https://github.com/user-attachments/assets/c1dc29c7-c199-415e-9666-a72e97b65b30)

**Comment by paul-gauthier** [comment]
I think you used `/model` to change the main model. But there is also a weak model, which may have stated set to an OpenAI model. Launch with `aider --sonnet` if you want to use sonnet.

**Comment by ignacio-chiazzo** [comment]
oh I think you're right for some reason the weak model isn't updated after running `/model` sometimes. I will report it back if I see it again; 

Is adding a warning when the Weak model is different than the main model an option? 

Thanks for your great work btw!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
