### ISSUE TITLE
Uncaught UnableToCountRepoFiles in repo.py line 279git 

### ISSUE THREAD

**Issue by aibots-team** [paul-gauthier/aider#1309]
Aider version: 0.54.10
Python version: 3.12.4
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "repo.py", line 255, in get_tracked_files
    commit = self.repo.head.commit
             ^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
           ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 197, in _db_query
    raise BadObject(sha)
gitdb.exc.BadObject: BadObject: b'22959bcdd3b124a642e2acaadc050e36d0520f52'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 745, in get_input
    self.get_addable_relative_files(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1656, in get_addable_relative_files
    all_files = set(self.get_all_relative_files())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1641, in get_all_relative_files
    files = self.repo.get_tracked_files()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 279, in get_tracked_files
    raise UnableToCountRepoFiles(f"Error getting tracked files: {str(e)}")
aider.repo.UnableToCountRepoFiles: Error getting tracked files: BadObject: b'22959bcdd3b124a642e2acaadc050e36d0520f52'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
