### ISSUE TITLE
Uncaught AttributeError in scrape.py line 159

### ISSUE THREAD

**Issue by anranik** [paul-gauthier/aider#1314]
Aider version: 0.54.12
Python version: 3.11.7
Platform: Windows-10-10.0.26120-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.42.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "scrape.py", line 158, in scrape_with_playwright
    response = page.goto(url, wait_until="networkidle", timeout=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_generated.py", line 9303, in goto
    self._sync(
  File "_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "_page.py", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_frame.py", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 5000ms exceeded.
=========================== logs ===========================
navigating to "https://huggingface.co/THUDM/CogVideoX-2b", waiting until "networkidle"
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 217, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 192, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 912, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 933, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 759, in preproc_user_input
    self.check_for_urls(inp)
  File "base_coder.py", line 794, in check_for_urls
    inp += self.commands.cmd_web(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 156, in cmd_web
    content = self.scraper.scrape(url) or ""
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "scrape.py", line 97, in scrape
    content, mime_type = self.scrape_with_playwright(url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scrape.py", line 159, in scrape_with_playwright
    except playwright._impl._errors.TimeoutError:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'playwright._impl' has no attribute '_errors'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
