### ISSUE TITLE
Uncaught OSError in __init__.py line 797

### ISSUE THREAD

**Issue by rdmayo21** [paul-gauthier/aider#1316]
Aider version: 0.54.12
Python version: 3.9.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 759, in preproc_user_input
    self.check_for_urls(inp)
  File "base_coder.py", line 794, in check_for_urls
    inp += self.commands.cmd_web(url)
  File "commands.py", line 156, in cmd_web
    content = self.scraper.scrape(url) or ""
  File "scrape.py", line 110, in scrape
    content = self.html_to_markdown(content)
  File "scrape.py", line 225, in html_to_markdown
    md = pypandoc.convert_text(page_source, "markdown", format="html")
  File "__init__.py", line 92, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
  File "__init__.py", line 364, in _convert_input
    _ensure_pandoc_path()
  File "__init__.py", line 797, in _ensure_pandoc_path
    raise OSError("No pandoc was found: either install pandoc and add it\n"
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
