### ISSUE TITLE
Uncaught ImportError in __init__.py line 78

### ISSUE THREAD

**Issue by ivnad95** [paul-gauthier/aider#1320]
Aider version: <module 'aider.__version__' from '/home/runner/.local/lib/python3.10/site-packages/aider/__version__.py'>
Python version: 3.10.11
Platform: Linux-6.5.0-1025-gcp-x86_64-with-glibc2.37
Python implementation: CPython
Virtual environment: No
OS: Linux 6.5.0-1025-gcp (64bit)
Git version: git version 2.42.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 498, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "models.py", line 486, in __init__
    res = self.validate_environment()
  File "models.py", line 660, in validate_environment
    res = litellm.validate_environment(model)
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 780, in <module>
    from .cost_calculator import completion_cost
  File "cost_calculator.py", line 24, in <module>
    from litellm.utils import (
  File "utils.py", line 53, in <module>
    from tokenizers import Tokenizer
  File "__init__.py", line 78, in <module>
    from .tokenizers import (
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

Did you install aider using `pipx` on Replit? Replit's pipx doesn't seem to allow aider to access an important library.

**Comment by paul-gauthier** [comment]
To use aider with pipx on replit, you can run these commands in the replit shell:

```
pip install pipx
pipx run aider-chat ...normal aider args...
```

If you install aider with pipx on replit and try and run it as just `aider` it will crash with a missing `libstdc++.so.6` library.

**Comment by paul-gauthier** [comment]
To use aider with pipx on replit, you can run these commands in the replit shell:

```
pip install pipx
pipx run aider-chat ...normal aider args...
```

If you install aider with pipx on replit and try and run it as just `aider` it will crash
with a missing `libstdc++.so.6` library.
