### ISSUE TITLE
Uncaught ValueError in <frozen ntpath> line 766

### ISSUE THREAD

**Issue by YakovAU** [paul-gauthier/aider#1331]
Aider version: 0.54.12
Python version: 3.11.9
Platform: Windows-10-10.0.22621-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 739, in get_input
    read_only_files = [self.get_rel_fname(fname) for fname in self.abs_read_only_fnames]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 739, in <listcomp>
    read_only_files = [self.get_rel_fname(fname) for fname in self.abs_read_only_fnames]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1627, in get_rel_fname
    return os.path.relpath(fname, self.root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 766, in relpath
ValueError: path is on mount 'E:', start on mount 'C:'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
