### ISSUE TITLE
Uncaught ValueError in symbolic.py line 257

### ISSUE THREAD

**Issue by Qcasares** [paul-gauthier/aider#1336]
Aider version: 0.54.12
Python version: 3.12.5
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1183, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1862, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 99, in commit
    diffs = self.get_diffs(fnames)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 207, in get_diffs
    active_branch = self.repo.active_branch
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 1036, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 411, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 278, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 257, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'HEAD' does not exist

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
