### ISSUE TITLE
Uncaught ValueError in <frozen ntpath> line 766

### ISSUE THREAD

**Issue by LouisDK** [paul-gauthier/aider#1344]
Aider version: 0.54.12
Python version: 3.11.7
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.45.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 738, in get_input
    inchat_files = self.get_inchat_relative_files()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1630, in get_inchat_relative_files
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1630, in <listcomp>
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1627, in get_rel_fname
    return os.path.relpath(fname, self.root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 766, in relpath
ValueError: path is on mount 'C:', start on mount 'D:'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
