### ISSUE TITLE
Uncaught NoConsoleScreenBufferError in win32.py line 219

### ISSUE THREAD

**Issue by dimentox** [paul-gauthier/aider#1345]
Aider version: 0.54.12
Python version: 3.10.14
Platform: Windows-10-10.0.26100-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
  File "base_coder.py", line 742, in get_input
    return self.io.get_input(
  File "io.py", line 337, in get_input
    session = PromptSession(
  File "prompt.py", line 476, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "prompt.py", line 727, in _create_application
    application: Application[_T] = Application(
  File "application.py", line 267, in __init__
    self.output = output or session.output
  File "current.py", line 67, in output
    self._output = create_output()
  File "defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
  File "win32.py", line 115, in __init__
    info = self.get_win32_screen_buffer_info()
  File "win32.py", line 219, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How are you running aider? You don't appear to have a working terminal environment.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
