### ISSUE TITLE
Uncaught BadObject in loose.py line 143

### ISSUE THREAD

**Issue by agrignon** [paul-gauthier/aider#1357]
Aider version: 0.55.0
Python version: 3.11.5
Platform: macOS-15.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "loose.py", line 132, in _map_loose_object
    return file_contents_ro_filepath(db_path, flags=self._fd_open_flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "util.py", line 204, in file_contents_ro_filepath
    fd = os.open(filepath, os.O_RDONLY | getattr(os, 'O_BINARY', 0) | flags)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/agrignon/projects/cadavercaves/.git/objects/10/896c0c70ae287228558b6985e144f7152ee58a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1083, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1021, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 971, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 627, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 592, in get_repo_map
    mentioned_fnames.update(self.get_ident_filename_matches(mentioned_idents))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 571, in get_ident_filename_matches
    for fname in self.get_all_relative_files():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1641, in get_all_relative_files
    files = self.repo.get_tracked_files()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 257, in get_tracked_files
    commit = self.repo.head.commit
             ^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "loose.py", line 154, in info
    m = self._map_loose_object(sha)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "loose.py", line 143, in _map_loose_object
    raise BadObject(sha) from e
gitdb.exc.BadObject: BadObject: b'10896c0c70ae287228558b6985e144f7152ee58a'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
