### ISSUE TITLE
Uncaught IndexError in fun.py line 111

### ISSUE THREAD

**Issue by rogerchucker** [paul-gauthier/aider#1369]
Aider version: 0.55.0
Python version: 3.11.9
Platform: macOS-15.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 551, in main
    if not sanity_check_repo(repo, io):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 302, in sanity_check_repo
    repo.get_tracked_files()
  File "repo.py", line 266, in get_tracked_files
    for blob in commit.tree.traverse():
  File "util.py", line 575, in _traverse
    addToStack(stack, item, branch_first, nd)
  File "util.py", line 535, in addToStack
    lst = self._get_intermediate_items(item)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tree.py", line 207, in _get_intermediate_items
    return tuple(index_object._iter_convert_to_object(index_object._cache))
                                                      ^^^^^^^^^^^^^^^^^^^
  File "util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "tree.py", line 214, in _set_cache_
    self._cache: List[TreeCacheTup] = tree_entries_from_data(ostream.read())
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fun.py", line 111, in tree_entries_from_data
    while data[i] != 0:
          ~~~~^^^
IndexError: index out of range

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
