### ISSUE TITLE
Uncaught RuntimeError in module.py line 1158

### ISSUE THREAD

**Issue by iplayfast** [paul-gauthier/aider#1381]
```
aider --model=ollama/yi-coder:latest
```

Aider version: 0.54.12
Python version: 3.10.12
Platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-40-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 217, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 192, in do_run
    return cmd_method(args)
  File "commands.py", line 875, in cmd_help
    self.help = Help()
  File "help.py", line 111, in __init__
    Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
  File "base.py", line 86, in __init__
    self._model = SentenceTransformer(
  File "SentenceTransformer.py", line 215, in __init__
    self.to(device)
  File "module.py", line 1160, in to
    return self._apply(convert)
  File "module.py", line 810, in _apply
    module._apply(fn)
  File "module.py", line 810, in _apply
    module._apply(fn)
  File "module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "module.py", line 833, in _apply
    param_applied = fn(param)
  File "module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
