### ISSUE TITLE
command /clipboard doesn't work - Uncaught ValueError in <frozen ntpath> 

### ISSUE THREAD

**Issue by dawid-abastr** [paul-gauthier/aider#1394]
Aider version: 0.55.0
Python version: 3.12.4
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.45.2.windows.1

When I tried to use /clipboard command an uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 738, in get_input
    inchat_files = self.get_inchat_relative_files()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1630, in get_inchat_relative_files
    files = [self.get_rel_fname(fname) for fname in self.abs_fnames]
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1627, in get_rel_fname
    return os.path.relpath(fname, self.root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 783, in relpath
ValueError: path is on mount 'C:', start on mount 'D:'

```

**Comment by fry69** [comment]
This does not seem to be easily fixable.

Workaround for now: Install Python, aider and the repositories you work on in the same Drive where your system `TEMP` resides (usually `C:`) if you want to use `/clipboard` on Windows.
