### ISSUE TITLE
Uncaught ModuleNotFoundError in <frozen importlib._bootstrap> line 1004

### ISSUE THREAD

**Issue by Ghost-keys** [paul-gauthier/aider#1399]
Aider version: 0.54.12
Python version: 3.10.12
Platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.9.3-76060903-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 498, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "models.py", line 486, in __init__
    res = self.validate_environment()
  File "models.py", line 660, in validate_environment
    res = litellm.validate_environment(model)
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'litellm'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

**Comment by Ghost-keys** [comment]
Its sorted. I had broken dependencies.
Thanks.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
