### ISSUE TITLE
Uncaught AttributeError in llm.py line 35

### ISSUE THREAD

**Issue by GameMaster007** [paul-gauthier/aider#1401]
Aider version: 0.55.0
Python version: 3.12.5
Platform: Linux-6.10.7-arch1-1-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: No
OS: Linux 6.10.7-arch1-1 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 510, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 486, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 660, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 35, in _load_litellm
    self._lazy_module._logging._disable_debugging()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm' has no attribute '_logging'. Did you mean: 'logging'?

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
