### ISSUE TITLE
Uncaught BadObject in base.py line 197

### ISSUE THREAD

**Issue by chapterv** [paul-gauthier/aider#1404]
Aider version: 0.55.0
Python version: 3.10.6
Platform: Windows-10-10.0.19044-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.41.0.windows.3

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1083, in send_message
    chunks = self.format_messages()
  File "base_coder.py", line 1021, in format_messages
    chunks = self.format_chat_chunks()
  File "base_coder.py", line 971, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
  File "base_coder.py", line 627, in get_repo_messages
    repo_content = self.get_repo_map()
  File "base_coder.py", line 589, in get_repo_map
    mentioned_fnames = self.get_file_mentions(cur_msg_text)
  File "base_coder.py", line 1322, in get_file_mentions
    addable_rel_fnames = self.get_addable_relative_files()
  File "base_coder.py", line 1656, in get_addable_relative_files
    all_files = set(self.get_all_relative_files())
  File "base_coder.py", line 1641, in get_all_relative_files
    files = self.repo.get_tracked_files()
  File "repo.py", line 257, in get_tracked_files
    commit = self.repo.head.commit
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
  File "base.py", line 197, in _db_query
    raise BadObject(sha)
gitdb.exc.BadObject: BadObject: b'bcaed259bab319a80f1430bafbc71eb6b880e19d'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
