### ISSUE TITLE
# Uncaught UnicodeEncodeError in cp1252.py line 19  'charmap' codec can't encode character '\u2588' in position 39: character maps to <undefined>

### ISSUE THREAD

**Issue by p-wegner** [paul-gauthier/aider#1408]
### Issue

When running aider with "--yes --mesage ..." this happens from time to time. The same prompt run in shell with same files in context works fine.

# Uncaught UnicodeEncodeError in cp1252.py line 19

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 667, in main
    coder.run(with_message=args.message)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1194, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1296, in lint_edited
    self.io.tool_warning(res)
  File "io.py", line 545, in tool_warning
    self._tool_message(message, strip, self.tool_warning_color)
  File "io.py", line 538, in _tool_message
    self.console.print(message, **style)
  File "console.py", line 1683, in print
    with self:
  File "console.py", line 864, in __exit__
    self._exit_buffer()
  File "console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "_win32_console.py", line 403, in write_text
    self.write(text)
  File "cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 39: character maps to <undefined>


### Version and model info

Aider version: 0.55.0
Python version: 3.10.0
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1
Model: --sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `--encoding` to set the encoding for aider to use.

**Comment by p-wegner** [comment]
Fixed by setting the env variable PYTHONIOENCODING=utf-8
