### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by iamtahirkhan6** [paul-gauthier/aider#1414]
Aider version: 0.55.0
Python version: 3.10.10
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "chat.py", line 722, in make_sync_call
    response = client.post(
  File "http_handler.py", line 339, in post
    raise e
  File "http_handler.py", line 325, in post
    response.raise_for_status()
  File "_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://europe-west1-aiplatform.googleapis.com/v1/projects/proj-1287/locations/europe-west1/publishers/anthropic/models/claude-3-5-sonnet@20240620:streamRawPredict'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vertex_ai_anthropic.py", line 327, in completion
    return anthropic_chat_completions.completion(
  File "chat.py", line 1112, in completion
    completion_stream = make_sync_call(
  File "chat.py", line 726, in make_sync_call
    raise AnthropicError(
litellm.llms.anthropic.chat.AnthropicError: b'[{\n  "error": {\n    "code": 429,\n    "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",\n    "status": "RESOURCE_EXHAUSTED"\n  }\n}\n]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 2076, in completion
    model_response = vertex_ai_anthropic.completion(
  File "vertex_ai_anthropic.py", line 347, in completion
    raise VertexAIError(status_code=500, message=str(e))
litellm.llms.vertex_ai_and_google_ai_studio.vertex_ai_anthropic.VertexAIError: b'[{\n  "error": {\n    "code": 429,\n    "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",\n    "status": "RESOURCE_EXHAUSTED"\n  }\n}\n]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "base_coder.py", line 1105, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1377, in send
    hash_object, completion = send_completion(
  File "sendchat.py", line 86, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1092, in wrapper
    raise e
  File "utils.py", line 980, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2796, in completion
    raise exception_type(
  File "utils.py", line 8189, in exception_type
    raise e
  File "utils.py", line 7184, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: litellm.RateLimitError: VertexAIException - b'[{\n  "error": {\n    "code": 429,\n    "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",\n    "status": "RESOURCE_EXHAUSTED"\n  }\n}\n]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 196, in do_run
    return cmd_method(args)
  File "commands.py", line 943, in cmd_ask
    return self._generic_chat_command(args, "ask")
  File "commands.py", line 964, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1107, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.AnthropicError,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment]
Please use the LiteLLM version required by aider, newer versions are not supported.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

You may want to read the docs on installing aider with pipx. Particularly if you are trying to use aider on replit.

https://aider.chat/docs/install/pipx.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by paul-gauthier** [comment]
Also, see this doc:

https://aider.chat/docs/troubleshooting/imports.html
