### ISSUE TITLE
Uncaught FileNotFoundError in __init__.py line 379

### ISSUE THREAD

**Issue by savastutumlu95** [paul-gauthier/aider#1416]
Aider version: 0.55.0
Python version: 3.12.6
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1194, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1288, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 97, in lint
    lintres = basic_lint(rel_fname, code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 205, in basic_lint
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
  File "__init__.py", line 132, in __init__
    self.lib = cdll.LoadLibrary(fspath(path_or_ptr))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\Savaş\AppData\Local\Programs\Python\Python312\Lib\site-packages\tree_sitter_languages\languages.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
