### ISSUE TITLE
Uncaught UnicodeEncodeError in history.py line 302

### ISSUE THREAD

**Issue by Rubentxu** [paul-gauthier/aider#1418]
Aider version: 0.55.0
Python version: 3.10.12
Platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-40-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 729, in run
    user_message = self.get_input()
  File "base_coder.py", line 742, in get_input
    return self.io.get_input(
  File "io.py", line 348, in get_input
    line = session.prompt()
  File "prompt.py", line 1035, in prompt
    return self.app.run(
  File "application.py", line 1002, in run
    return asyncio.run(coro)
  File "runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "base_events.py", line 649, in run_until_complete
    return future.result()
  File "application.py", line 886, in run_async
    return await _run_async(f)
  File "application.py", line 677, in _run_async
    self.key_processor.process_keys()
  File "key_processor.py", line 273, in process_keys
    self._process_coroutine.send(key_press)
  File "key_processor.py", line 188, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "key_processor.py", line 323, in _call_handler
    handler.call(event)
  File "key_bindings.py", line 127, in call
    result = self.handler(event)
  File "prompt.py", line 807, in _accept_input
    self.default_buffer.validate_and_handle()
  File "buffer.py", line 1891, in validate_and_handle
    self.append_to_history()
  File "buffer.py", line 1365, in append_to_history
    self.history.append_string(self.text)
  File "history.py", line 76, in append_string
    self.store_string(string)
  File "history.py", line 306, in store_string
    write(f"+{line}\n")
  File "history.py", line 302, in write
    f.write(t.encode("utf-8"))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 1: surrogates not allowed

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `--encoding` to set the encoding for aider to use.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by Rubentxu** [comment]
thanks
