### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by cloudbow** [paul-gauthier/aider#1429]
Aider version: 0.55.0
Python version: 3.11.8
Platform: macOS-12.6-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 21.6.0 (64bit)
Git version: git version 2.37.1 (Apple Git-137.1)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1105, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1394, in send
    raise kbi
  File "base_coder.py", line 1389, in send
    yield from self.show_send_output_stream(completion)
  File "base_coder.py", line 1463, in show_send_output_stream
    for chunk in completion:
  File "utils.py", line 10017, in __next__
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "chat.py", line 1344, in __next__
    chunk = self.response_iterator.__next__()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_models.py", line 863, in iter_lines
    for text in self.iter_text():
  File "_models.py", line 850, in iter_text
    for byte_content in self.iter_bytes():
  File "_models.py", line 831, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "_models.py", line 885, in iter_raw
    for raw_stream_bytes in self.stream:
  File "_client.py", line 127, in __iter__
    for chunk in self._stream:
  File "default.py", line 116, in __iter__
    for part in self._httpcore_stream:
  File "connection_pool.py", line 367, in __iter__
    raise exc from None
  File "connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "http11.py", line 349, in __iter__
    raise exc
  File "http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ssl.py", line 1295, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "ssl.py", line 1168, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1107, in send_message
    except retry_exceptions() as err:
           ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment]
Please use the LiteLLM version aider requires (1.44.7), newer versions are not compatible currently.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

You may want to read the docs on installing aider with pipx. Particularly if you are trying to use aider on replit.

https://aider.chat/docs/install/pipx.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
