### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by matt-schrader** [paul-gauthier/aider#1435]
Aider version: 0.55.0
Python version: 3.12.5
Platform: Linux-6.10.8-arch1-1-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: No
OS: Linux 6.10.8-arch1-1 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1194, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1288, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 97, in lint
    lintres = basic_lint(rel_fname, code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 205, in basic_lint
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

You may want to read the docs on installing aider with pipx. Particularly if you are trying to use aider on replit.

https://aider.chat/docs/install/pipx.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
