### ISSUE TITLE
Uncaught AssertionError in base.py line 114

### ISSUE THREAD

**Issue by FarVision2** [paul-gauthier/aider#1448]
Aider version: 0.55.0
Python version: 3.11.9
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 551, in main
    if not sanity_check_repo(repo, io):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 302, in sanity_check_repo
    repo.get_tracked_files()
  File "repo.py", line 266, in get_tracked_files
    for blob in commit.tree.traverse():
  File "util.py", line 575, in _traverse
    addToStack(stack, item, branch_first, nd)
  File "util.py", line 535, in addToStack
    lst = self._get_intermediate_items(item)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tree.py", line 207, in _get_intermediate_items
    return tuple(index_object._iter_convert_to_object(index_object._cache))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tree.py", line 226, in _iter_convert_to_object
    yield self._map_id_to_type[mode >> 12](self.repo, binsha, mode, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tree.py", line 199, in __init__
    super().__init__(repo, binsha, mode, path)
  File "base.py", line 258, in __init__
    super().__init__(repo, binsha)
  File "base.py", line 114, in __init__
    assert len(binsha) == 20, "Require 20 byte binary sha, got %r, len = %i" % (
           ^^^^^^^^^^^^^^^^^
AssertionError: Require 20 byte binary sha, got b'\x98eR\x9d\xb8\xdcU\xaeUj\x1f\xdb\xe1\x178\xda\xcb\xba\x9d', len = 19

```
(large github fork)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by FarVision2** [comment]
Thank you for that. I'm not sure I remember which repo it was but it was
some agentic generation workflow which created a phenomenal amount of
garbage which had no chance of being committed back up to my fork.
