### ISSUE TITLE
Uncaught RuntimeError in SentenceTransformer.py line 568

### ISSUE THREAD

**Issue by nemilya** [paul-gauthier/aider#1456]
Aider version: 0.55.0
Python version: 3.12.6
Platform: macOS-13.6.9-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 22.6.0 (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 906, in cmd_help
    self.help = Help()
                ^^^^^^
  File "help.py", line 113, in __init__
    index = get_index()
            ^^^^^^^^^^^
  File "help.py", line 98, in get_index
    index = VectorStoreIndex(nodes, show_progress=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 75, in __init__
    super().__init__(
  File "base.py", line 77, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 307, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 278, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "base.py", line 231, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 138, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 335, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 277, in _get_text_embeddings
    return self._embed(texts, prompt_name="text")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 215, in _embed
    emb = self._model.encode(
          ^^^^^^^^^^^^^^^^^^^
  File "SentenceTransformer.py", line 568, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                 ^^^^^^^^^^^
RuntimeError: Numpy is not available

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by nemilya** [comment]
Installed by `brew install aider`.

Error happened when first try for `> /help code` - it asked about install new pip (help), and during `Generating embeddings:` that error happened.

But now, when again start `aider` and type `> /help code` - all works!

Thanks for great tool!
