### ISSUE TITLE
Summarizer unexpectedly failed for all models

### ISSUE THREAD

**Issue by DAMunene** [paul-gauthier/aider#1466]
### Issue

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 682, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1195, in send_message
    self.auto_commit(edited, context="Ran the linter")
  File "base_coder.py", line 1862, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 99, in commit
    diffs = self.get_diffs(fnames)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 221, in get_diffs
    if not self.path_in_repo(fname):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 346, in path_in_repo
    tracked_files = set(self.get_tracked_files())
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 279, in get_tracked_files
    raise UnableToCountRepoFiles(f"Error getting tracked files: {str(e)}")
aider.repo.UnableToCountRepoFiles: Error getting tracked files: BadObject: b'2bc6dda046a7f25d89c75b5252168acee94bac8e'

```

Please consider reporting this bug to help improve aider!
Open a GitHub Issue pre-filled with the above error in your browser? (Y/n) Summarization failed for model openrouter/anthropic/claude-3-haiku-20240307: sys.excepthook is None
Summarization failed for model openrouter/anthropic/claude-3.5-sonnet: sys.excepthook is None
summarizer unexpectedly failed for all models

### Version and model info

_No response_

**Comment by DAMunene** [comment]
Everything looks great!! Thank you for developing such an awesome product

Regards,
