### ISSUE TITLE
Uncaught ValueError in utils.py line 143

### ISSUE THREAD

**Issue by Procureallyai** [paul-gauthier/aider#1474]
Aider version: 0.56.0
Python version: 3.11.4
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1223, in send_message
    shared_output = self.run_shell_commands()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1945, in run_shell_commands
    output = self.handle_shell_commands(command, group)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1971, in handle_shell_commands
    exit_status, output = run_cmd(command, error_print=self.io.tool_error)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 13, in run_cmd
    return run_cmd_pexpect(command, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "run_cmd.py", line 87, in run_cmd_pexpect
    child.interact(output_filter=output_callback)
  File "pty_spawn.py", line 793, in interact
    self.__interact_copy(escape_character, input_filter, output_filter)
  File "pty_spawn.py", line 822, in __interact_copy
    r, w, e = select_ignore_interrupts(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 143, in select_ignore_interrupts
    return select.select(iwtd, owtd, ewtd, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()

```

**Comment by fry69** [comment]
Thank you for filing this bug report.

How did you install aider?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch
```

If you have a chance to try it, let me know if it works better for you.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
