### ISSUE TITLE
Uncaught InternalServerError in utils.py line 6935

### ISSUE THREAD

**Issue by cswelker** [paul-gauthier/aider#1478]
Aider version: 0.55.0
Python version: 3.12.4
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 1512, in completion
    response = anthropic_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anthropic.py", line 1096, in completion
    raise AnthropicError(
litellm.llms.anthropic.AnthropicError: {"type":"error","error":{"type":"api_error","message":"Internal server error"}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    return
        ^^^
  File "base_coder.py", line 730, in run
    return self.partial_response_content
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 773, in run_one
    else:
        ^^
  File "base_coder.py", line 1183, in send_message
    content = args.get("explanation") or ""
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1863, in auto_commit
    return json.loads(data + '"}]}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 101, in commit
    else:
          
  File "repo.py", line 186, in get_commit_message
    continue
             
  File "sendchat.py", line 44, in wrapper
    return decorated_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 106, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 86, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 1078, in wrapper
    raise e
  File "utils.py", line 966, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 2766, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "utils.py", line 8438, in exception_type
    raise e
  File "utils.py", line 6935, in exception_type
    raise litellm.InternalServerError(
litellm.exceptions.InternalServerError: litellm.InternalServerError: AnthropicException - {"type":"error","error":{"type":"api_error","message":"Internal server error"}}. Handle with `litellm.InternalServerError`.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. That error just means that Anthropic's servers were down.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
