### ISSUE TITLE
Uncaught OSError in util.py line 125

### ISSUE THREAD

**Issue by tn-py** [paul-gauthier/aider#1485]
Aider version: 0.55.0
Python version: 3.12.0
Platform: Windows-11-10.0.26120-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.40.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "mman.py", line 569, in _obtain_region
    r = self.MapRegionCls(a.path_or_fd(), mid.ofs, mid.size, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "util.py", line 125, in __init__
    actual_size = min(os.fstat(fd).st_size - sizeofs, corrected_size)
                      ^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 551, in main
    if not sanity_check_repo(repo, io):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 302, in sanity_check_repo
    repo.get_tracked_files()
  File "repo.py", line 257, in get_tracked_files
    commit = self.repo.head.commit
             ^^^^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
            ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 210, in info
    return self._db_query(sha).info(sha)
           ^^^^^^^^^^^^^^^^^^^
  File "base.py", line 193, in _db_query
    if db.has_object(sha):
       ^^^^^^^^^^^^^^^^^^
  File "pack.py", line 91, in has_object
    self._pack_info(sha)
  File "pack.py", line 70, in _pack_info
    self._sort_entities()
  File "pack.py", line 58, in _sort_entities
    self._entities.sort(key=lambda l: l[0], reverse=True)
    ^^^^^^^^^^^^^^
  File "util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "pack.py", line 54, in _set_cache_
    self.update_cache(force=True)
  File "pack.py", line 157, in update_cache
    self._entities.append([entity.pack().size(), entity, entity.index().sha_to_index])
                           ^^^^^^^^^^^^^^^^^^^^
  File "pack.py", line 572, in size
    return self._size
           ^^^^^^^^^^
  File "util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "pack.py", line 534, in _set_cache_
    self._cursor = mman.make_cursor(self._packpath).use_region()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mman.py", line 133, in use_region
    self._region = man._obtain_region(self._rlist, offset, size, flags, False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mman.py", line 581, in _obtain_region
    return self._obtain_region(a, offset, size, flags, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mman.py", line 569, in _obtain_region
    r = self.MapRegionCls(a.path_or_fd(), mid.ofs, mid.size, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "util.py", line 125, in __init__
    actual_size = min(os.fstat(fd).st_size - sizeofs, corrected_size)
                      ^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
