### ISSUE TITLE
 Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by rempel1234** [paul-gauthier/aider#1495]
### Issue

sh-5.2$ python3 -m aider --model ollama/llama3:70b --browser
CONTROL-C to exit...

# Uncaught TypeError in main.py line 172

Aider version: <module 'aider.__version__' from '/home/ssm-user/.local/lib/python3.9/site-packages/aider/__version__.py'>
Python version: 3.9.16
Platform: Linux-6.1.106-116.188.amzn2023.x86_64-x86_64-with-glibc2.34
Python implementation: CPython
Virtual environment: No
OS: Linux 6.1.106-116.188.amzn2023.x86_64 (64bit)
Git version: git version 2.40.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 422, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
TypeError: argument of type 'module' is not iterable

```

Please consider reporting this bug to help improve aider!
Open a GitHub Issue pre-filled with the above error in your browser? (Y/n) ^CError in sys.excepthook:
Traceback (most recent call last):
  File "/home/ssm-user/.local/lib/python3.9/site-packages/aider/report.py", line 151, in exception_handler
    report_github_issue(issue_text, title=title)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/aider/report.py", line 71, in report_github_issue
    confirmation = input(prompt).strip().lower()
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/aider/__main__.py", line 4, in <module>
    main()
  File "/home/ssm-user/.local/lib/python3.9/site-packages/aider/main.py", line 422, in main
    launch_gui(argv)
  File "/home/ssm-user/.local/lib/python3.9/site-packages/aider/main.py", line 172, in launch_gui
    if "-dev" in __version__:

### Version and model info

sh-5.2$ python3 -m aider --model ollama/llama3:70b --browser

**Comment by rempel1234** [comment]
Reinstalled using pipx, and it resolved the issue. Would be nice if the directions mentioned switching to pipx if there's an error... This does look like a really amazing tool!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
