### ISSUE TITLE
Uncaught AttributeError in pathlib.py line 1094

### ISSUE THREAD

**Issue by kornhill** [paul-gauthier/aider#1498]
Aider version: 0.56.0
Python version: 3.12.4
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 772, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 761, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 639, in cmd_add
    matched_files = self.glob_filtered_to_repo(word)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 591, in glob_filtered_to_repo
    raw_matched_files = list(Path(self.coder.root).glob(pattern))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1094, in glob
    for p in selector.select_from(self):
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_TerminatingSelector' object has no attribute 'select_from'. Did you mean: '_select_from'?

```

**Comment by fry69** [comment]
Thank you for filing this issue.

How did you install aider?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
