### ISSUE TITLE
Uncaught UnicodeDecodeError in <frozen codecs> line 322

### ISSUE THREAD

**Issue by EthanVV** [paul-gauthier/aider#1513]
Aider version: 0.56.0
Python version: 3.12.5
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.42.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 363, in main
    loaded_dotenvs = load_dotenv_files(git_root, args.env_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 279, in load_dotenv_files
    load_dotenv(fname, override=True)
  File "main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ^^^^^^^^^^^
  File "main.py", line 76, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 238, in resolve_variables
    for (name, value) in values:
                         ^^^^^^
  File "main.py", line 84, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 26, in with_warn_for_invalid_lines
    for mapping in mappings:
                   ^^^^^^^^
  File "parser.py", line 173, in parse_stream
    reader = Reader(stream)
             ^^^^^^^^^^^^^^
  File "parser.py", line 64, in __init__
    self.string = stream.read()
                  ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
