### ISSUE TITLE
Uncaught UnicodeDecodeError in utils.py line 241

### ISSUE THREAD

**Issue by cute-slime** [paul-gauthier/aider#1514]
Aider version: 0.56.1.dev
Python version: 3.11.9
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.1.windows.1

This error occurred while attempting to use the /web command after proceeding with the installation suggested by Aider:

```
For the best web scraping, install Playwright:

python.exe -m pip install aider-chat[playwright]
C:\Users\jongm\.pyenv\pyenv-win\versions\3.11.9\python.exe -m playwright install --with-deps chromium

See https://aider.chat/docs/install/optional.html#enable-playwright for more info.

Install playwright? (Y)es/(N)o [Yes]:

Installing: python.exe -m pip install aider-chat[playwright]
                
Installation complete.


Installing: C:\Users\jongm\.pyenv\pyenv-win\versions\3.11.9\python.exe -m playwright install --with-deps chromium
Installing... ⠇
# Uncaught UnicodeDecodeError in utils.py line 241
```

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 722, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 759, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 748, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 148, in cmd_web
    res = install_playwright(self.io)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scrape.py", line 61, in install_playwright
    success, output = utils.run_install(chromium_cmd)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 241, in run_install
    char = process.stdout.read(1)
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1: illegal multibyte sequence

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by cute-slime** [comment]
The issue has been resolved, and everything is functioning normally.
Thank you.
