### ISSUE TITLE
Uncaught ValueError in pathlib.py line 730

### ISSUE THREAD

**Issue by bitdeep** [paul-gauthier/aider#1524]
Aider version: 0.56.1.dev111+ge6037140
Python version: 3.11.9
Platform: Windows-10-10.0.22635-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 466, in main
    return main(argv, input, output, right_repo_root, return_coder=return_coder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 564, in main
    if not sanity_check_repo(repo, io):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 308, in sanity_check_repo
    repo.get_tracked_files()
  File "repo.py", line 289, in get_tracked_files
    res = [fname for fname in files if not self.ignored_file(fname)]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 289, in <listcomp>
    res = [fname for fname in files if not self.ignored_file(fname)]
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 332, in ignored_file
    result = self.ignored_file_raw(fname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 339, in ignored_file_raw
    cwd_path = Path.cwd().resolve().relative_to(Path(self.root).resolve())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'C:\\dev\\squid-certbot' is not in the subpath of 'C:\\dev\\squid-certbot\\docker-compose-squid' OR one path is relative and the other is absolute.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
