### ISSUE TITLE
Uncaught NoConsoleScreenBufferError in win32.py line 219

### ISSUE THREAD

**Issue by tianweichao** [paul-gauthier/aider#1546]
Aider version: 0.56.0
Python version: 3.9.19
Platform: Windows-10-10.0.22621-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.40.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 534, in main
    if not io.confirm_ask("Proceed anyway?"):
  File "io.py", line 469, in confirm_ask
    res = prompt(
  File "prompt.py", line 1423, in prompt
    session: PromptSession[str] = PromptSession(history=history)
  File "prompt.py", line 476, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "prompt.py", line 727, in _create_application
    application: Application[_T] = Application(
  File "application.py", line 267, in __init__
    self.output = output or session.output
  File "current.py", line 67, in output
    self._output = create_output()
  File "defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
  File "win32.py", line 115, in __init__
    info = self.get_win32_screen_buffer_info()
  File "win32.py", line 219, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from GitHub:
```
aider --install-main-branch

# or.

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
If you have a chance to try it, please report if it works better for you.
