### ISSUE TITLE
Uncaught OSError in pathlib.py line 1175

### ISSUE THREAD

**Issue by krishnas1998** [paul-gauthier/aider#1577]
Aider version: 0.56.0
Python version: 3.10.8
Platform: macOS-14.4-arm64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.4.0 (64bit)
Git version: git version 2.33.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.aider/caches'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.aider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 518, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "models.py", line 484, in __init__
    self.info = self.get_model_info(model)
  File "models.py", line 504, in get_model_info
    return get_model_info(model)
  File "models.py", line 441, in get_model_info
    cache_dir.mkdir(parents=True, exist_ok=True)
  File "pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/root'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
