### ISSUE TITLE
Uncaught TypeError in __main__.py line 4

### ISSUE THREAD

**Issue by amitj-endian** [paul-gauthier/aider#1588]
Aider version: 0.54.7-dev

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 640, in main
    coder.run()
  File "base_coder.py", line 727, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 764, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 753, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 204, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 179, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 887, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 908, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 721, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 770, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1131, in send_message
    self.show_exhausted_error()
  File "base_coder.py", line 1208, in show_exhausted_error
    input_tokens = self.main_model.token_count(self.format_messages())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 590, in token_count
    msgs = json.dumps(messages)
           ^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ChatChunks is not JSON serializable

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from GitHub:
```
aider --install-main-branch

# or.

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
If you have a chance to try it, please report if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
