### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by joaoguilhermeS** [paul-gauthier/aider#1598]
Aider version: 0.56.0
Python version: 3.10.12
Platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.9.3-76060903-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1213, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1307, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
  File "linter.py", line 100, in lint
    lintres = cmd(fname, rel_fname, code)
  File "linter.py", line 117, in py_lint
    basic_res = basic_lint(rel_fname, code)
  File "linter.py", line 213, in basic_lint
    parser = get_parser(lang)
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The error seems to come from installing aider via a system package, these often do not get the dependencies right.

Please install aider separately from other Python modules, e.g. via `pipx` or `venv`.

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

Duplicate #1604
