### ISSUE TITLE
Feature Request: Support git worktrees

### ISSUE THREAD

**Issue by thenbe** [paul-gauthier/aider#16]
I think git worktrees offer a great workflow for a tool like aider. Worktrees reduce the friction that naturally stems from having an external tool commit automatically, resulting in a smoother experience.

 In case you're not familiar: [man git-worktree](https://git-scm.com/docs/git-worktree).

A sample workflow would look something like this:

```bash
mkdir mydir && cd mydir

# create a dummy repo
mkdir myrepo && cd myrepo && touch README.md && git init && git add -A && git commit -m "Initial commit"

# aider works here
aider -v

# create a worktree to fix some bug. CD into it.
mkdir ../worktrees
git worktree add ../worktrees/bugfix
cd ../worktrees/bugfix

# use aider to help fix the bug (This will result in the error shown below)
aider -v
```

```
Traceback (most recent call last):
  File "/home/nbe/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/nbe/projects/playground/python-exp/venv/lib/python3.10/site-packages/aider/main.py", line 216, in main
    coder = Coder(
  File "/home/nbe/projects/playground/python-exp/venv/lib/python3.10/site-packages/aider/coder.py", line 85, in __init__
    self.set_repo(fnames)
  File "/home/nbe/projects/playground/python-exp/venv/lib/python3.10/site-packages/aider/coder.py", line 149, in set_repo
    repo = git.Repo(repo_paths.pop(), odbt=git.GitDB)
  File "/home/nbe/projects/playground/python-exp/venv/lib/python3.10/site-packages/git/repo/base.py", line 265, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/nbe/mydir/myrepo/.git/worktrees/bugfix
```

**Comment by paul-gauthier** [comment]
Thanks for reporting this issue. I just pushed a fix. Let me know if it works for you.

**Comment by thenbe** [comment]
Works great. Thank you!
