### ISSUE TITLE
Uncaught TypeError in typing.py line 1422

### ISSUE THREAD

**Issue by justintrotta** [paul-gauthier/aider#1625]
Aider version: 0.56.0
Python version: 3.10.0rc2
Platform: Windows-10-10.0.26120-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.43.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1202, in send_message
    saved_message = self.auto_commit(edited)
  File "base_coder.py", line 1885, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
  File "repo.py", line 141, in commit
    commit_hash = self.get_head_commit_sha(short=True)
  File "repo.py", line 395, in get_head_commit_sha
    commit = self.get_head_commit()
  File "repo.py", line 390, in get_head_commit
    return self.repo.head.commit
  File "symbolic.py", line 297, in _get_commit
    obj = self._get_object()
  File "symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "base.py", line 150, in new_from_sha
    inst = get_object_type_by_name(oinfo.type)(repo, oinfo.binsha)
  File "commit.py", line 172, in __init__
    super().__init__(repo, binsha)
  File "base.py", line 111, in __init__
    super().__init__()
  File "typing.py", line 1422, in _no_init_or_replace_init
    cls.__init__(self, *args, **kwargs)
TypeError: Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'

```

**Comment by justintrotta** [comment]
this was resolved by deleting .git
