### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by jjphung** [paul-gauthier/aider#1659]
Aider version: 0.56.0
Python version: 3.11.5
Platform: macOS-14.4.1-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.4.0 (64bit)
Git version: git version 2.38.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1124, in send_message
    continue
  File "base_coder.py", line 1408, in send
    self.keyboard_interrupt()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1490, in show_send_output_stream
    pass
aider.coders.base_coder.FinishReasonLength

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    return 1
  File "base_coder.py", line 735, in run
    return self.io.get_input(
                ^^^^^^^^^^^^^^
  File "base_coder.py", line 772, in run_one
    self.io.tool_warning(f"Only {self.max_reflections} reflections allowed, stopping.")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 761, in preproc_user_input
    else:
          
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 947, in cmd_code
  File "commands.py", line 964, in _generic_chat_command
  File "base_coder.py", line 729, in run
  File "base_coder.py", line 778, in run_one
    def check_for_urls(self, inp):
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1126, in send_message
    interrupted = True
       ^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is in the latest version (`0.57.1`), please update aider with
```
aider --upgrade
```
