### ISSUE TITLE
Uncaught KeyError in models.py line 788 - vertexAI gemini-1.5-pro-latest

### ISSUE THREAD

**Issue by bungrudi** [paul-gauthier/aider#1661]
Aider version: 0.56.0
Python version: 3.12.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 529, in main
  File "models.py", line 735, in sanity_check_models
    def get_image_size(self, fname):
                     ^^^^^^^^^^^^^^^^
  File "models.py", line 768, in sanity_check_model
    return res
               
  File "models.py", line 788, in fuzzy_match_models
KeyError: 'litellm_provider'

```

**Comment by bungrudi** [comment]
sorry wrong model name.. was not listed in `--list-models vertex`
