### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by samrat-m** [paul-gauthier/aider#1668]
Aider version: 0.56.0
Python version: 3.12.3
Platform: macOS-14.4.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.4.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "utils.py", line 10022, in __next__
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "chat.py", line 1365, in __next__
    return self.chunk_parser(chunk=data_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "chat.py", line 1325, in chunk_parser
    raise AnthropicError(
litellm.llms.anthropic.chat.AnthropicError: Overloaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "base_coder.py", line 1124, in send_message
    continue
  File "base_coder.py", line 1408, in send
    self.keyboard_interrupt()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1482, in show_send_output_stream
    func = chunk.choices[0].delta.function_call
  File "utils.py", line 10110, in __next__
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "utils.py", line 8194, in exception_type
    raise e
  File "utils.py", line 6680, in exception_type
    raise litellm.InternalServerError(
litellm.exceptions.InternalServerError: litellm.InternalServerError: AnthropicException - Overloaded. Handle with `litellm.InternalServerError`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    return 1
  File "base_coder.py", line 735, in run
    return self.io.get_input(
                ^^^^^^^^^^^^^^
  File "base_coder.py", line 778, in run_one
    def check_for_urls(self, inp):
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1126, in send_message
    interrupted = True
       ^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is in the latest version (`0.57.1`), please update aider with
```
aider --upgrade
```
