### ISSUE TITLE
Uncaught UnicodeEncodeError in _win32_console.py line 403

### ISSUE THREAD

**Issue by fenix30660** [paul-gauthier/aider#1670]
Aider version: 0.57.1
Python version: 3.10.10
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 535, in main
    problem = models.sanity_check_models(io, main_model)
  File "models.py", line 840, in sanity_check_models
    problem_strong = sanity_check_model(io, main_model)
  File "models.py", line 855, in sanity_check_model
    io.tool_output(f"- {key}: {status}")
  File "io.py", line 587, in tool_output
    self.console.print(*messages, style=style)
  File "console.py", line 1683, in print
    with self:
  File "console.py", line 864, in __exit__
    self._exit_buffer()
  File "console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2717' in position 18: illegal multibyte sequence

```

**Comment by fry69** [comment]
Thank you for filing this issue.

I assume you are using a Windows terminal, which aider didn't like much, so it decided to use the simple (`--no-pretty`) interface as a fallback. And I further assume that this "dumb" terminal  cannot handle Chinese GBK encoded Unicode characters.

Is that correct so far?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
