### ISSUE TITLE
Uncaught ModuleNotFoundError in pagerank_alg.py line 453

### ISSUE THREAD

**Issue by sebbacon** [paul-gauthier/aider#1673]
Aider version: 0.57.1
Python version: 3.12.4
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
  File "main.py", line 709, in main
  File "base_coder.py", line 723, in run
  File "base_coder.py", line 766, in run_one
  File "base_coder.py", line 1097, in send_message
  File "base_coder.py", line 1035, in format_messages
  File "base_coder.py", line 985, in format_chat_chunks
  File "base_coder.py", line 620, in get_repo_messages
  File "base_coder.py", line 592, in get_repo_map
  File "repomap.py", line 127, in get_repo_map
  File "repomap.py", line 478, in get_ranked_tags_map
  File "repomap.py", line 509, in get_ranked_tags_map_uncached
  File "repomap.py", line 399, in get_ranked_tags
  File "backends.py", line 412, in __call__
  File "pagerank_alg.py", line 110, in pagerank
  File "pagerank_alg.py", line 453, in _pagerank_scipy
ModuleNotFoundError: No module named 'scipy'

```

**Comment by sebbacon** [comment]
PBKAC

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.

**Comment by paul-gauthier** [comment]
How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html
