### ISSUE TITLE
Uncaught ImportError in utils.py line 9

### ISSUE THREAD

**Issue by iamgrewal** [paul-gauthier/aider#1690]
Aider version: 0.57.1
Python version: 3.10.0
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 524, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "models.py", line 592, in __init__
    res = self.validate_environment()
  File "models.py", line 766, in validate_environment
    res = litellm.validate_environment(model)
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "caching.py", line 28, in <module>
    from litellm.types.utils import all_litellm_params
  File "utils.py", line 9, in <module>
    from openai.types.completion_usage import CompletionTokensDetails, CompletionUsage
ImportError: cannot import name 'CompletionTokensDetails' from 'openai.types.completion_usage' (/opt/anaconda3/envs/dspy-rag/lib/python3.10/site-packages/openai/types/completion_usage.py)

```

**Comment by fry69** [comment]
Thank you for filing this issue.

At first glance this looks like you installed aider in an environment with many other Python modules and aider's dependencies got mixed up. Can you please try to install aider in a separate Python environment? Either with anaconda (which you seem to be using) or `venv` or even `pipx`?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by paul-gauthier** [comment]
It is recommended to install via pip or pipx, not brew. 

Please read the linked url above.
