### ISSUE TITLE
Uncaught UnicodeEncodeError in cp1252.py line 19

### ISSUE THREAD

**Issue by madanjayaprakasam** [paul-gauthier/aider#1693]
Aider version: 0.57.1
Python version: 3.12.6
Platform: Windows-11-10.0.22635-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.39.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "main.py", line 792, in <module>
    status = main()
             ^^^^^^
  File "main.py", line 535, in main
    problem = models.sanity_check_models(io, main_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 840, in sanity_check_models
    problem_strong = sanity_check_model(io, main_model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 855, in sanity_check_model
    io.tool_output(f"- {key}: {status}")
  File "io.py", line 587, in tool_output
    self.console.print(*messages, style=style)
  File "console.py", line 1683, in print
    with self:
  File "console.py", line 864, in __exit__
    self._exit_buffer()
  File "console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "_win32_console.py", line 403, in write_text
    self.write(text)
  File "cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2717' in position 18: character maps to <undefined>

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from GitHub:
```
aider --install-main-branch

# or

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
If you have a chance to try it, please report if it works better for you.
