### ISSUE TITLE
Uncaught ImportError in utils.py line 9

### ISSUE THREAD

**Issue by worketome** [paul-gauthier/aider#1705]
Aider version: 0.56.0
Python version: 3.11.0
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 478, in main
    models.print_matching_models(io, args.list_models)
  File "models.py", line 820, in print_matching_models
    matches = fuzzy_match_models(search)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 784, in fuzzy_match_models
    for model, attrs in litellm.model_cost.items():
                        ^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "caching.py", line 28, in <module>
    from litellm.types.utils import all_litellm_params
  File "utils.py", line 9, in <module>
    from openai.types.completion_usage import CompletionTokensDetails, CompletionUsage
ImportError: cannot import name 'CompletionTokensDetails' from 'openai.types.completion_usage' (C:\Users\worke\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\types\completion_usage.py)

```

**Comment by fry69** [comment]
Thank you for filing this issue.

At first glance this looks like you installed aider in an environment with many other Python modules and aider's dependencies got mixed up. Can you please try to install aider in a separate Python environment? Either with `venv` or `pipx`?

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
