### ISSUE TITLE
Uncaught OSError in __init__.py line 379

### ISSUE THREAD

**Issue by DMTarmey** [paul-gauthier/aider#1716]
Aider version: 0.57.1
Python version: 3.12.6
Platform: Linux-6.11.0-5-cachyos-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.11.0-5-cachyos (64bit)
Git version: git version 2.46.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
  File "main.py", line 709, in main
  File "base_coder.py", line 723, in run
  File "base_coder.py", line 766, in run_one
  File "base_coder.py", line 1097, in send_message
  File "base_coder.py", line 1035, in format_messages
  File "base_coder.py", line 985, in format_chat_chunks
  File "base_coder.py", line 620, in get_repo_messages
  File "base_coder.py", line 592, in get_repo_map
  File "repomap.py", line 127, in get_repo_map
  File "repomap.py", line 478, in get_ranked_tags_map
  File "repomap.py", line 543, in get_ranked_tags_map_uncached
  File "repomap.py", line 626, in to_tree
  File "repomap.py", line 582, in render_tree
  File "grep_ast.py", line 47, in __init__
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
  File "__init__.py", line 132, in __init__
  File "__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/dmtarmey/AiderProjects/aider-env/lib/python3.12/site-packages/tree_sitter_languages/languages.so: cannot open shared object file: No such file or directory

```

**Comment by fry69** [comment]
Thank you for filing this issue.

This looks like an installation problem, please try to reinstall via official methods, see here ->

https://aider.chat/docs/install/install.html

This document may also be helpful -> https://aider.chat/docs/troubleshooting/imports.html
