### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 21

### ISSUE THREAD

**Issue by aitorroma** [paul-gauthier/aider#1721]
Aider version: 0.57.1
Python version: 3.10.12
Platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.9.3-76060903-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1115, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1392, in send
    hash_object, completion = send_completion(
  File "sendchat.py", line 87, in send_completion
    res = litellm.completion(**kwargs)
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 8, in <module>
    from litellm.llms.custom_httpx.http_handler import AsyncHTTPHandler, HTTPHandler
  File "http_handler.py", line 7, in <module>
    from httpx import USE_CLIENT_DEFAULT
ImportError: cannot import name 'USE_CLIENT_DEFAULT' from 'httpx' (/home/tuxed/.local/lib/python3.10/site-packages/httpx/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1117, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 21, in retry_exceptions
    httpx.ConnectError,
AttributeError: module 'httpx' has no attribute 'ConnectError'

```

**Comment by aitorroma** [comment]
Solved!

rm -Rf /home/tuxed/.local/lib/python3.10/site-packages/httpx/
python3 -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
