### ISSUE TITLE
'message': 'Incorrect API key provided:'

### ISSUE THREAD

**Issue by akamalov** [paul-gauthier/aider#1731]
### Issue

* Environment*
`Windows 11`
`conda 23.7.2`
`Python 3.11.9`
`aider 0.57.1`

1. Generated new key at `https://platform.openai.com/api-keys`. 
2. Export env.variable:

`(aider) D:\SD> set  OPENAI_API_KEY="sk-projXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...."`

Ran aider-chat  as:
```
(aider) D:\SD>aider --model openai/gpt-4o-mini
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.57.1
Model: openai/gpt-4o-mini with whole edit format
Git repo: .git with 0 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
───────────────────────────────────────────────────────────────────────────────

```
Ran a prompt:

```
> Make a minesweeper game using html,css,js


Unexpected error: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided:
"sk-proj********************************************************************************************************************************************************
**WQA". You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Traceback (most recent call last):
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 907, in completion
    raise e
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 784, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 1045, in streaming
    headers, response = self.make_sync_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 683, in make_sync_openai_chat_completion_request
    raise e
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 672, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\_legacy_response.py", line 353, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\resources\chat\completions.py", line 704, in create
    return self._post(
           ^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\_base_client.py", line 1268, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\_base_client.py", line 945, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\openai\_base_client.py", line 1049, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided:
"sk-proj********************************************************************************************************************************************************
**WQA". You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\main.py", line 1419, in completion
    raise e
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\main.py", line 1392, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 914, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 401 - {'error': {'message': 'Incorrect API key provided:
"sk-proj********************************************************************************************************************************************************
**WQA". You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\aider\Lib\site-packages\aider\coders\base_coder.py", line 1115, in send_message
    yield from self.send(messages, functions=self.functions)
  File "D:\anaconda3\envs\aider\Lib\site-packages\aider\coders\base_coder.py", line 1392, in send
    hash_object, completion = send_completion(
                              ^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\aider\sendchat.py", line 87, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 1086, in wrapper
    raise e
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 974, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\main.py", line 2847, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 8194, in exception_type
    raise e
  File "D:\anaconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 6525, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect
API key provided:
"sk-proj********************************************************************************************************************************************************
**WQA". You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}


────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Remove the `"` when setting the API key, e.g.
```
(aider) D:\SD> set  OPENAI_API_KEY=sk-projXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....
```
instead of
```
(aider) D:\SD> set  OPENAI_API_KEY="sk-projXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...."
```

**Comment by akamalov** [comment]
Thank you very much indeed. That solved the problem!!

**Comment by akamalov** [comment]
Thanks to @fry69 !!!!
