### ISSUE TITLE
Uncaught RuntimeError in __init__.py line 467

### ISSUE THREAD

**Issue by etnt** [paul-gauthier/aider#1751]
Aider version: 0.57.1
Python version: 3.12.5
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.40.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 760, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 749, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 942, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 963, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 717, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 760, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 752, in preproc_user_input
    self.check_for_urls(inp)
  File "base_coder.py", line 787, in check_for_urls
    inp += self.commands.cmd_web(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 156, in cmd_web
    content = self.scraper.scrape(url) or ""
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "scrape.py", line 110, in scrape
    content = self.html_to_markdown(content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scrape.py", line 228, in html_to_markdown
    md = pypandoc.convert_text(page_source, "markdown", format="html")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 92, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 467, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "64" during conversion: TagOpen "img" []


```

The action I did in the aider shell was:
```
https://github.com/stanfordnlp/pyreft                                                                                                                                                                      
Add URL to the chat? (Y)es/(N)o [Yes]:                                                                                                                                                                     
Scraping https://github.com/stanfordnlp/pyreft...  
```

**Comment by fry69** [comment]
Thank you for filing this issue.

aider's internal scraper is very limited, if it fails try using `/web` and let it install playwright/chromium.

These documents may be helpful:
- https://aider.chat/docs/usage/images-urls.html#web-pages
- https://aider.chat/docs/install/optional.html#enable-playwright

**Comment by etnt** [comment]
Thanks for the reply. Feel free to close the issue if you'd like :-)

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
