### ISSUE TITLE
OpenRouter model name

### ISSUE THREAD

**Issue by Yona544** [paul-gauthier/aider#1824]
a. Why not check for my model available when setting modal, and not crash 
b.  why not use my openrouter API key i Have in the .env file 

Aider version: 0.58.0
Python version: 3.11.4
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

Aider v0.58.0
Main model: o1-preview with architect edit format
Editor model: gpt-4o with editor-diff edit format
Weak model: gpt-4o-mini

Unexpected error: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model
`o1-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code':
'model_not_found'}}
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 907, in completion
    raise e
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 825, in completion
    self.make_sync_openai_chat_completion_request(
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 683, in
make_sync_openai_chat_completion_request
    raise e
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 672, in
make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\_legacy_response.py", line 353, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\resources\chat\completions.py", line 704, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\_base_client.py", line 1268, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\_base_client.py", line 945, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\openai\_base_client.py", line 1049, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `o1-preview` does not exist or you do not have
access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\litellm\main.py", line 1419, in completion
    raise e
  File "C:\Python311\Lib\site-packages\litellm\main.py", line 1372, in completion
    response = openai_o1_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\chat\o1_handler.py", line 58, in completion
    response = super().completion(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 914, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 404 - {'error': {'message': 'The model `o1-preview` does not exist
or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\aider\coders\base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "C:\Python311\Lib\site-packages\aider\coders\base_coder.py", line 1410, in send
    hash_object, completion = send_completion(
                              ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\aider\sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 1086, in wrapper
    raise e
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 974, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\main.py", line 2847, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 8194, in exception_type
    raise e
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 6432, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The
model `o1-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None,
'code': 'model_not_found'}}

**Comment by fry69** [comment]
Thank you for filing this issue.

Looks like you are talking to the OpenAI API, which rejects you, not the OpenRouter API. Probably because you did not specify the correct model name.

To use OpenRouter models start with `openrouter/`, see here -> https://aider.chat/docs/llms/openrouter.html

**Comment by Yona544** [comment]
Thanks @fry69  
To use -architect with openrouter/openai/o1-preview and deepseek as the editor how would i call it at the command line and is there any way i can set it in the .env file?

**Comment by fry69** [comment]
I guess this should work `--model openrouter/openai/o1-preview --architect --editor-model deepseek/deepseek-chat` (not tested)

I'd recommend to only use `.env` files for authentication/API keys and put such configuration in a `.aider.conf.yml` file, see here -> https://aider.chat/docs/config/aider_conf.html

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.

**Comment by Yona544** [comment]
Running **aider --model openrouter/openai/o1-preview --architect --editor-model openrouter/deepseek/deepseek-coder** 
or
**aider --model openrouter/openai/o1-preview --architect --editor-model openrouter/deepseek/deepseek-chat**
After asking anything I'm getting error **BadRequestError: litellm.BadRequestError: OpenrouterException -**


Aider version: 0.58.0
Python version: 3.11.4
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

Aider v0.58.0
Main model: openrouter/openai/o1-preview with architect edit format
Editor model: openrouter/deepseek/deepseek-coder with editor-diff edit format

**Comment by fry69** [comment]
Use `openrouter/deepseek/deepseek-chat` instead of `openrouter/deepseek/deepseek-coder`, that does not exist anymore.

**Comment by Yona544** [comment]
As you can see in the above reply I tried them both 
and still got the same error with no explanation 


Aider v0.58.0
Main model: openrouter/openai/o1-preview with architect edit format
Editor model: openrouter/deepseek/deepseek-chat with editor-diff edit format
