### ISSUE TITLE
Uncaught ValueError in base_coder.py line 156

### ISSUE THREAD

**Issue by calmren** [paul-gauthier/aider#1835]
Aider version: 0.58.0
Python version: 3.12.4
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.46.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1201, in send_message
    self.reply_completed()
  File "architect_coder.py", line 32, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 156, in create
    raise ValueError(f"Unknown edit format {edit_format}")
ValueError: Unknown edit format whole-file

```

**Comment by fry69** [comment]
Thank you for filing this issue.

This error should be handled more gracefully. The allowed valued for edit formats are `whole` and `diff` (there are more, but those are experimental,  avoid them for now).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you cause this error? If you run aider with a bad edit format, it should print a nice error:

```
$ aider --edit-format nonono
─────────────────────────────────────────────────────────────────────────────────────────────────────────
Unknown edit format nonono
```

**Comment by calmren** [comment]
Hi,
I was in architecture mode, setting up new project repo using win
powershell with my usual yaml config but forgot I had testing instructions.
Aider was trying to test, and rightly said it couldn’t but crashed. It may
have been missing rights to edit in powershell or incorrect path. When I
get a chance I’ll try to replicate if needed and send more info.

**Comment by paul-gauthier** [comment]
I'm labeling this issue as stale because it has been open for 2 weeks with no activity. If there are no additional comments, it will be closed in 7 days.
