### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by nkeilar** [paul-gauthier/aider#1836]
Aider version: 0.58.0
Python version: 3.10.12
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-45-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1410, in send
    hash_object, completion = send_completion(
  File "sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1058, in wrapper
    raise e
  File "utils.py", line 946, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2900, in completion
    raise exception_type(
  File "main.py", line 845, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "get_llm_provider_logic.py", line 510, in get_llm_provider
    raise e
  File "get_llm_provider_logic.py", line 487, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=sonnet
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 231, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "commands.py", line 206, in do_run
    return cmd_method(args)
  File "commands.py", line 991, in cmd_architect
    return self._generic_chat_command(args, "architect")
  File "commands.py", line 1008, in _generic_chat_command
    coder.run(user_msg)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1201, in send_message
    self.reply_completed()
  File "architect_coder.py", line 39, in reply_completed
    editor_coder.run(with_message=content, preproc=False)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1131, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

Here is a second related report 

# Uncaught AttributeError in sendchat.py line 30

Aider version: 0.58.0
Python version: 3.10.12
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-45-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1410, in send
    hash_object, completion = send_completion(
  File "sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1058, in wrapper
    raise e
  File "utils.py", line 946, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2900, in completion
    raise exception_type(
  File "main.py", line 845, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "get_llm_provider_logic.py", line 510, in get_llm_provider
    raise e
  File "get_llm_provider_logic.py", line 487, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=claude-3-5-sonnet
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1201, in send_message
    self.reply_completed()
  File "architect_coder.py", line 39, in reply_completed
    editor_coder.run(with_message=content, preproc=False)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1131, in send_message
    except retry_exceptions() as err:
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
AttributeError: module 'litellm.llms.anthropic.chat' has no attribute 'AnthropicError'

```

**Comment by nkeilar** [comment]
Blocked so digging deeper. Recreated venv, no luck. Additional information. I'm running with the architecture mode 

```
Aider v0.58.0
Main model: o1-preview with architect edit format
Editor model: anthropic/claude-3-5-sonnet with editor-diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 18 files
Repo-map: using 4096 tokens, files refresh
Warning: map-tokens > 2048 is not recommended as too much irrelevant code can confuse LLMs.
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Document src/content_crew/main.py                                                                                                         

Add src/content_crew/main.py to the chat? (Y)es/(N)o/(D)on't ask again [Yes]:                                                               
To document src/content_crew/main.py, make the following modifications:                                                                     

 1 Add a module-level docstring at the top of the file to describe the purpose of the module.                                               
                                                                                                                                            
    """Main module to execute the Content Generation Crew process."""                                                                       
                                                                                                                                            
   Insert this docstring immediately after the imports:                                                                                     
                                                                                                                                            
    from crew import ContentGenerationCrew                                                                                                  
                                                                                                                                            
    """Main module to execute the Content Generation Crew process."""                                                                       
                                                                                                                                            
 2 Add a docstring to the main function to explain its functionality.                                                                       
                                                                                                                                            
    def main():                                                                                                                             
        """Initialize and run the content generation crew, then print the result."""                                                        
        crew = ContentGenerationCrew()                                                                                                      
        result = crew.run()                                                                                                                 
        print("Content Generation Result:")                                                                                                 
        print(result)                                                                                                                       
                                                                                                                                            
 3 Add an inline comment before the conditional check to explain its purpose.                                                               
                                                                                                                                            
    # Run the main function if the script is executed directly                                                                              
    if __name__ == "__main__":                                                                                                              
        main()                                                                                                                              
                                                                                                                                            

These changes will provide clear documentation for the module and its main function.                                                        

Tokens: 1.2k sent, 1.3k received. Cost: $0.10 message, $0.10 session.
Edit the files? (Y)es/(N)o [Yes]:                                                                                                           
Unexpected error: litellm.NotFoundError: AnthropicException - {"type":"error","error":{"type":"not_found_error","message":"model: 
claude-3-5-sonnet"}}
Traceback (most recent call last):
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/main.py", line 1586, in completion
    response = anthropic_chat_completions.completion(
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/llms/anthropic/chat.py", line 1139, in completion
    response = client.post(
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 371, in post
    raise e
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 357, in post
    response.raise_for_status()
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.anthropic.com/v1/messages'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1129, in send_message
    yield from self.send(messages, functions=self.functions)
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1410, in send
    hash_object, completion = send_completion(
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/aider/sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/utils.py", line 1086, in wrapper
    raise e
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/utils.py", line 974, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/main.py", line 2847, in completion
    raise exception_type(
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/utils.py", line 8194, in exception_type
    raise e
  File "/home/nathank/venvs/aider/lib/python3.10/site-packages/litellm/utils.py", line 6656, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: AnthropicException - 
{"type":"error","error":{"type":"not_found_error","message":"model: claude-3-5-sonnet"}}
```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.58.0, installed using Python 3.12.6
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by nkeilar** [comment]
@fry69 thanks for your assistance. That did not work. I already had aider instealled in a seperate venv but I nuked it and setup with pipx - are you able to reproduce invoking aider like this: 

```
aider --o1-preview --architect --editor-model anthropic/claude-3-5-sonnet --map-tokens 4096 --cache-prompts --no-stream --cache-keepalive-pings 2
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.58.0
Main model: o1-preview with architect edit format
Editor model: anthropic/claude-3-5-sonnet with editor-diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 18 files
Repo-map: using 4096 tokens, files refresh
Warning: map-tokens > 2048 is not recommended as too much irrelevant code can confuse LLMs.
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Document src/content_crew/main.py                                                                                                         

Add src/content_crew/main.py to the chat? (Y)es/(N)o/(D)on't ask again [Yes]:                                                               
To document the src/content_crew/main.py file, please make the following modifications:                                                     

 1 Add a module-level docstring at the top of the file to describe the purpose of the module. Insert this immediately after the import      
   statements.                                                                                                                              
                                                                                                                                            
    """                                                                                                                                     
    Main module to run the Content Generation Crew application.                                                                             
    """                                                                                                                                     
                                                                                                                                            
    from crew import ContentGenerationCrew                                                                                                  
                                                                                                                                            
 2 Add a docstring to the main() function to explain its functionality.                                                                     
                                                                                                                                            
    def main():                                                                                                                             
        """                                                                                                                                 
        Initializes and runs the ContentGenerationCrew, then prints the result.                                                             
        """                                                                                                                                 
        crew = ContentGenerationCrew()                                                                                                      
        result = crew.run()                                                                                                                 
        print("Content Generation Result:")                                                                                                 
        print(result)                                                                                                                       
                                                                                                                                            
 3 Optionally, add inline comments for clarity (if needed). Since the code is straightforward, this step is optional.                       

By adding these docstrings, we improve the readability and maintainability of the code, making it clearer for other developers or users who 
interact with this script.                                                                                                                  

Tokens: 1.2k sent, 1.2k received. Cost: $0.09 message, $0.09 session.
Edit the files? (Y)es/(N)o [Yes]:                                                                                                           
Unexpected error: litellm.NotFoundError: AnthropicException - {"type":"error","error":{"type":"not_found_error","message":"model: 
claude-3-5-sonnet"}}
Traceback (most recent call last):
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/main.py", line 1586, in completion
    response = anthropic_chat_completions.completion(
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/llms/anthropic/chat.py", line 1139, in 
completion
    response = client.post(
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 371, 
in post
    raise e
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 357, 
in post
    response.raise_for_status()
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.anthropic.com/v1/messages'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1129, in 
send_message
    yield from self.send(messages, functions=self.functions)
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1410, in send
    hash_object, completion = send_completion(
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/sendchat.py", line 83, in send_completion
    res = litellm.completion(**kwargs)
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/utils.py", line 1086, in wrapper
    raise e
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/utils.py", line 974, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/main.py", line 2847, in completion
    raise exception_type(
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/utils.py", line 8194, in exception_type
    raise e
  File "/home/nathank/.local/share/pipx/venvs/aider-chat/lib/python3.10/site-packages/litellm/utils.py", line 6656, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: AnthropicException - 
{"type":"error","error":{"type":"not_found_error","message":"model: claude-3-5-sonnet"}}


```

**Comment by fry69** [comment]
Your editor model is wrong, use `--editor-model anthropic/claude-3-5-sonnet-20240620`

**Comment by nkeilar** [comment]
When I invoked aider like this it works, `aider --sonnet --map-tokens 4096 --cache-prompts --no-stream --cache-keepalive-pings 2` to edit files... but not as I did above. 

... feels like a bug

**Comment by fry69** [comment]
It is not a bug. Use this line ->
```
aider --o1-preview --architect --editor-model anthropic/claude-3-5-sonnet-20240620--map-tokens 4096 --cache-prompts --no-stream --cache-keepalive-pings 2
```

**Comment by nkeilar** [comment]
Thanks! Was not clear what to put as the --editor-model I tried everything but `anthropic/claude-3-5-sonnet-20240620` using that solved the issue. :1st_place_medal:  @fry69

**Comment by nkeilar** [comment]
Working
