### ISSUE TITLE
Uncaught ImportError in http_handler.py line 7

### ISSUE THREAD

**Issue by DMTarmey** [paul-gauthier/aider#1882]
Aider version: 0.58.1
Python version: 3.12.6
Platform: Linux-6.11.1-2-cachyos-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.11.1-2-cachyos (64bit)
Git version: git version 2.46.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 537, in main
    main_model = models.Model(
                 ^^^^^^^^^^^^^
  File "models.py", line 646, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 845, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "__init__.py", line 8, in <module>
    from litellm.llms.custom_httpx.http_handler import AsyncHTTPHandler, HTTPHandler
  File "http_handler.py", line 7, in <module>
    from httpx import USE_CLIENT_DEFAULT
ImportError: cannot import name 'USE_CLIENT_DEFAULT' from 'httpx' (/home/dmtarmey/MyProjects/aider-env/lib/python3.12/site-packages/httpx/__init__.py)

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.58.1, installed using Python 3.12.6
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html
