### ISSUE TITLE
Error calling check_model_availability on Azure OpenAI

### ISSUE THREAD

**Issue by klehmann** [paul-gauthier/aider#220]
Hi!

I am trying to set up Aider with our Azure OpenAI services deployment. I configured it to use gpt-4 (will try gpt-4-32k later if required for larger context window), but the execution fails when calling check_model_availability:

```
(base) klehmann@Karstens-Mac tests % aider               
Aider v0.13.0
VSCode terminal detected, pretty output has been disabled.
Setting openai.api_base=https://our-test-env.openai.azure.com/
Setting openai.api_type=azure
Setting openai.api_version=2023-06-13
Setting openai.api_deployment_id=gpt-4
Traceback (most recent call last):
  File "/Users/klehmann/opt/anaconda3/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/main.py", line 464, in main
    coder = Coder.create(
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 66, in create
    if not check_model_availability(main_model):
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 903, in check_model_availability
    available_models = openai.Model.list()
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```

I tweaked models.py to skip the check_model_availability call for gpt-4:

```python
        if self.is_gpt4():
            self.edit_format = "diff"
            self.use_repo_map = True
            self.send_undo_reply = True
            self.always_available = True # Karsten Lehmann, added 2023-08-25

            if tokens == 8:
                self.prompt_price = 0.03
                self.completion_price = 0.06
            elif tokens == 32:
                self.prompt_price = 0.06
                self.completion_price = 0.12

            return
```
Is this call to read the deployed models available on Azure? Am I missing something in my configuration (I am using the global YAML file)?

**Comment by klehmann** [comment]
Ok, looks like more things are not working as expected. Now I get an error when sending my first prompt.
```
Traceback (most recent call last):
  File "/Users/klehmann/opt/anaconda3/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/main.py", line 508, in main
    coder.run()
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 324, in run
    new_user_message = self.run_loop()
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 403, in run_loop
    return self.send_new_user_message(inp)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 443, in send_new_user_message
    raise err
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 436, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/coders/base_coder.py", line 556, in send
    hash_object, completion = send_with_retries(model, messages, functions, self.stream)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/aider/sendchat.py", line 61, in send_with_retries
    res = openai.ChatCompletion.create(**kwargs)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```

**Comment by klehmann** [comment]
Got it working. Had to revert my change for the openai-api-version value. I had thought this was the model version. Closing this issue. :-)

openai-api-version: 2023-03-15-preview
