### ISSUE TITLE
Idea: automatically switch from gpt-4 to gpt-4-32k

### ISSUE THREAD

**Issue by klehmann** [paul-gauthier/aider#229]
When the context window for gpt-4 is (about to be) exceeded, Aider could automatically switch to gpt-4-32k and resend the data/prompt.

**Comment by azazar** [comment]
Keep in mind that gpt-4-32k isn't available to everyone. I can access it only through Openrouter

**Comment by mikeslattery** [comment]
Alternatively, if you won't have gpt-4-32k, it could use gpt-3.5-turbo-16k.  It won't work as well, of course, but at least it will have a chance.  Maybe spit out a warning.

**Comment by joshuavial** [comment]
Ī like the idea but would personally like to see it as a setting as I think some folks would prefer to see an error that they've busted their context window instead of auto bumping and doubling (at least) their spend rate.

**Comment by paul-gauthier** [comment]
I think the sensible thing is just to quit aider and re-run with `--model gpt-4-32k`. You can use the up-arrow to re-send the last request that blew up the context window.

You couldn't really "live" switch from gpt-4 -> gpt-3.5-16k. They use different edit formats, so the entire conversation history would need to be discarded anyway. So you might as well quit and relaunch aider.

I tihnk the only other thing you lose is the set of files which were added to the chat?

**Comment by joshuavial** [comment]
Maybe a --resume flag would be useful? It could call summarize history on the last session and re-add the same files, we'd need to update the chat history format to include the file names in the context window (or similar).

**Comment by Troubladore** [comment]
I feel like this is a translation issue. There is some fundamental representation of the conversation history, which passes through a function to shape it appropriately when you want to continue a conversation thread with a particular endpoint.

This is probably a "future" problem, but it would be a lot more fluent than stopping and starting your session all the time. Eventually you'll want to persist conversations, so you can resume them across sessions.

**Comment by alexanderkjeldaas** [comment]
For some of these models, the cost of the cheaper ones are dwarfed by the more expensive ones, so it does not cost much to always run `gpt3-16k` when running `gpt4-8k`, so instead of letting the user figure out when `gpt3` could work, there can be a mode where it is always run, and the user is *informed* that gpt3 might have been good enough for this particular task.

**Comment by VictorBargains** [comment]
I think there is a lot of room for improvement of the meta-llm-model layer. Not only could it intelligently switch from one model to another if it knows a larger context is available, but it also could switch to a cheaper model if it detects a rate limit or some other error. For instance, I keep getting these from gpt-4 which makes me wish it could switch back to gpt-3.5-turbo without me having to deal with this awful crash message and losing some progress:

```
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 0.8 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 0.1 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 3.6 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 4.3 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 12.2 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 24.6 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 27.0 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 53.1 seconds.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 25.7 seconds.
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\Scripts\aider.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\main.py", line 667, in main
    coder.run()
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\coders\base_coder.py", line 400, in run
    new_user_message = self.run_loop()
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\coders\base_coder.py", line 484, in run_loop
    return self.send_new_user_message(inp)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\coders\base_coder.py", line 585, in send_new_user_message
    saved_message = self.auto_commit(edited)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\coders\base_coder.py", line 1029, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, prefix="aider: ")
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\repo.py", line 73, in commit
    commit_message = self.get_commit_message(diffs, context)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\repo.py", line 124, in get_commit_message
    commit_message = simple_send_with_retries(self.client, model.name, messages)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\sendchat.py", line 71, in simple_send_with_retries
    _hash, response = send_with_retries(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\aider\sendchat.py", line 61, in send_with_retries
    res = client.chat.completions.create(**kwargs)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_utils\_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\resources\chat\completions.py", line 645, in create
    return self._post(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 853, in request
    return self._request(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 916, in _request
    return self._retry_request(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 958, in _retry_request
    return self._request(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 916, in _request
    return self._retry_request(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 958, in _retry_request
    return self._request(
  File "C:\Users\victorb\AppData\Roaming\Python\Python310\site-packages\openai\_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

There exist community standards for the config_list of various LLMs and URLs and API keys -- so either that standard should be extended with a field that lets you specify when and why you would prefer that LLM over others (cheaper, higher context, faster, better for code, better for simple questions, better when giving 10 examples, etc).

**Comment by paul-gauthier** [comment]
Given that most everyone is using the 128k context GPT-4 Turbo models, I'm not sure this auto-switch concept is relevant any longer.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by mikeslattery** [comment]
> I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

I agree with your reason for closing.  However, I think a `/model` command would be useful for this case and many others.  For example, a user could switch to a better models upon a failure, or to a cheaper model when doing something simple (like copywriting).

I make a similar comment to you on reddit this week.

**Comment by paul-gauthier** [comment]
Yup, `/model` would be a good solution. It's on the roadmap.
