### ISSUE TITLE
IndexError: string index out of range (Java)

### ISSUE THREAD

**Issue by wwestenbrink** [paul-gauthier/aider#24]
Hi Paul, amazing tool you've created here!

Trying it out with a java project I encountered the following error:

```
string index out of range

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aider/coder.py", line 803, in apply_updates
    edited = method(content)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aider/coder.py", line 616, in update_files_gpt4
    if utils.do_replace(full_path, original, updated, self.dry_run):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aider/utils.py", line 216, in do_replace
    new_content = replace_most_similar_chunk(content, before_text, after_text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aider/utils.py", line 99, in replace_most_similar_chunk
    res = replace_part_with_missing_leading_whitespace(whole, part, replace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aider/utils.py", line 70, in replace_part_with_missing_leading_whitespace
    if all(pline[0].isspace() for pline in part_lines):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aider/utils.py", line 70, in <genexpr>
    if all(pline[0].isspace() for pline in part_lines):
           ~~~~~^^^
IndexError: string index out of range
```

Seems at least on the `part_lines` was empty here, crashing the program.

updating utils.py#70 to:
`    if all((len(pline)> 0 and pline[0].isspace()) for pline in part_lines): `
fixed the problem

Let me know if you like a PR.

**Comment by paul-gauthier** [comment]
Thanks for reporting the bug and providing the fix. If you install from GitHub, it will have the fix now.
