### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ryanfreckleton** [paul-gauthier/aider#273]
I'm consistently getting this when attempting to run various commands.

Traceback (most recent call last):
  File "/home/ryan/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/ryan/.local/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/main.py", line 538, in main
    coder.run()
  File "/home/ryan/.local/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 328, in run
    new_user_message = self.send_new_user_message(new_user_message)
  File "/home/ryan/.local/pipx/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 431, in send_new_user_message
    messages += self.done_messages
TypeError: 'NoneType' object is not iterable

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

What version are you running?

**Comment by ryanfreckleton** [comment]
0.14.1

```
% aider --version
aider 0.14.1
```

My pleasure. Aider is a lot of fun to use and I'm happy to help! Please let me know if there's anything else I should add or do to make this easier (besides fixing it myself ;-) )

**Comment by paul-gauthier** [comment]
Thanks again for sharing the stack trace. The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
