### ISSUE TITLE
[BUG] New version crashes due to sound module

### ISSUE THREAD

**Issue by arash-cid** [paul-gauthier/aider#274]
**aider v(0.14.1)**

Running aider inside docker with python3 gives this error:

```errorr
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/soundfile.py", line 170, in <module>
    raise OSError('sndfile library not found using ctypes.util.find_library')
OSError: sndfile library not found using ctypes.util.find_library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/vscode/.local/lib/python3.11/site-packages/aider/main.py", line 11, in <module>
    from aider.coders import Coder
  File "/home/vscode/.local/lib/python3.11/site-packages/aider/coders/__init__.py", line 1, in <module>
    from .base_coder import Coder
  File "/home/vscode/.local/lib/python3.11/site-packages/aider/coders/base_coder.py", line 20, in <module>
    from aider.commands import Commands
  File "/home/vscode/.local/lib/python3.11/site-packages/aider/commands.py", line 11, in <module>
    from aider import prompts, voice
  File "/home/vscode/.local/lib/python3.11/site-packages/aider/voice.py", line 8, in <module>
    import soundfile as sf
  File "/home/vscode/.local/lib/python3.11/site-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)

```

**Comment by paul-gauthier** [comment]
What OS are you running?

Have you installed port audio?

https://aider.chat/docs/install.html#install-portaudio-optional

**Comment by arash-cid** [comment]
docker `ubuntu:22.04`

**Comment by paul-gauthier** [comment]
Ah, I see what's happening now. Not sure why your system is failing to `import soundfile` though. That's a standard pip-installed python library.

In any case, I have made aider tolerate a failed import of soundfile by simply disabling `/voice` since it is indeed an optional feature.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by arash-cid** [comment]
Thanks @paul-gauthier 
Apologies I forgot about this one, 
Just checked now and it is working like a charm 

Thank youuu
