### ISSUE TITLE
Non-relative patterns are unsupported

### ISSUE THREAD

**Issue by Storhemulen** [paul-gauthier/aider#279]
Fresh install on ubuntu 22.04
I cant get it to work with my files.
Any tips?

`ubuntu@Ubuntu:~/starkekjell$ aider

Aider v0.14.1
Model: gpt-4
Git repo: .git
Repo-map: basic using 1024 tokens (ctags executable not found)
Use /help to see in-chat commands, run with --help to see cmd line args
───────────────────────────────────────────────────────────────────────────────
/add xxxxxxxx.ps1 /add xxxxxxxxx.txt /add xxxxxxxxxxxxx.ps1                    

Traceback (most recent call last):
File "/home/ubuntu/.local/bin/aider", line 8, in <module>
sys.exit(main())
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/main.py", line 538, in main
coder.run()
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 325, in run
new_user_message = self.run_loop()
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 404, in run_loop
return self.commands.run(inp)
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/commands.py", line 74, in run
return self.do_run(matching_commands[0][1:], rest_inp)
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/commands.py", line 52, in do_run
return cmd_method(args)
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/commands.py", line 289, in cmd_add
matched_files = self.glob_filtered_to_repo(word)
File "/home/ubuntu/.local/lib/python3.10/site-packages/aider/commands.py", line 252, in glob_filtered_to_repo
raw_matched_files = list(Path(self.coder.root).glob(pattern))
File "/usr/lib/python3.10/pathlib.py", line 1032, in glob
raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
ubuntu@Ubuntu:~/starkekjell$`

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Did you actually enter `/add xxxxxxxx.ps1 /add xxxxxxxxx.txt /add xxxxxxxxxxxxx.ps1` all on one line? You only need to start the line with `/add` and then follow it with all the filenames.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
