### ISSUE TITLE
Invalid glob pattern crashes chat

### ISSUE THREAD

**Issue by KillerGoldFisch** [paul-gauthier/aider#293]
When trying to add files using an invalid glob pattern, the chat crashes.

Aider version: v0.15.0
OS: Ubuntu 22.04
Python version: 3.10

Example Chat:
```
Aider v0.15.0
VSCode terminal detected, pretty output has been disabled.
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /add **.txt                                                                                                                                                              

Traceback (most recent call last):
  File "/usr/local/py-utils/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/main.py", line 564, in main
    coder.run()
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 326, in run
    new_user_message = self.run_loop()
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/coders/base_coder.py", line 405, in run_loop
    return self.commands.run(inp)
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/commands.py", line 73, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/commands.py", line 51, in do_run
    return cmd_method(args)
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/commands.py", line 293, in cmd_add
    matched_files = self.glob_filtered_to_repo(word)
  File "/usr/local/py-utils/venvs/aider-chat/lib/python3.10/site-packages/aider/commands.py", line 256, in glob_filtered_to_repo
    raw_matched_files = list(Path(self.coder.root).glob(pattern))
  File "/usr/lib/python3.10/pathlib.py", line 1033, in glob
    selector = _make_selector(tuple(pattern_parts), self._flavour)
  File "/usr/lib/python3.10/pathlib.py", line 374, in _make_selector
    raise ValueError("Invalid pattern: '**' can only be an entire path component")
ValueError: Invalid pattern: '**' can only be an entire path component
```

This exits aider.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I just pushed a fix.  The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
