### ISSUE TITLE
Crashing when adding file that listed in `.gitignore`

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#316]
# Output
```
$ aider 
Aider v0.16.3                                                                                                                                                         
VSCode terminal detected, pretty output has been disabled.
Model: gpt-4
Git repo: .git
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  

> /undo                                                                          

The last commit was not made by aider in this chat session.
You could try `/git reset --hard HEAD^` but be aware that this is a destructive 
command!
─────────────────────────────────────────────────────────────────────────────────
> /add tmp/wordpress.py                                                                                                                                                

Traceback (most recent call last):
  File "/home/user/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/aider/main.py", line 564, in main
    coder.run()
  File "/home/user/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 319, in run
    new_user_message = self.run_loop()
  File "/home/user/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 398, in run_loop
    return self.commands.run(inp)
  File "/home/user/.local/lib/python3.10/site-packages/aider/commands.py", line 73, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "/home/user/.local/lib/python3.10/site-packages/aider/commands.py", line 51, in do_run
    return cmd_method(args)
  File "/home/user/.local/lib/python3.10/site-packages/aider/commands.py", line 316, in cmd_add
    self.coder.repo.repo.git.add(abs_file_path)
  File "/home/user/.local/lib/python3.10/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git add /home/user/Projects/_projectname_/tmp/wordpress.py
  stderr: 'The following paths are ignored by one of your .gitignore files:
tmp
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"'
```

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by azazar** [comment]
It doesn't crash anymore. But still fails.

```
$ aider 
Aider v0.16.4-dev
VSCode terminal detected, pretty output has been disabled.
Model: gpt-4
Git repo: .git
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /add tmp/wordpress.py                                                                                                                                              

No files matched 'tmp/wordpress.py'. Do you want to create /home/user/Projects/_projectname_/tmp/wordpress.py? n
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /add tmp/task_prompt.md                                                                                                                                            

Unable to add /home/user/Projects/_projectname_/tmp/task_prompt.md: Cmd('git') failed due to: exit code(1)
  cmdline: git add /home/user/Projects/_projectname_/tmp/task_prompt.md
  stderr: 'The following paths are ignored by one of your .gitignore files:
tmp
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"'
```

**Comment by paul-gauthier** [comment]
Ya, there isn't a great choice for how to handle this situation. I think this is the best behavior. Aider expects to use git to commit changes that it makes. This keeps your source code safe. It can't do that if you ask it to `/add` a file which is part of `.gitignore`. 

You can work around this by:

1. Editing `.gitignore` so the file is not ignored, or.
2. Run `aider --no-git` to tell it that you don't want it to manage the files with git.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
