### ISSUE TITLE
When I drop all files, and add one I have traceback and aider exits.

### ISSUE THREAD

**Issue by tonymacx86PRO** [paul-gauthier/aider#33]
```
Traceback (most recent call last):
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\main.py", line 293, in main
    coder.run()
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 328, in run
    new_user_message = self.run_loop()
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 392, in run_loop
    return self.commands.run(inp)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\commands.py", line 58, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\commands.py", line 43, in do_run
    return cmd_method(args)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\commands.py", line 254, in cmd_add
    self.coder.abs_fnames.add(abs_file_path)
AttributeError: 'list' object has no attribute 'add'
```

**Comment by paul-gauthier** [comment]
Good find, and thanks for reporting this issue. I just pushed a fix.

You'll need to install the latest from github to pick it up. Please let me know if you have any more problems.

```
pip install git+https://github.com/paul-gauthier/aider.git
```

**Comment by tonymacx86PRO** [comment]
It actually works!!!
