### ISSUE TITLE
aider crashed when adding directory of just created git submodule

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#336]
Created with :

```
{/run 
command ; 
command ;
...
many commands ; 
used { .. } to make `/run` with multiple commands ending with `;` just in case ;
...
}
```

git submodule (subdirectory).
And wanted to add it :

```
(...)

VALL-E-X
Add these files to the chat? y
Traceback (most recent call last):
  File "/home/gw-t490/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/main.py", line 566, in main
    coder.run()
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 336, in run
    new_user_message = self.send_new_user_message(new_user_message)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 424, in send_new_user_message
    self.choose_fence()
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 255, in choose_fence
    for _fname, content in self.get_abs_fnames_content():
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 244, in get_abs_fnames_content
    content = self.io.read_text(fname)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gw-t490/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/io.py", line 144, in read_text
    with open(str(filename), "r", encoding=self.encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/gw-t490/d/23Q4/code/misc/vall-e-x_example/VALL-E-X'
```

Bigger part of transcript:
https://gist.github.com/gwpl/8c33ed8f25df33855be925eb77b1ecb8

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I just pushed a fix.  The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by gwpl** [comment]
I tried to reproduce and I couldn't . So hopefully fix is working well! Thank you!
