### ISSUE TITLE
Adding plenty of files made aider crash due to a RateLimit error (gpt-4-1106-preview)

### ISSUE THREAD

**Issue by younes-io** [paul-gauthier/aider#358]
So, I was using aider, and added all the contents of a folder like this: 
`/add libs/langchain/langchain/vectorstores/*`
This obviously added all files, but triggered a crash due to the RateLimit error..

```
(plenty of files)...
Added libs/langchain/langchain/vectorstores/redis/constants.py to the chat
Added libs/langchain/langchain/vectorstores/redis/base.py to the chat
Added libs/langchain/langchain/vectorstores/deeplake.py to the chat
Added libs/langchain/langchain/vectorstores/hologres.py to the chat
Added libs/langchain/langchain/vectorstores/chroma.py to the chat
Added libs/langchain/langchain/vectorstores/utils.py to the chat
Added libs/langchain/langchain/vectorstores/neo4j_vector.py to the chat
Added libs/langchain/langchain/vectorstores/dingo.py to the chat
Added libs/langchain/langchain/vectorstores/weaviate.py to the chat
Added libs/langchain/langchain/vectorstores/azure_cosmos_db.py to the chat
Added libs/langchain/langchain/vectorstores/base.py to the chat
Added libs/langchain/langchain/vectorstores/bageldb.py to the chat
Added libs/langchain/langchain/vectorstores/clarifai.py to the chat
Added libs/langchain/langchain/vectorstores/milvus.py to the chat
Added libs/langchain/langchain/vectorstores/dashvector.py to the chat
Added libs/langchain/langchain/vectorstores/scann.py to the chat
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 0.2 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 1.3 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 3.2 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 3.0 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 11.6 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 16.2 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 48.1 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 35.9 seconds.
Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
Retry in 15.9 seconds.
Traceback (most recent call last):
  File "/home/user_github/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/user_github/.local/lib/python3.10/site-packages/aider/main.py", line 566, in main
    coder.run()
  File "/home/user_github/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 336, in run
    new_user_message = self.send_new_user_message(new_user_message)
  File "/home/user_github/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 449, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
  File "/home/user_github/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 569, in send
    hash_object, completion = send_with_retries(model, messages, functions, self.stream)
  File "/home/user_github/.local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/user_github/.local/lib/python3.10/site-packages/aider/sendchat.py", line 64, in send_with_retries
    res = openai.ChatCompletion.create(**kwargs)
  File "/home/user_github/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/user_github/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create      
    response, _, api_key = requestor.request(
  File "/home/user_github/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/user_github/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/user_github/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Request too large for gpt-4-1106-preview in organization org-s43*******************T on tokens per min (TPM): Limit 300000, Requested 335205. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.

```

I think the reties configured to 10 maybe aren't enough to make the program crash.. I think it should retry indefinitely until it finishes embedding or completion or whatever it's doing.. What do you think ?
BTW, this is how I ran it `aider --model gpt-4-1106-preview --no-auto-commits --pretty`

**Comment by paul-gauthier** [comment]
See #205.
