### ISSUE TITLE
"The '...' model doesn't exist" crash

### ISSUE THREAD

**Issue by divan** [paul-gauthier/aider#367]
I just installed aider on the latest MacOS, created a new OpenAI API Key (I'm on the paid plan and do have access to GPT-4).
Without tweaking any variables, that's the output and an error I got.
What could be the reason?

```
Aider v0.18.0
Model: gpt-4
Git repo: .git
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Can you explain what this repo is doing?

Traceback (most recent call last):
  File "/Users/divan/Library/Python/3.9/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/main.py", line 566, in main
    coder.run()
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/coders/base_coder.py", line 329, in run
    new_user_message = self.run_loop()
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/coders/base_coder.py", line 412, in run_loop
    return self.send_new_user_message(inp)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/coders/base_coder.py", line 473, in send_new_user_message
    raise err
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/coders/base_coder.py", line 466, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/coders/base_coder.py", line 586, in send
    hash_object, completion = send_with_retries(model, messages, functions, self.stream)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/aider/sendchat.py", line 64, in send_with_retries
    res = openai.ChatCompletion.create(**kwargs)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Is this reproducible for you? It should not be possible for this to happen. Aider checks with OpenAI to see which models you key can use on startup. If it got this far, OpenAI said your key was good for `gpt-4`.

My guess is that this was some sort of transient outage/problem with OpenAI's API service.

**Comment by divan** [comment]
Hmm, you're probably right. Just tried it again and can't reproduce.
