### ISSUE TITLE
running LM Studio locally with model: codellama-7b-instruct

### ISSUE THREAD

**Issue by MrGordonElliott** [paul-gauthier/aider#368]
Loving AIDER.  Thank you !!!

I have a problem.  I am trying to get LM Studio running locally with Aider

i have the follow code in my aider.config.yml

`#LM Studio
openai-api-base: http://localhost:1234/v1
openai-api-key: 'sk-or-v1-xxxxx'
model: codellama-7b-instruct`

my error is

`
Aider v0.18.0
VSCode terminal detected, pretty output has been disabled.
Setting openai.api_base=http://localhost:1234/v1
Traceback (most recent call last):
  File "D:\miniconda3\envs\aider\lib\runpy.py", line 196, in _run_module_as_main        
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\envs\aider\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\miniconda3\envs\aider\Scripts\aider.exe\__main__.py", line 7, in <module>    
  File "D:\miniconda3\envs\aider\lib\site-packages\aider\main.py", line 504, in main    
    main_model = models.Model.create(args.model)
  File "D:\miniconda3\envs\aider\lib\site-packages\aider\models\model.py", line 26, in create
    return OpenAIModel(name)
  File "D:\miniconda3\envs\aider\lib\site-packages\aider\models\openai.py", line 30, in __init__
    raise ValueError(f"Unknown context window size for model: {name}")
ValueError: Unknown context window size for model: codellama-7b-instruct`

any ideas please.

**Comment by apcameron** [comment]
Change the model name to gpt-3.5-turbo-16k in your aider.config.yml
That will give it a 16k context window and then it should work with codellama-7b-instruct.
NOTE: You may have better results with DeepSeek Coder.
Have a look at https://github.com/paul-gauthier/aider/issues/172 for further details.

**Comment by paul-gauthier** [comment]
I'm going to close this as a dup of #172. But feel free to re-open or file a new issue if you need more help.
