### ISSUE TITLE
Benchmark docker container assert error?

### ISSUE THREAD

**Issue by zestysoft** [paul-gauthier/aider#369]
Heya, I just followed the instructions [here](https://github.com/paul-gauthier/aider/tree/main/benchmark#setup-for-benchmarking) on building the docker container to run benchmarks.  However, when I attempt to execute, I'm getting an assertion error:
```
root@1475a4ab83fe:/aider# ./benchmark/benchmark.py a-helpful-name-for-this-run --model gpt-3.5-turbo --edit-format whole --threads 1
Traceback (most recent call last):
  File "/aider/./benchmark/benchmark.py", line 772, in <module>
    app()
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 716, in main
    return _main(
  File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/aider/./benchmark/benchmark.py", line 366, in main
    assert ORIGINAL_DNAME.exists() and ORIGINAL_DNAME.is_dir(), ORIGINAL_DNAME
AssertionError: /benchmarks/exercism-python
```

Indeed, there is no /benchmarks/exercism-python file or folder.

**Comment by apcameron** [comment]
Create a symlink like this  exercism-python -> practice

**Comment by paul-gauthier** [comment]
Thanks for the PR with the fix!

I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
