### ISSUE TITLE
Crash issue folowing pip update of openai-1.3.5 with Aider 0.18

### ISSUE THREAD

**Issue by kolergy** [paul-gauthier/aider#376]
The error is as follow when I try to start Aider, I've just updated the openai library and aider on this computer. is there a change in syntax on the openai side?
`aider
Traceback (most recent call last):
  File "/home/xx/miniforge3/envs/my_env/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/xx/miniforge3/envs/my_env/lib/python3.11/site-packages/aider/main.py", line 10, in <module>
    from aider import __version__, models
  File "/home/xx/miniforge3/envs/my_env/lib/python3.11/site-packages/aider/models/__init__.py", line 5, in <module>
    GPT4 = Model.create("gpt-4")
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniforge3/envs/my_env/lib/python3.11/site-packages/aider/models/model.py", line 24, in create
    if "openrouter.ai" in openai.api_base:
                          ^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'api_base'. Did you mean: 'api_type'?`

**Comment by kcolemangt** [comment]
Yes. Revert to the older package.
```
pip install openai==0.28.1
```
