### ISSUE TITLE
When git user and email are not set, don't dump a bunch of useless info to the screen

### ISSUE THREAD

**Issue by harleypig** [paul-gauthier/aider#500]
```
$ aider
Aider v0.25.0
Model: gpt-4-1106-preview using udiff edit format
Git repo: .git with 112 files
Repo-map: using 2048 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```
If the git user and email are not set, aider dumps a bunch of unnecessary info to the screen.
```
Committing config/shell-startup/git before applying edits.
Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m Remove unnecessary directory creation for git state home. --no-verify -- /home/harleypig/projects/dotfiles/config/shell-startup/git
  stderr: 'Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'harleypig@yippy.(none)')'

Traceback (most recent call last):
  File "/home/harleypig/.local/share/python/lib/python3.10/site-packages/aider/coders/base_coder.py", line 942, in apply_updates
    edited = self.update_files()
  File "/home/harleypig/.local/share/python/lib/python3.10/site-packages/aider/coders/base_coder.py", line 936, in update_files
    edits = self.prepare_to_edit(edits)
  File "/home/harleypig/.local/share/python/lib/python3.10/site-packages/aider/coders/base_coder.py", line 929, in prepare_to_edit
    self.dirty_commit()
  File "/home/harleypig/.local/share/python/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1042, in dirty_commit
    self.repo.commit(fnames=self.need_commit_before_edits)
  File "/home/harleypig/.local/share/python/lib/python3.10/site-packages/aider/repo.py", line 94, in commit
    self.repo.git.commit(cmd)
  File "/usr/local/lib/python3.10/dist-packages/git/cmd.py", line 736, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/git/cmd.py", line 1316, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/git/cmd.py", line 1111, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m Remove unnecessary directory creation for git state home. --no-verify -- /home/harleypig/projects/dotfiles/config/shell-startup/git
  stderr: 'Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'harleypig@yippy.(none)')'
Update exception #1, retrying...
Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m Remove unnecessary directory creation for git state home. --no-verify --
/home/harleypig/projects/dotfiles/config/shell-startup/git
  stderr: 'Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'harleypig@yippy.(none)')'
It seems you're encountering an issue with Git not being able to identify the author for commits. This is a configuration
issue that needs to be resolved before you can successfully make commits. You need to set your Git user name and email
address.

However, as an expert software developer, I can only provide you with the necessary commands to fix this issue, but I
cannot execute them for you. Here are the commands you would typically run to set your Git identity:


 git config --global user.email "you@example.com"
 git config --global user.name "Your Name"


Replace "you@example.com" with your email address and "Your Name" with your name. If you want to set the identity only
for the current repository, omit the --global flag.

Please run these commands in your terminal, and then try your Git commit again. If you need further assistance with the
configuration or have other requests for code changes, feel free to ask.
```
Instead of using up tokens, you could run `git config --list | grep -E '^user\.(email|name)='` (or equivalent in python) on startup and just die immediately if they aren't set because nothing will be able to be committed without those settings.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

That output is coming from your local `git` binary. Aider already does exactly what you suggest, and confirms that the repo has user name and email set when it launches.

https://github.com/paul-gauthier/aider/blob/f45887d176a97ef7d902e666b771dce81ef6037a/aider/main.py#L61

It sounds like there is something unusual happening with your local git repo. Based on that error the user email is set, but it is set to a value which git considers to be invalid: `harleypig@yippy.(none)`.

Maybe try setting the email to a valid email address?

**Comment by harleypig** [comment]
I don't think I explained myself well. :)

I know the problem (the email defaults to $USER@$(hostname), though I can't remember where the `none` comes from). I cloned this repository to a new setup and forgot to configure the name and email.

But the error output above shows a Python traceback and then a response from the AI. The traceback is okay, I guess, but this kind of error shouldn't be using up tokens.

**Comment by paul-gauthier** [comment]
I see. The problem has nothing to do with user.email. It appears you have one set, which your local git is unhappy with. FWIW, my local git doesn't care about weird emails.

The problem is that errors from the local git invocations shouldn't get reflected back to the LLM. Agreed. I made that change. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by harleypig** [comment]
`user.name` and `user.email` are not set, `config/shell-startup/git` is added but not commited (ignore `gitconfig.user.bak`, it holds my user name and email) and I get the expected error.
```
$ git config --list | grep -E '^user\.(name|email)=' ; git status -s ; git commit -m 'test'
M  config/shell-startup/git
?? gitconfig.user.bak
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'harleypig@yippy.(none)')
```
Now I'm not getting the error at all and three attempts before dying.
```
$ aider config/shell-startup/git
Aider v0.25.1-dev
Model: gpt-4-1106-preview using udiff edit format
Git repo: .git with 112 files
Repo-map: using 2048 tokens
Added config/shell-startup/git to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
config/shell-startup/git
> Remove the git_remove_missing_files function


 --- config/shell-startup/git
 +++ config/shell-startup/git
 @@ ... @@
 -# XXX: Remove this
 -function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }
 -
  function gtoplevel() {
    git rev-parse --show-toplevel 2> /dev/null || {



Committing config/shell-startup/git before applying edits.
Malformed response #1, retrying...
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files
UnifiedDiffNoMatch: hunk failed to apply!

config/shell-startup/git does not contain lines that match the diff you provided!
Try again.
DO NOT skip blank lines, comments, docstrings, etc!
The diff needs to apply cleanly to the lines in config/shell-startup/git!

config/shell-startup/git does not contain these 5 exact lines in a row:
\`\`\`
# XXX: Remove this
function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }

function gtoplevel() {
  git rev-parse --show-toplevel 2> /dev/null || {
\`\`\`


 --- config/shell-startup/git
 +++ config/shell-startup/git
 @@ ... @@
 -# XXX: Remove this
 -function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }
 -
  function gtoplevel() {
    git rev-parse --show-toplevel 2> /dev/null || {



Committing config/shell-startup/git before applying edits.
Malformed response #2, retrying...
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files
UnifiedDiffNoMatch: hunk failed to apply!

config/shell-startup/git does not contain lines that match the diff you provided!
Try again.
DO NOT skip blank lines, comments, docstrings, etc!
The diff needs to apply cleanly to the lines in config/shell-startup/git!

config/shell-startup/git does not contain these 5 exact lines in a row:
\`\`\`
# XXX: Remove this
function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }

function gtoplevel() {
  git rev-parse --show-toplevel 2> /dev/null || {
\`\`\`


 --- config/shell-startup/git
 +++ config/shell-startup/git
 @@ ... @@
 -# XXX: Remove this
 -function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }
 -
  function gtoplevel() {
    git rev-parse --show-toplevel 2> /dev/null || {



Committing config/shell-startup/git before applying edits.
Malformed response #3, aborting.
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files
UnifiedDiffNoMatch: hunk failed to apply!

config/shell-startup/git does not contain lines that match the diff you provided!
Try again.
DO NOT skip blank lines, comments, docstrings, etc!
The diff needs to apply cleanly to the lines in config/shell-startup/git!

config/shell-startup/git does not contain these 5 exact lines in a row:
\`\`\`
# XXX: Remove this
function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }

function gtoplevel() {
  git rev-parse --show-toplevel 2> /dev/null || {
\`\`\`
```

**Comment by harleypig** [comment]
Feh. That's what I get for doing too many things at once. Ignore my previous ~~idiocy~~post.

This is working.
