### ISSUE TITLE
Aider is crashing when context becomes too large and claude-3-opus model is selected

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#515]
Aider v0.27.0

Command: `aider --openrouter --model anthropic/claude-3-opus --openai-api-key *****`

```
Traceback (most recent call last):
  File "/home/m/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/main.py", line 667, in main
    coder.run()
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 403, in run
    new_user_message = self.send_new_user_message(new_user_message)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 539, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 665, in send
    self.show_send_output_stream(completion)
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 748, in show_send_output_stream
    for chunk in completion:
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_streaming.py", line 43, in __iter__
    for item in self._iterator:
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_streaming.py", line 62, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
```

**Comment by paul-gauthier** [comment]
What does `/tokens` show you before such a crash?

**Comment by azazar** [comment]
I can't reproduce it after applying the last update and modifying the project code.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here if you are able to repo and I will re-open.
