### ISSUE TITLE
Crash when git is in detached HEAD state

### ISSUE THREAD

**Issue by SupraSummus** [paul-gauthier/aider#520]
When git is not on any branch there is a crash.

This is on version `v0.26.0`.

Trace:
```
Traceback (most recent call last):
  File "/usr/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/aider/main.py", line 656, in main
    coder.run()
  File "/usr/lib/python3.11/site-packages/aider/coders/base_coder.py", line 403, in run
    new_user_message = self.send_new_user_message(new_user_message)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aider/coders/base_coder.py", line 585, in send_new_user_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aider/coders/base_coder.py", line 1029, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, prefix="aider: ")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aider/repo.py", line 66, in commit
    diffs = self.get_diffs(fnames)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aider/repo.py", line 141, in get_diffs
    commits = self.repo.iter_commits(self.repo.active_branch)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/git/repo/base.py", line 958, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/git/refs/symbolic.py", line 383, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '00adf5e33da5b25a9f63fb2faa13aea176144f17'
```

And side note: thank you for developing and publishing the aider in open way. I appreciate it! ;)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This does seem like a bug in the corner case of detached head. I'll work on a solution.

**Comment by paul-gauthier** [comment]
I've fixed this issue and will merge to main soon.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
