### ISSUE TITLE
It seems Azure Open AI stopped working in v0.29.0

### ISSUE THREAD

**Issue by mikeplavsky** [paul-gauthier/aider#568]
With .aider.config.yml:
```
openai-api-key: *****
openai-api-base: *****
openai-api-version: 2024-02-15-preview
model: azure/gpt-4-turbo
weak-model: azure/gpt-4-turbo
```
Getting this error: 
```
Aider v0.29.0
To use model azure/gpt-4-turbo, please set these environment variables:- AZURE_API_BASE- AZURE_API_VERSION- AZURE_API_KEY
```
After adding AZURE_API_BASE, AZURE_API_VERSION, AZURE_API_KEY to the environment: 
```
Aider v0.29.0
Models: gpt-4-turbo with udiff edit format, weak model gpt-4-turbo
Git repo: .git with 149 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```
and then after saying Hi:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 332, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 514, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 581, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/main.py", line 1009, in completion
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/main.py", line 982, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 420, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/main.py", line 685, in main
    coder.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/coders/base_coder.py", line 392, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/coders/base_coder.py", line 476, in run_loop
    return self.send_new_user_message(inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/coders/base_coder.py", line 531, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/coders/base_coder.py", line 651, in send
    hash_object, completion = send_with_retries(model, messages, functions, self.stream)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aider/sendchat.py", line 50, in send_with_retries
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/utils.py", line 2965, in wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/utils.py", line 2863, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/main.py", line 2136, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/utils.py", line 8628, in exception_type
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/utils.py", line 7440, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
mike@MIKEP01-MAC aider %

**Comment by mikeplavsky** [comment]
If I follow this example: https://docs.litellm.ai/docs/providers/azure#completion---using-env-variables with the same environment variables I get the answer from Azure OpenAI: 

```
from litellm import completion
completion(model='azure/gpt-4-turbo', messages = [{ "content": "Hello, how are you?","role": "user"}])
``` 

ModelResponse(id='chatcmpl-9GeLLl8DLUFM36nGHm8MnH2eJmQxE', choices=[Choices(finish_reason='stop', index=0, message=Message(content="Hello! I'm just a computer program, so I don't have feelings, but I'm here and ready to assist you with any questions or tasks you have. How can I help you today?", role='assistant'))], created=1713755355, model='gpt-4', object='chat.completion', system_fingerprint='fp_2f57f81c11', usage=Usage(completion_tokens=40, prompt_tokens=13, total_tokens=53))

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Sorry you're having trouble connecting to Azure. It's possible that something in the latest version isn't working quite right.

Can you try removing your `.aider.conf.yml` file and running aider like this:

```
AZURE_API_KEY=your-key-goes-here
AZURE_API_VERSION=2023-05-15
AZURE_API_BASE=https://example-endpoint.openai.azure.com
aider --model azure/<your_deployment_name>
```

If that works I can make some changes to aider to make this simpler/easier.

**Comment by mikeplavsky** [comment]
Without `.aider.config.yml`: 

```
aider --model azure/gpt-4-turbo
Aider v0.29.1
To use model gpt-3.5-turbo, please set these environment variables:- OPENAI_API_KEY
```

**Comment by paul-gauthier** [comment]
Ah ok, thanks for working through this with me. We need to tell aider to use Azure for the "weak model" too:

Can you try this? Again, with no `.aider.conf.yml`. We're just adding: `--weak-model azure/<your_deployment_name>`

```
export AZURE_API_KEY=your-key-goes-here
export AZURE_API_VERSION=2023-05-15
export AZURE_API_BASE=https://example-endpoint.openai.azure.com
aider --model azure/<your_deployment_name> --weak-model azure/<your_deployment_name> 
```

**Comment by mikeplavsky** [comment]
`aider --model azure/gpt-4-turbo --weak-model azure/gpt-4-turbo` also crashes: 

```
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by paul-gauthier** [comment]
Ok, thanks. I think I fixed the issue. Thanks again for all the help working through this and debugging it.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by mikeplavsky** [comment]
Thank you a lot. Now it works: 

```
mike@MIKEP01-MAC aider % aider --model azure/gpt-4-turbo --weak-model azure/gpt-4-turbo
Aider v0.29.2-dev
Models: azure/gpt-4-turbo with udiff edit format, weak model azure/gpt-4-turbo
Git repo: .git with 155 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Please don't change any code, I am reading.

Understood, I'll wait for your instructions when you're ready.
```

**Comment by paul-gauthier** [comment]
Great! With this new version, you shouldn't need to manually specify `--weak-model`. Aider will automatically use the main model as the weak model for azure if none is specified. You can of course specify a different weak model if you'd like.

**Comment by mikeplavsky** [comment]
Fixed
