### ISSUE TITLE
Crash: AttributeError: 'SyntaxError' object has no attribute 'end_lineno'

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [paul-gauthier/aider#619]
### Issue

Hi, encountered that error multiple times now. It completely crashes aider and forces me to manually revert the partial changes then relaunch aider.

It seems to happen when gpt4o botched an edit so bad that it ends up creating a syntax error, which is not properly catched by the linter.

Full trace:
```
Applied edit to VideoFlow.py
Traceback (most recent call last):
  File "/home/USER.local/lib/python3.9/site-packages/aider/linter.py", line 130, in lint_python_compile
    compile(code, fname, "exec")  # USE TRACEBACK BELOW HERE
  File "/home/USERDownloads/VideoFlow/VideoFlow.py", line 39
    Initialize the VideoFlow class with a video path.
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/USER.local/lib/python3.9/site-packages/aider/main.py", line 457, in main
    coder.run()
  File "/home/USER.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 545, in run
    list(self.send_new_user_message(new_user_message))
  File "/home/USER.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 783, in send_new_user_message
    lint_errors = self.lint_edited(edited)
  File "/home/USER.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 825, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
  File "/home/USER.local/lib/python3.9/site-packages/aider/linter.py", line 80, in lint
    linkres = cmd(fname, rel_fname, code)
  File "/home/USER.local/lib/python3.9/site-packages/aider/linter.py", line 98, in py_lint
    compile_res = lint_python_compile(fname, code)
  File "/home/USER.local/lib/python3.9/site-packages/aider/linter.py", line 133, in lint_python_compile
    line_numbers = list(range(err.lineno - 1, err.end_lineno))
AttributeError: 'SyntaxError' object has no attribute 'end_lineno'
```

### Version and model info

Aider==0.2.4
Aider-chat==0.36.0
GPT-4o

Edit format: the one by default for GPT-4o

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've fixed this bug. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
