### ISSUE TITLE
Issue using Azure OpenAI models

### ISSUE THREAD

**Issue by vladiliescu** [paul-gauthier/aider#672]
### Issue

I'm having trouble using any Azure model. My setup:

.env

```
AZURE_API_KEY="xxx"
AZURE_API_VERSION="2024-02-01"
AZURE_API_BASE="https://xxx.openai.azure.com"
```

## First issue
Running `aider --models azure` will list all Azure models supported by Aider (I guess?) and not my actual deployed models, which may or may not have different names. i.e. I'm using `GPT4` which is not present in the list but it's unclear whether I should send this string to Aider, or deploy a new model named `gpt-4`. As you can imagine, running `aider --model azure/GPT4` results in the warnings below

```
Model azure/GPT4: Unknown model, context window size and token costs unavailable.
Did you mean one of these?
- azure/gpt-4
- azure/gpt-4o
- azure/gpt-4-32k
For more info see https://aider.chat/docs/llms.html#model-warnings
```

## Second issue
Even if I create a new deployment (`gpt-4`) and invoke aider as `aider --model azure/gpt-4`, it will crash complaining that it cannot find the deployment.

```
Traceback (most recent call last):
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/llms/azure.py", line 292, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/llms/azure.py", line 508, in streaming
    response = azure_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/main.py", line 905, in completion
    response = azure_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/llms/azure.py", line 374, in completion
    raise AzureOpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.azure.AzureOpenAIError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vladi/miniconda3/envs/aider/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/aider/main.py", line 457, in main
    coder.run()
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/aider/coders/base_coder.py", line 588, in run
    list(self.send_new_user_message(new_user_message))
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/aider/coders/base_coder.py", line 790, in send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/aider/coders/base_coder.py", line 963, in send
    hash_object, completion = send_with_retries(
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/aider/sendchat.py", line 71, in send_with_retries
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/utils.py", line 3317, in wrapper
    raise e
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/utils.py", line 3211, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/main.py", line 2368, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/utils.py", line 9709, in exception_type
    raise e
  File "/Users/vladi/miniconda3/envs/aider/lib/python3.11/site-packages/litellm/utils.py", line 9545, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: AzureException - Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
```

I'm running this on a fresh conda environment, `conda create -n aider python=3.11`, `aider-chat` being the only package installed in there.

### Version and model info

Aider v0.37.0
Model: azure/gpt-4 with diff edit format
Git repo: .git with 10 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can ignore the `Model azure/GPT4: Unknown model, context window size and token costs unavailable.` warning. It's just a warning.

Use `--model azure/your-deployment-name`.

https://aider.chat/docs/llms/azure.html

**Comment by vladiliescu** [comment]
And thank you for writing aider, it's a pretty cool tool.

That's not it though -- the lack of info re: which models are/aren't available isn't the main issue (I mentioned creating a deployment named gpt-4 and it still didn't work), the main issue is that it didn't work for my setup, even after using an actual deployment.

And, I think I've tracked down the cause of this -- looks like if I have some other azure open ai keys defined in my .env (which of course I have, because I'm using them in my project), then aider will try to use those? Looks like it. Here's a simple repro:

This works:
```
AZURE_API_KEY="xxx"
AZURE_API_VERSION="2024-02-01"
AZURE_API_BASE="https://xxx.openai.azure.com"
```

This doesn't work, aider seems to use the `AZURE_OPENAI_*` stuff (`litellm.exceptions.AuthenticationError: AzureException - Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}`
```
AZURE_API_KEY="xxx"
AZURE_API_VERSION="2024-02-01"
AZURE_API_BASE="https://xxx.openai.azure.com"

AZURE_OPENAI_API_KEY="xxx"
AZURE_OPENAI_API_VERSION="2024-02-01"
AZURE_OPENAI_MODEL="xxx"
AZURE_OPENAI_INSTANCE_NAME="xxx"
```

**Comment by paul-gauthier** [comment]
Glad you've figured out the issue. I added a note to the [aider azure docs](https://aider.chat/docs/llms/azure.html) that `AZURE_OPENAI_API_xxx` variables are also used.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
