### ISSUE TITLE
Using the aider open large git repository

### ISSUE THREAD

**Issue by vernon2gh** [paul-gauthier/aider#702]
### Issue

Here I use aider to open the Linux kernel repository, which is about 6GB size. The following error is displayed:

If it is because the git repository is too large, can compile_commands.json be used to reduce the index of the git repository source code?

```bash
$ aider
Traceback (most recent call last):
  File "/home/test/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python3.10/site-packages/aider/main.py", line 414, in main
    coder.show_announcements()
  File "/home/test/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 356, in show_announcements
    for line in self.get_announcements():
  File "/home/test/.local/lib/python3.10/site-packages/aider/coders/base_coder.py", line 159, in get_announcements
    num_files = len(self.repo.get_tracked_files())
  File "/home/test/.local/lib/python3.10/site-packages/aider/repo.py", line 213, in get_tracked_files
    for blob in commit.tree.traverse():
  File "/home/test/.local/lib/python3.10/site-packages/git/objects/util.py", line 575, in _traverse
    addToStack(stack, item, branch_first, nd)
  File "/home/test/.local/lib/python3.10/site-packages/git/objects/util.py", line 535, in addToStack
    lst = self._get_intermediate_items(item)
  File "/home/test/.local/lib/python3.10/site-packages/git/objects/tree.py", line 207, in _get_intermediate_items
    return tuple(index_object._iter_convert_to_object(index_object._cache))
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/home/test/.local/lib/python3.10/site-packages/git/objects/tree.py", line 214, in _set_cache_
    self._cache: List[TreeCacheTup] = tree_entries_from_data(ostream.read())
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/base.py", line 138, in read
    return self[3].read(size)
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/stream.py", line 487, in read
    bl = self._size - self._br      # bytes left
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/stream.py", line 461, in _set_cache_brute_
    apply_delta_data(bbuf, src_size, ddata, len(ddata), tbuf.write)
  File "/home/test/.local/lib/python3.10/site-packages/gitdb/fun.py", line 673, in apply_delta_data
    raise ValueError("unexpected delta opcode 0")
ValueError: unexpected delta opcode 0
```

### Version and model info

Aider v0.39.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This may be due to the index version of that repo. See #211 for more info.

**Comment by vernon2gh** [comment]
Thanks for your reply.

My git version is 2.34.1, it is an unknown option `--show-index-version`, but the `aider --no-git` command is normally working.

After adding a file to the aider, let analysis a function, but another error appears below.
It looks like this file has too much content, can the file content be sent in multiple parts?

```bash
$ aider --no-git                
Aider v0.39.0
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: none
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────
> /add mm/vmscan.c                                                                                                                                                                                                                          

Added /home/test/workplaces/upstream/linux/mm/vmscan.c to the chat
────────────────────────────────────────────────────────
mm/vmscan.c                                                                                                                                                                                                                                 
> analysis shrink_folio_list function  
litellm.APIConnectionError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o in organization org-xxx on tokens per min (TPM): Limit 30000, Requested 54736. The input or output tokens must be red
uced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}                                                                  
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.10/site-packages/litellm/llms/openai.py", line 799, in completion
    raise e
  File "/home/test/.local/lib/python3.10/site-packages/litellm/llms/openai.py", line 718, in completion
    return self.streaming(
  File "/home/test/.local/lib/python3.10/site-packages/litellm/llms/openai.py", line 896, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
  File "/home/test/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/test/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o in organization org-xxx on tokens per min (TPM): Limit 30000, Requested 54736. The input or output tokens must be reduced 
in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
```

**Comment by paul-gauthier** [comment]
It looks like your OpenAI API key doesn't have enough quote to work with large files yet.

**Comment by LZING** [comment]
> It looks like your OpenAI API key doesn't have enough quote to work with large files yet.

So how should we deal with large code repositories? Sending only part of the source code will affect the context. Now it seems that only Gemini 1.5pro can handle about 200m tokens, which is the upper limit.

**Comment by paul-gauthier** [comment]
This is a problem with your specific OpenAI API key. OpenAI usually limits new API users to a very low quota. As you use the API more and pay them more money they usually give you full access.

**Comment by vernon2gh** [comment]
> This is a problem with your specific OpenAI API key. OpenAI usually limits new API users to a very low quota. As you use the API more and pay them more money they usually give you full access.

Can the file content be sent in multiple parts? If yes, we can avoid this limit.

**Comment by paul-gauthier** [comment]
Unfortunately no. You need to get your OpenAI API key working correctly.

**Comment by LZING** [comment]
> Unfortunately no. You need to get your OpenAI API key working correctly.

Hi, paul.
But I feel that this is not a problem with OpenAI tokens. Even if you are an enterprise user's token, it is limited by LLM long context memory. OpenAI currently only supports up to 128k input. However, this should not be enough for user tokens in large code repositories.

**Comment by paul-gauthier** [comment]
> openai.RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o in organization org-xxx on tokens per min (TPM): Limit 30000, Requested 54736. The input or output tokens must be reduced 
in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

I was responding about the error above that was reported earlier in the issue. If you follow the url in the error message it will provide more detail about OpenAI rate limits. 

Their rate limits have nothing to do with the models context window. Here's some info about how aider manages files and other repo context:

https://aider.chat/docs/usage.html#adding-files

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
