### ISSUE TITLE
module 'litellm' has no attribute 'validate_environment'

### ISSUE THREAD

**Issue by ramsey-coding** [paul-gauthier/aider#724]
### Issue

I can't run repomap and get the following error:

```
   res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm' has no attribute 'validate_environment'
```

I installed the dependencies from the Aider repo using:

```pip install -r requirements.txt```

**Comment by paul-gauthier** [comment]
Sorry, can you be more clear about exactly what you are doing to see this error?

**Comment by Symbolk** [comment]
I also encountered errors with litellm, but it is:
AttributeError: module 'litellm' has no attribute 'exceptions'

However, the venv\Lib\site-packages\litellm\exceptions.py does exist and can be opened in PyCharm.
litellm==1.40.26

**Comment by paul-gauthier** [comment]
This is probably due to an issue with your local python environment. Are you doing something other than running off a vanilla `pip install aider-chat`?

**Comment by Symbolk** [comment]
> This is probably due to an issue with your local python environment. Are you doing something other than running off a vanilla `pip install aider-chat`?

I directly cloned the code, pip install -r req.txt,  and ran aider/main.py, which throws the error:
```
Traceback (most recent call last):
  File "D:\coding\ai\aider\aider\main.py", line 15, in <module>
    from aider.coders import Coder
  File "D:\coding\ai\aider\aider\coders\__init__.py", line 1, in <module>
    from .base_coder import Coder
  File "D:\coding\ai\aider\aider\coders\base_coder.py", line 22, in <module>
    from aider.history import ChatSummary
  File "D:\coding\ai\aider\aider\history.py", line 5, in <module>
    from aider.sendchat import simple_send_with_retries
  File "D:\coding\ai\aider\aider\sendchat.py", line 38, in <module>
    litellm.exceptions.APIConnectionError,
AttributeError: module 'litellm' has no attribute 'exceptions'
```

**Comment by Zzhiter** [comment]
metoo
