### ISSUE TITLE
TypeError: CaptureIO.tool_output() got an unexpected keyword argument 'log_only'

### ISSUE THREAD

**Issue by sanity** [paul-gauthier/aider#740]
### Issue

2024-06-27 12:47:51.479 Uncaught app exception
Traceback (most recent call last):
  File "/home/ian/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/gui.py", line 543, in <module>
    status = gui_main()
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/gui.py", line 539, in gui_main
    GUI()
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/gui.py", line 374, in __init__
    self.process_chat()
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/gui.py", line 417, in process_chat
    res = st.write_stream(self.coder.run_stream(prompt))
  File "/home/ian/miniconda3/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/streamlit/elements/write.py", line 167, in write_stream
    for chunk in stream:  # type: ignore
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 588, in run_stream
    yield from self.send_new_user_message(user_message)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 880, in send_new_user_message
    test_errors = self.commands.cmd_test(self.test_cmd)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 544, in cmd_test
    return self.cmd_run(args, True)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 582, in cmd_run
    self.io.tool_output(line, log_only=True)
TypeError: CaptureIO.tool_output() got an unexpected keyword argument 'log_only'

### Version and model info

Aider v0.40.6
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 72 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've pushed a fix.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
