### ISSUE TITLE
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.

### ISSUE THREAD

**Issue by jagoff2** [paul-gauthier/aider#744]
### Issue

running a fork of openpilot through aider and received the following error

2024-06-28 13:32:29.131 Uncaught app exception
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/gui.py", line 543, in <module>
    status = gui_main()
             ^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/gui.py", line 539, in gui_main
    GUI()
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/gui.py", line 374, in __init__
    self.process_chat()
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/gui.py", line 417, in process_chat
    res = st.write_stream(self.coder.run_stream(prompt))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/streamlit/elements/write.py", line 167, in write_stream
    for chunk in stream:  # type: ignore
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/coders/base_coder.py", line 588, in run_stream
    yield from self.send_new_user_message(user_message)
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/coders/base_coder.py", line 806, in send_new_user_message
    messages = self.format_messages()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/coders/base_coder.py", line 762, in format_messages
    messages += self.get_files_messages()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/coders/base_coder.py", line 530, in get_files_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/coders/base_coder.py", line 520, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/repomap.py", line 84, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/repomap.py", line 407, in get_ranked_tags_map
    num_tokens = self.token_count(tree)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/models.py", line 419, in token_count
    return len(self.tokenizer(msgs))
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/aider/models.py", line 408, in tokenizer
    return litellm.encode(model=self.name, text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/litellm/utils.py", line 1496, in encode
    enc = tokenizer_json["tokenizer"].encode(text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tiktoken/core.py", line 117, in encode
    raise_disallowed_special_token(match.group())
  File "/home/user/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tiktoken/core.py", line 400, in raise_disallowed_special_token
    raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.

### Version and model info

--browser

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It sounds like you are using a local API server and a local model? It appears they may not be compatible with litellm, which aider users to connect to LLMs.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by maxim-saplin** [comment]
I have error, the problem is due to one of the source files used in chat has the special token in it, e.g. here's a piece of my Python file:
```
        # Did first attempt with direct apply_chat_template without add_generation_prompt=True and adjusting result, trained for a few epochs, bot turned up crazy
        # 'prompt': '<|user|>\nQ:Question: how ... Yes or no.\nA:<|endoftext|>\n',
...
```

As you can see I am experimenting with tokenizer and actually have the token mentioned in the comments.

Seems like setting `disallowed_special` to a few ChatML values (e.g. <|endoftext|>,  <|assistant|> etc.) might help solving the issues. 

The case is relevant for those ones tinkering with HF Transformers and finetuning models.
