### ISSUE TITLE
An error occurred after commit

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#757]
### Issue

Latest sources, an error occurred after commit

Exception in thread Thread-1686 (summarize_worker):
Traceback (most recent call last):
  File "/home/eryk/micromamba/envs/genai/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/eryk/micromamba/envs/genai/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eryk/micromamba/envs/genai/lib/python3.12/site-packages/aider/coders/base_coder.py", line 688, in summarize_worker
    self.summarized_done_messages = self.summarizer.summarize(self.done_messages)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eryk/micromamba/envs/genai/lib/python3.12/site-packages/aider/history.py", line 64, in summarize
    model_max_input_tokens = self.model.info.get("max_input_tokens", 4096) - 512
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

### Version and model info

Aider v0.40.7-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 36 files
Repo-map: using 2028 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I'll fix this bug.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
