### ISSUE TITLE
I have installed by "Pip install aider-chat"  after I run browser it shows error

### ISSUE THREAD

**Issue by MAhmadUzair** [paul-gauthier/aider#763]
### Issue

I have installed by "Pip install aider-chat"  after I run browser it shows error

```
Creating empty file D:\dreamsleep\venv-aider\Lib\site-packages\aider\aider
Aider v0.40.6
Model: groq/llama3-8b-8192 with whole edit format
Git repo: .git with 0 files
Repo-map: disabled
Added aider to the chat.
2024-07-01 19:53:59.991 Uncaught app exception
Traceback (most recent call last):
  File "D:\dreamsleep\venv-aider\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 543, in <module>
    status = gui_main()
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 539, in gui_main
    GUI()
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 367, in __init__
    self.do_sidebar()
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 150, in do_sidebar
    self.do_add_to_chat()
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 179, in do_add_to_chat
    self.do_add_files()
  File "D:\dreamsleep\venv-aider\Lib\site-packages\aider\gui.py", line 183, in do_add_files
    fnames = st.multiselect(
  File "D:\dreamsleep\venv-aider\lib\site-packages\streamlit\runtime\metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "D:\dreamsleep\venv-aider\lib\site-packages\streamlit\elements\widgets\multiselect.py", line 258, in multiselect
    return self._multiselect(
  File "D:\dreamsleep\venv-aider\lib\site-packages\streamlit\elements\widgets\multiselect.py", line 304, in _multiselect
    indices = _check_and_convert_to_indices(opt, default)
  File "D:\dreamsleep\venv-aider\lib\site-packages\streamlit\elements\widgets\multiselect.py", line 97, in _check_and_convert_to_indices
    raise StreamlitAPIException(
streamlit.errors.StreamlitAPIException: The default value 'aider' is part of the options. Please make sure that every default values also exists in the options.
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like you ran aider from a directory deep inside the virtual environment. That may have caused import problems. 

Try running aider from a directory with code you want to edit, or from an empty directory.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
