### ISSUE TITLE
Error on OpenAI API Compatible End Point

### ISSUE THREAD

**Issue by stin7** [paul-gauthier/aider#788]
### Issue

I have a local dev server running a local model that is compatible with the OpenAI API.

I'd like to try using it with Aider.

I've reviewed https://aider.chat/docs/llms/openai-compat.html and run the following commands:

```
root@353412898c1e:/aider# aider --version
aider 0.41.1-dev
root@353412898c1e:/aider# export OPENAI_API_BASE=http://0.0.0.0:3000/v1
root@353412898c1e:/aider# export OPENAI_API_KEY=notneeded
root@353412898c1e:/aider# aider --model openai/my-custom-model # Prefix the model name with openai/
Traceback (most recent call last):
  File "/usr/local/bin/aider", line 33, in <module>
    sys.exit(load_entry_point('aider-chat', 'console_scripts', 'aider')())
  File "/aider/aider/main.py", line 413, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "/aider/aider/models.py", line 377, in __init__
    max_input_tokens = self.info.get("max_input_tokens")
AttributeError: 'NoneType' object has no attribute 'get'
```

Tracing the code my guess is that the code is looking for "my-custom-model" in [OPENAI_MODELS](https://github.com/paul-gauthier/aider/blob/main/aider/models.py#L20) which of course returns None.

Should I be creating a 'my-custom-model' config somewhere for the code to find?

### Version and model info

aider 0.41.1-dev
Model: Custom via OpenAI API Compatible Endpoint
Running in a Docker instance on a mac (following the Benchmark instructions to try to test this custom model)

**Comment by stin7** [comment]
That fixed it, thanks!
