### ISSUE TITLE
bug, AttributeError: 'EditBlockCoder' object has no attribute 'root'

### ISSUE THREAD

**Issue by wbazant** [paul-gauthier/aider#801]
### Issue

This is the bug:
 ```
 aider --sonnet --no-git src/constants/map.js src/components/connect/ConnectLocation.js src/components/desktop/MainPane.js src/components/map/TrackLocationButton.js -m 'x'
Traceback (most recent call last):
  File "/home/wbazant/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/main.py", line 424, in main
    coder = Coder.create(
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 126, in create
    res = EditBlockCoder(main_model, io, **kwargs)
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/coders/editblock_coder.py", line 20, in __init__
    super().__init__(*args, **kwargs)
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 307, in __init__
    self.check_added_files()
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 1334, in check_added_files
    relative_fname = self.get_rel_fname(fname)
  File "/home/wbazant/.local/lib/python3.9/site-packages/aider/coders/base_coder.py", line 1224, in get_rel_fname
    return os.path.relpath(fname, self.root)
AttributeError: 'EditBlockCoder' object has no attribute 'root'
```

It happens occasionally, and I've only seen it today (since last update 0.41 -> 0.42) and with --no-git.

I can share the four files with you - they're from https://github.com/falling-fruit/falling-fruit-web - but I suspect the contents don't matter because the error message mentions paths.

I tried shrinking the bug by producing variations fewer files than all four, different orders, etc. but best I could do was realising the -m arg content doesn't matter. `--no-git` is essential for the bug to stay in, though.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I think I've fixed this bug.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by wbazant** [comment]
FYI, the new download size is very large after adding torch, made me run out of disk space a few times after downloading / installing:
```
Collecting torch==2.2.2 (from aider-chat==0.42.1.dev0)
  Downloading torch-2.2.2-cp39-cp39-manylinux1_x86_64.whl (755.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.9 MB/s eta 0:00:00

Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 5.4 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 6.7 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 7.5 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 3.3 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.9 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 6.3 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 6.0 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 4.3 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 3.0 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 5.2 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.6 MB/s eta 0:00:00
Collecting triton==2.2.0 (from torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading triton-2.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 MB 3.0 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->aider-chat==0.42.1.dev0)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 8.3 MB/s eta 0:00:00
```

**Comment by wbazant** [comment]
Looks like the issue is fixed, thanks!
