### ISSUE TITLE
Crash on running on a dir without .git dir

### ISSUE THREAD

**Issue by bitdeep** [paul-gauthier/aider#831]
### Issue

> aid is a alias `DOSKEY AID=aider --model openrouter/anthropic/claude-3.5-sonnet --edit-format whole --no-attribute-author --dark-mode --edit-format diff --map-tokens 1024 --yes $*`
```cmd

D:\ai\sdk>ls
.                  Queue.ts           package-lock.json  redis.ts
..                 colors.ts          package.json       templates
ApiServer.ts       mysql.ts           public             utils.ts
Base.ts            node_modules       redis              yarn.lock

D:\ai\sdk>aid ApiServer.ts Base.ts colors.ts utils.ts
Git repository created in the current working directory.
Added .aider* to .gitignore
Update git name with: git config user.name "Your Name"
Update git email with: git config user.email "you@example.com"
thread '<unnamed>' panicked at src\validators\mod.rs:399:23:
Error building schema validator:
  MemoryError: 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\python311\Lib\site-packages\aider\main.py", line 438, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\aider\models.py", line 373, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\aider\models.py", line 556, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\aider\llm.py", line 19, in __getattr__
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\python311\Lib\site-packages\litellm\__init__.py", line 9, in <module>
    from litellm.caching import Cache
  File "C:\python311\Lib\site-packages\litellm\caching.py", line 20, in <module>
    from openai._models import BaseModel as OpenAIObject
  File "C:\python311\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\python311\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "C:\python311\Lib\site-packages\openai\types\batch.py", line 7, in <module>
    from .._models import BaseModel
  File "C:\python311\Lib\site-packages\openai\_models.py", line 36, in <module>
    from ._utils import (
  File "C:\python311\Lib\site-packages\openai\_utils\__init__.py", line 3, in <module>
    from ._utils import (
  File "C:\python311\Lib\site-packages\openai\_utils\_utils.py", line 24, in <module>
    from .._compat import parse_date as parse_date, parse_datetime as parse_datetime
  File "C:\python311\Lib\site-packages\openai\_compat.py", line 170, in <module>
    class GenericModel(pydantic.BaseModel):
  File "C:\python311\Lib\site-packages\pydantic\_internal\_model_construction.py", line 205, in __new__
    complete_model_class(
  File "C:\python311\Lib\site-packages\pydantic\_internal\_model_construction.py", line 544, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 452, in clean_schema
    schema = validate_core_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\pydantic\_internal\_core_utils.py", line 568, in validate_core_schema
    return _validate_core_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Error building schema validator:
  MemoryError:

D:\ai\sdk>
```

### Version and model info

```
Environment Variables:
  OPENAI_API_KEY:    ***

Defaults:
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --map-tokens:      1024
  --env-file:        D:\ai\sdk\.env
  --input-history-file:D:\ai\sdk\.aider.input.history
  --chat-history-file:D:\ai\sdk\.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     D:\ai\sdk\.aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --voice-language:  en
  --encoding:        utf-8

Option settings:
  - aiderignore: D:\ai\sdk\.aiderignore
  - anthropic_api_key: None
  - apply: None
  - assistant_output_color: #0088ff
  - attribute_author: True
  - attribute_commit_message: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - chat_history_file: D:\ai\sdk\.aider.chat.history.md
  - check_update: False
  - code_theme: default
  - commit: False
  - config: None
  - dark_mode: False
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - encoding: utf-8
  - env_file: D:\ai\sdk\.env
  - exit: False
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: D:\ai\sdk\.aider.input.history
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - llm_history_file: None
  - map_tokens: 1024
  - max_chat_history_tokens: None
  - message: None
  - message_file: None
  - model: None
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - models: None
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ***
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - restore_chat_history: False
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_repo_map: False
  - skip_check_update: False
  - stream: True
  - test: False
  - test_cmd: []
  - tool_error_color: #FF2222
  - tool_output_color: None
  - user_input_color: #00cc00
  - verbose: True
  - verify_ssl: True
  - vim: False
  - voice_language: en
  - weak_model: None
  - yes: None

Aider v0.43.0
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 0 files
Repo-map: using 1024 tokens
VSCode terminal detected, pretty output has been disabled.
Use /help <question> to ask for help, run with --help to see cmd line args
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> memory allocation of 7556864 bytes failed
```

**Comment by bitdeep** [comment]
Well, was qbittorrent eating like 200G of RAM, so, not sure if you guys want to handle this.
