### ISSUE TITLE
How to know if aider still running or stopped

### ISSUE THREAD

**Issue by PtradeLLC** [paul-gauthier/aider#87]
I just installed and ran aider on my codebase. Seems it's working but not sure because it's stuck at the `green arrow` on the commad line (Please see image). This is the last output i got:

```
Failed to generate commit message using gpt-3.5-turbo due to an invalid request.
Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? work in progress y

Commit b5f56b1 work in progress y
Use /help to see in-chat commands.
```
How do I know if it stopped or still running?
<img width="859" alt="Screen Shot 2023-07-11 at 4 49 11 PM" src="https://github.com/paul-gauthier/aider/assets/138940763/0897802a-1613-402e-9d30-ff23ddc89bba">

**Comment by paul-gauthier** [comment]
The green `>` prompt means aider is waiting for your input. You can type a message to GPT there and press enter. Ask it to write some code for your, or to modify one of your existing source files.

**Comment by PtradeLLC** [comment]
Thanks @paul-gauthier. I entered `y` to proceed, and got this output. I don't quite know if it's good or bad or how to proceed. What do you suggest?
```
Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Update frontend subproject commit to efccb263d7404b0d88342a7b8b211e4d3cfbe33b-dirty. y

Traceback (most recent call last):
  File "/Users/admin/anaconda3/envs/aider/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/Users/admin/anaconda3/envs/aider/lib/python3.10/site-packages/aider/main.py", line 280, in main
    coder.commit(ask=True, which="repo_files")
  File "/Users/admin/anaconda3/envs/aider/lib/python3.10/site-packages/aider/coders/base_coder.py", line 818, in commit
    repo.git.commit("-m", full_commit_message, "--no-verify")
  File "/Users/admin/anaconda3/envs/aider/lib/python3.10/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/admin/anaconda3/envs/aider/lib/python3.10/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/admin/anaconda3/envs/aider/lib/python3.10/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git commit -m Update frontend subproject commit to efccb263d7404b0d88342a7b8b211e4d3cfbe33b-dirty. y

 --no-verify
  stdout: 'On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   frontend (modified content, untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .aider.chat.history.md
        .aider.input.history
        aider/.aider.ident.cache.v1/
        aider/.aider.tags.cache.v1/
        aider/Zapier/
        aider/ctags/

no changes added to commit (use "git add" and/or "git commit -a")'
(aider) admin@AFVFHGQBRQ6L7 aider % 
```
It hasn't executed my instructions for the things I wanted done.

**Comment by paul-gauthier** [comment]
Sorry, it's a bit hard for me to try and debug the problem you are having. It sounds like it might be helpful for you to get an overview about how to work with aider? Here is a recent youtube video that provides a nice introduction to the tool and how to use it.

https://www.youtube.com/watch?v=df8afeb1FY8

Let me know if that helps orient you to the best way to work with aider.

**Comment by PtradeLLC** [comment]
Thanks again @paul-gauthier for your prompt response. Love the product

**Comment by PtradeLLC** [comment]
@paul-gauthier, sorry for the bother. I just watched that video but the guy didnt get to where i am stuck now. So I am trying to commit files cos I was prompted that git has some uncommitted file - asked if I wanted to commit? I entere `y`, but it continues in a look .. asking if I wanted to commit. Here is the output:

```
 > Git repo has uncommitted changes.  
 > Commit before the chat proceeds [y/n/commit message]? Update frontend subproject commit to efccb263d7404b0d88342a7b8b211e4d3cfbe33b-dirty. y  
+
+# aider chat started at 2023-07-11 17:53:58
+
+> /Users/admin/anaconda3/envs/aider/bin/aider  
+> No OpenAI API key provided. Use --openai-api-key or env OPENAI_API_KEY.  
+
+# aider chat started at 2023-07-11 17:54:41
+
+> /Users/admin/anaconda3/envs/aider/bin/aider  
+> No OpenAI API key provided. Use --openai-api-key or env OPENAI_API_KEY.  
+
+# aider chat started at 2023-07-11 17:55:21
+
+> /Users/admin/anaconda3/envs/aider/bin/aider  
+> Model: gpt-4  
+> Git repo: ../.git  
+> Repo-map: universal-ctags using 1024 tokens  
diff --git a/aider/.aider.ident.cache.v1/cache.db b/aider/.aider.ident.cache.v1/cache.db
index 56d9a8d..8909639 100644
Binary files a/aider/.aider.ident.cache.v1/cache.db and b/aider/.aider.ident.cache.v1/cache.db differ
diff --git a/aider/.aider.tags.cache.v1/cache.db b/aider/.aider.tags.cache.v1/cache.db
index ec5e874..1d1b25a 100644
Binary files a/aider/.aider.tags.cache.v1/cache.db and b/aider/.aider.tags.cache.v1/cache.db differ

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-
map. y/"aider_commit"

Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y/"aider_commit"
Use /help to see in-chat commands.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> y                                                                                                                                                              

diff --git a/.aider.chat.history.md b/.aider.chat.history.md
index 644a7ac..a65b63a 100644
--- a/.aider.chat.history.md
+++ b/.aider.chat.history.md
@@ -88,3 +88,7 @@
 > Repo-map: universal-ctags using 1024 tokens  
 > Git repo has uncommitted changes.  
 > Commit before the chat proceeds [y/n/commit message]? Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y/"aider_commit"  
+> Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y/"aider_commit"  
+> Use /help to see in-chat commands.  
+
+#### y  

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git
repo, and repo-map. y

Commit 6a83001 Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y
Use up-arrow to retry previous command: y
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> y                                                                                                                                                              

diff --git a/.aider.chat.history.md b/.aider.chat.history.md
index 6f49ad6..56640cb 100644
--- a/.aider.chat.history.md
+++ b/.aider.chat.history.md
@@ -94,3 +94,7 @@
 #### y  
 > Git repo has uncommitted changes.  
 > Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Commit 6a83001 Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Use up-arrow to retry previous command: y  
+
+#### y  

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git
repo, and repo-map. y

Commit 7a0357a Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y
Use up-arrow to retry previous command: y
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> y                                                                                                                                                              

diff --git a/.aider.chat.history.md b/.aider.chat.history.md
index cc8bb00..1900a94 100644
--- a/.aider.chat.history.md
+++ b/.aider.chat.history.md
@@ -100,3 +100,7 @@
 #### y  
 > Git repo has uncommitted changes.  
 > Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Commit 7a0357a Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Use up-arrow to retry previous command: y  
+
+#### y  

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git
repo, and repo-map. y

Commit 8d17e56 Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y
Use up-arrow to retry previous command: y
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> y                                                                                                                                                              

diff --git a/.aider.chat.history.md b/.aider.chat.history.md
index dadd9f7..8c58e7f 100644
--- a/.aider.chat.history.md
+++ b/.aider.chat.history.md
@@ -106,3 +106,7 @@
 #### y  
 > Git repo has uncommitted changes.  
 > Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Commit 8d17e56 Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git repo, and repo-map. y  
+> Use up-arrow to retry previous command: y  
+
+#### y  

Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]? Commit ed85475 Updated chat history with multiple chat sessions and added information about the model, git
repo, and repo-map.```

Any suggestions how to move past this?

**Comment by paul-gauthier** [comment]
It looks like you may have added `.aider.chat.history.md` and/or `.aider.input.history.md` to the git repo? You should remove them from git, as they are log files and are not intended to be placed under version control.

**Comment by PtradeLLC** [comment]
Ah, I see.. aider rookie mistake lol.. thanks for the tip. Would that be why I couldn’t commit in one go?

**Comment by PtradeLLC** [comment]
Hello @paul-gauthier . Finally got aider to stop asking me to commit file, and respond to input, but not what I expected. I asked it to rewrite the codebase based on specs I provided in a `.txt` file; but got this response instead

```
Yes, I understand. However, as an AI, I'm unable to directly write or modify code. I can guide you through the process of updating the project based on the specifications provided in the specs.txt file.                                                                                        

Here are the general steps you would need to follow:                                                                                               

 1 Set up a new Next.js project.                                                                                                                   
 2 Create the necessary components as specified in the specs.txt file.
  ...                                                                                    

Please note that this is a high-level overview. Each step will involve more detailed tasks. If you need help with a specific step or task, feel    
free to ask! 
```
Is this normal?

**Comment by paul-gauthier** [comment]
It looks like one of your initial problems was because you added the `.aider...` files to the git repo. I've updated aider to create a `.gitignore` file to try and prevent that happening. But you would have to manually remove them from your repo if they've already been added. You might look into `git rm --cached` as a way to do that.

I've merged a fix into the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
Feel free to join us in the discord if you need help debugging your aider installation. 

https://discord.com/channels/1131200896827654144/1133060264825208942

I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.
