### ISSUE TITLE
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#889]
Can't use Aider v0.45.0 with openrouter/anthropic/claude-3.5-sonnet model. It's resulting in the following error message.

```
Unexpected error: cannot access local variable 'message' where it is not associated with a value
Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 856, in completion
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 775, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 955, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 1261, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Error code: 402 - {'error': {'message': 'You are out of credits. Please visit https://openrouter.ai/credits to add more.', 'code': 402}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/main.py", line 1829, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 862, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 402 - {'error': {'message': 'You are out of credits. Please visit https://openrouter.ai/credits to add more.', 'code': 402}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 858, in send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 1110, in send
    hash_object, completion = send_with_retries(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/sendchat.py", line 53, in wrapper
    return decorated_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/sendchat.py", line 81, in send_with_retries
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/main.py", line 2605, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 7650, in exception_type
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 7580, in exception_type
    message=f"APIError: {exception_provider} - {message}",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
```

**Comment by azazar** [comment]
Aider v0.45.1 with openrouter/anthropic/claude-3.5-sonnet model does the same. It's resulting in the following error message

```
Unexpected error: cannot access local variable 'message' where it is not associated with a value
Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 856, in completion
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 775, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 955, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 1261, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Error code: 402 - {'error': {'message': 'You are out of credits. Please visit https://openrouter.ai/credits to add more.', 'code': 402}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/main.py", line 1829, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/llms/openai.py", line 862, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 402 - {'error': {'message': 'You are out of credits. Please visit https://openrouter.ai/credits to add more.', 'code': 402}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 858, in send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 1110, in send
    hash_object, completion = send_with_retries(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/sendchat.py", line 53, in wrapper
    return decorated_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/sendchat.py", line 81, in send_with_retries
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/main.py", line 2605, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 7650, in exception_type
    raise e
  File "/home/m/Private/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 7580, in exception_type
    message=f"APIError: {exception_provider} - {message}",
                                                ^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
```

**Comment by azazar** [comment]
Figured out, that it was a negative balance issue. It would be more convenient if error message could indicate that.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Your original error message contained this line, which explains that you are out of credits:

```
openai.APIStatusError: Error code: 402 - {'error': {'message': 'You are out of credits. Please visit https://openrouter.ai/credits to add more.', 'code': 402}}
```

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
