### ISSUE TITLE
adding a https/secure localhost-like url to aider triggers it to try to use playwright to add the contents of the url but playwright fails on self-signed certs

### ISSUE THREAD

**Issue by davidbuzz** [paul-gauthier/aider#905]
### Issue

heres my aider prompt that didn't work:  [ it crashes with net::ERR_CERT_AUTHORITY_INVALID ]

> please make this a web app, it will be delivered via a webpage and its url is https://localhost/new_aider_test_repo/index.php                                                              

Add https://localhost/new_aider_test_repo/index.php to the chat? y
Traceback (most recent call last):
  File "/home/buzz/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/main.py", line 586, in main
    coder.run()
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 627, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 666, in run_loop
    inp = self.check_for_urls(inp)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 676, in check_for_urls
    inp += self.commands.cmd_web(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/commands.py", line 74, in cmd_web
    content = self.scraper.scrape(url) or ""
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/scrape.py", line 93, in scrape
    content = self.scrape_with_playwright(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/scrape.py", line 128, in scrape_with_playwright
    page.goto(url, wait_until="networkidle", timeout=5000)
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 8851, in goto
    self._sync(
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost/new_aider_test_repo/index.php

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I had aider update itself so that playwright obey they `--no-verify-ssl` switch. 

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by davidbuzz** [comment]
[ ran the above command to get a new version then..]
attempted to fix and still got the error:
aider --version
aider 0.45.2-dev
aider --no-verify-ssl --model ollama/llama3.1:8b 
```
> this a web app, it will be delivered via a webpage and its url is https://localhost/new_aider_test_repo/index.php                                                                    

Add https://localhost/new_aider_test_repo/index.php to the chat? y
Traceback (most recent call last):
  File "/home/buzz/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/main.py", line 587, in main
    coder.run()
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 628, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 667, in run_loop
    inp = self.check_for_urls(inp)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/coders/base_coder.py", line 677, in check_for_urls
    inp += self.commands.cmd_web(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/commands.py", line 77, in cmd_web
    content = self.scraper.scrape(url) or ""
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/scrape.py", line 95, in scrape
    content = self.scrape_with_playwright(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/aider/scrape.py", line 131, in scrape_with_playwright
    page.goto(url, wait_until="networkidle", timeout=5000)
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 8851, in goto
    self._sync(
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buzz/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost/new_aider_test_repo/index.php
Call log:
navigating to "https://localhost/new_aider_test_repo/index.php", waiting until "networkidle"
```

**Comment by paul-gauthier** [comment]
Sorry, please try again. I've updated the fix and better tested it.

**Comment by davidbuzz** [comment]
seems better now, thx.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
