### ISSUE TITLE
Aider crashes trying to decode an emoji

### ISSUE THREAD

**Issue by bitnom** [paul-gauthier/aider#911]
### Issue

Aider tries to parse the following conditional and crashes.

```
if (chunk.content === 'Unexpected error: 'charmap' codec can't encode character '\U0001f6d1' in 
position 0: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aider\coders\base_coder.py", line 858, in send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aider\coders\base_coder.py", line 1116, in send
    yield from self.show_send_output_stream(completion)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aider\coders\base_coder.py", line 1235, in show_send_output_stream
    sys.stdout.write(text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f6d1' in position 0: character maps to <undefined>
```

Since this is happening trying to pipe to stdout, perhaps just do something like the following just for the stdout call:

```python
str(obj).encode(enc, errors='backslashreplace').decode(enc)
```

Potentially related to https://github.com/paul-gauthier/aider/issues/28

### Version and model info

Aider version: `0.45.1`
OS: Win

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
