### ISSUE TITLE
aider opens /web for github pages and crashes

### ISSUE THREAD

**Issue by lawong888** [paul-gauthier/aider#929]
I wanted Aider to reference some discussion in Github and installed Playwright with chromium, tried both pip and pipx install of Aider + Playwright, it crashes consistently trying to open this page:   https://github.com/miguelgrinberg/python-socketio/issues/35

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\lawless\.local\bin\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\main.py", line 586, in main
    coder.run()
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 627, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 663, in run_loop
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\commands.py", line 133, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\commands.py", line 108, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\commands.py", line 74, in cmd_web
    content = self.scraper.scrape(url) or ""
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\scrape.py", line 93, in scrape
    content = self.scrape_with_playwright(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\aider\scrape.py", line 131, in scrape_with_playwright
    content = page.content()
              ^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\sync_api\_generated.py", line 8747, in content
    return mapping.from_maybe_impl(self._sync(self._impl_obj.content()))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\_impl\_page.py", line 507, in content
    return await self._main_frame.content()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\_impl\_frame.py", line 416, in content
    return await self._channel.send("content")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawless\pipx\venvs\aider-chat\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.content: Unable to retrieve content because the page is navigating and changing the content.'

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

There's nothing we can do if the page won't quiesce, but we certainly shouldn't let aider crash.

I had aider fix this issue. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by NeuralAIM** [comment]
> I had aider fix this issue.

@paul-gauthier, are you using sonnet 3.5?

**Comment by paul-gauthier** [comment]
Yes I mostly use sonnet.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
