### ISSUE TITLE
Text file loading error

### ISSUE THREAD

**Issue by karenjhiggins** [paul-gauthier/aider#938]
Traceback (most recent call last):
  File "C:\Users\karen\PycharmProjects\DioceseProject\.venv\Lib\site-packages\langchain_community\document_loaders\text.py", line 43, in lazy_load
    text = f.read()
           ^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

**Comment by karenjhiggins** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 25167: character maps to <undefined>

**Comment by karenjhiggins** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 25167: character maps to <undefined>

**Comment by karenjhiggins** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 25167: character maps to <undefined>
