### ISSUE TITLE
UnboundLocalError: local variable 'instructions' referenced before assignment

### ISSUE THREAD

**Issue by sanity** [paul-gauthier/aider#961]
### Issue

When I use `/test` I get this exception:

```
Traceback (most recent call last):
  File "/home/ian/miniconda3/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/main.py", line 589, in main
    coder.run()
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 615, in run
    new_user_message = self.run_loop()
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/coders/base_coder.py", line 651, in run_loop
    return self.commands.run(inp)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 186, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 161, in do_run
    return cmd_method(args)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 624, in cmd_test
    return self.cmd_run(args, True)
  File "/home/ian/miniconda3/lib/python3.10/site-packages/aider/commands.py", line 681, in cmd_run
    if instructions:
UnboundLocalError: local variable 'instructions' referenced before assignment

```

### Version and model info

Aider v0.46.1
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've made some changes that should fix this bug.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by sanity** [comment]
Thanks @paul-gauthier, looks like that fixed it.
