### ISSUE TITLE
BUG: installing playwright

### ISSUE THREAD

**Issue by lightningRalf** [paul-gauthier/aider#970]
### Issue

when trying to install playwright I get the following error:

```
For the best web scraping, install Playwright:

playwright install --with-deps chromium

See https://aider.chat/docs/install/optional.html#enable-playwright for more info.

Install playwright? y

Installing:  playwright install --with-deps chromium
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\mjpa\.local\bin\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\main.py", line 589, in main
    coder.run()
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 615, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 654, in run_loop
    self.check_for_urls(inp)
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 666, in check_for_urls
    inp += self.commands.cmd_web(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\commands.py", line 117, in cmd_web
    res = install_playwright(self.io)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\scrape.py", line 60, in install_playwright
    success, output = utils.run_install(chromium_cmd)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjpa\pipx\venvs\aider-chat\Lib\site-packages\aider\utils.py", line 202, in run_install
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

### Version and model info

Aider v.0.46.1
Windows 11 using vs chromium

**Comment by paul-gauthier** [comment]
Thanks for sharing this error. You should be able to finish installing it like this:

```
python -m playwright install --with-deps chromium
```

I've fixed this in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
