### ISSUE TITLE
Aider launch failure with VPN on

### ISSUE THREAD

**Issue by algorithmx** [paul-gauthier/aider#984]
### Issue

I must use VPN. When I launch aider with VPN on, I got the following error message:
```
Traceback (most recent call last):
  File "/opt/AER/aider/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/aider/main.py", line 453, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/aider/models.py", line 393, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/aider/models.py", line 576, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/aider/llm.py", line 17, in __getattr__
    self._load_litellm()
  File "/opt/AER/aider/lib/python3.11/site-packages/aider/llm.py", line 24, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dabajabaza/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/AER/aider/lib/python3.11/site-packages/litellm/__init__.py", line 261, in <module>
    module_level_aclient = AsyncHTTPHandler(timeout=request_timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 30, in __init__
    self.client = self.create_client(
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 48, in create_client
    return httpx.AsyncClient(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/httpx/_client.py", line 1429, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
           ^
  File "/opt/AER/aider/lib/python3.11/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
                                  ^^^^^^^^^^^^^^
  File "/opt/AER/aider/lib/python3.11/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:12377/')

```

### Version and model info

aider 0.47.1
ubuntu 24.04

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
